### ISSUE TITLE
Hide grayed emojis

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#10]
**Describe the plugin**
So I have nitro and cba to go through an emoji list that won't load for 100 guilds but essentially if you have Nitro and ***I believe*** if a server reaches a boost level, adds more emojis, and then loses said level, those emojis are no longer accessable and therefor are gray in the emoji list. This plugin would then remove those emojis from everywhere you can pick emojis.

**Expected behavior**
^^^

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by mrrobboss** [comment]
cmon someone please for the non nitro users

**Comment by juby210-PL** [comment]
claimed

**Comment by Bowser65** [comment]
Note: you can probably achieve this by tricking the use external emoji, but that'd also nuke global emotes (Twitch, GameWisp), idk

**Comment by juby210-PL** [comment]
I don't think I need to do a plugin for it because this snippet is working: 
```js
require('powercord/webpack').getModule(['isEmojiFiltered'],false).isEmojiFiltered = require('powercord/webpack').getModule(['isEmojiFiltered'],false).isEmojiDisabled
```

**Comment by Bowser65** [comment]
You can still make a standalone plugin for it, or of you want PR it to Discord Tweaks

**Comment by juby210-PL** [comment]
done, i added this to discord-tweaks

https://github.com/NurMarvin/discord-tweaks/pull/2
