### ISSUE TITLE
Customizable guild features

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#102]
*Original request by @noirscape, see powercord-org/powercord#196*

### Description
When selecting a guild, some guilds are boosted enough (or are paid for game servers) to show a guild banner. It would be fancy and nice to be able to set the guild banner manually, even if the guild does not have a boosted banner.

At the moment this behavior is not in Powercord but is provided by a similar plugin for BetterDiscord called [EditServers](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/8bc7a19ec2531caab1e36aaa6d74c5d267948035/Plugins/EditServers/EditServers.plugin.js), which might help with development if this is to be implemented.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by redstonekasi** [comment]
i'll try to do this one

**Comment by Bowser65** [comment]
For the same reasons as mentioned in #186 this is no longer guidelines complying.
