### ISSUE TITLE
Vector Image Embed/Viewer

### ISSUE THREAD

**Issue by MulverineX** [powercord-community/suggestions#103]
**Describe the plugin**
Give you the option to embed/view vector images in-app, a common format is SVG, but support for others like .ai (illustrator), .eps, etc would be neat.

**Expected behavior**
Any posted vector images will be embedded like bitmap/regular images, and you can open them in the common image viewer. You can spoiler mark them, and they work from direct source links (like bitmap images).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
I'll consider this request as suppressed by #136
