### ISSUE TITLE
hideaway deafen/mute buttons

### ISSUE THREAD

**Issue by virivongithub** [powercord-community/suggestions#104]
**Describe the plugin**
a plugin that hides the mute and deafen button 

**Expected behavior**
so you hided the deafen buttons, what now? well i think it would be cool that you have to hover over the settings button to show the deafon/mute buttons with maybe a nice slide effect, i dont know if this is possible because of issues with lazy loading but i hope its possible

thanks in adance -viriv

concept of how it would look (hiding my tag):
![image](https://user-images.githubusercontent.com/30769091/83341795-0f3d2800-a2e8-11ea-98a8-75643786dc52.png)

**Comment by Juby210** [comment]
you can do it with just css

**Comment by virivongithub** [comment]
Ohh ok well at least I know that now so I can close this I guess
