### ISSUE TITLE
In-App Notifications

### ISSUE THREAD

**Issue by OneUpMcN** [powercord-community/suggestions#107]
### Description
The plugin would display a notification in the top-right hand corner of your discord when you were DM'd or pinged. The notification would appear for a few brief moments before disappearing unless the user hovered over the notification or pressed an **X**.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by BenSegal855** [comment]
I am going to attempt this. Be aware this is my first plugin and I don't have a ton of time to put towards it because Life™️. Please keep the up for grabs label as I will most diffidently not complete this soon and may fail. But hey, one can never learn if they never fail.

**Comment by BenSegal855** [comment]
Well I made it and it works. Its not the best but it give you notifications in app. I'll be updating it as I learn and hopefully one day it will have all the wonderful features it should. But for now, here it is:
https://github.com/BenSegal855/In-app-notifs
