### ISSUE TITLE
Typing status profile modal

### ISSUE THREAD

**Issue by Ser-Ames** [powercord-community/suggestions#108]
**Describe the plugin**
Allows the user to click on users who are typing in a chat to bring up their server profile modal thingy that shows roles and such

**Expected behavior**
explained above
(do reply if its not specific enough)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
Suggestion is no longer up for grabs and should be marked as "Completed". You can click the link below to view the plug-in's repository. Thank you.

[GriefMoDz/smart-typers](https://github.com/griefmodz/smart-typers)

**Comment by Ser-Ames** [comment]
thanks for making the plugin, this is exactly what i was requesting! you did an amazing job of it too!
