### ISSUE TITLE
Better user badges

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#11]
**Describe the plugin**
Displays the users badges after their name in chat/member list/friends list/(maybe more, idk). Basically everywhere the user's name is their badges would be after it. 

**Expected behavior**
Preferably each badge would be toggleable. Not sure how this would work with custom powercord badges however.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
i'm claiming this :eyes:

**Comment by ghostlydilemma** [comment]
owo

**Comment by Bowser65** [comment]
https://github.com/powercord-community/badges-everywhere 🎉 

More features are to come, as mentionned in the readme.md
