### ISSUE TITLE
Add DiscordRep tab to Profile popup

### ISSUE THREAD

**Issue by Freeplayg** [powercord-community/suggestions#111]
**Describe the plugin**
It would add another tab in the User profile popup that shows information about the users DiscordRep profile like votes and infractions
They have an API explained here: https://docs.discordrep.com/

**Expected behavior**
![](https://i.imgur.com/i2CZ07y.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Controlfreak707** [comment]
Sure I'll do it. I haven't made a Powercord plugin before, so it might take a bit... However the DiscordRep API looks pretty simple to use, so hopefully I'll actually get it finished.

**Comment by aetheryx** [comment]
this issue is mostly on hold until we can get in touch with discordrep. the api is authentication based, there are no real viable options (proxying all requests through a backend with a single token, hardcoding a token, making users get their own token, etc)

**Comment by Ser-Ames** [comment]
i doubt that discordrep will ever allow for some other method of auth. this plugin is gonna be a hard one to make unless you wanna host a proxy server which handles all the api requests and potentially abuse/rate limit the crap out of your token

**Comment by LilSizzurp** [comment]
Done.
https://github.com/power-plugs/powerrep/
