### ISSUE TITLE
Selection of monitor for the discord notifications 

### ISSUE THREAD

**Issue by neiii** [powercord-community/suggestions#113]
**Describe the plugin**
The plugin would allow you to select the monitor you want your discord notifications to pop up at. Useful as notifications don't pop up if you're running something fullscreen

**Expected behavior**
A basic selection menu / config file that will let you choose the monitor

**Comment by Bowser65** [comment]
I honestly don't know how feasible this is. Electron p much relies on native Windows notifications (since I believe this plugin targets Windows notifications) and I don't believe there are ways of selecting on which monitor the notification is showing up.

**Comment by CodingKanin** [comment]
Can anyone say if this is possible or not?

**Comment by KyzaGitHub** [comment]
This is possible if you use other `BrowserWindow`s as the notifications, but with remote gone it's hard to say if this would ever be a thing. Especially since so don't see it being a thing people would have fun writing.

**Comment by CodingKanin** [comment]
For now, im going to close this. If anyone finds a viable way of achieving this let me know.
