### ISSUE TITLE
Automatic groupchat leaver

### ISSUE THREAD

**Issue by Blazzycrafter** [powercord-community/suggestions#118]
Automatic groupchat leaver
----
- Important:
- I need a plugin that automatically leaves new groups and that you can give for an example give a grace period for 120 seconds 
- in which someone can invite me to groups.
----
Plus Points:

- A big settings menu (With functionality )

- A PM to the person that invited me that i dont accept group invites without me allowing it. (Customizable)

- A message to the groupchat that i dont accept group invites without me allowing it. (Customizable)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Automation like this is strictly prohibited afaik, at least according to Jake when talking about bots. Maybe @Bowser65 knows more.

**Comment by CodingKanin** [comment]
According to Bowser
> f there's a button and it's a response to a user action (as long as it doesn't do 150 billion requests yes) it's not strictly selfbotting
but at this point right click > leave is as efficient kek

So essentially this plugin isn't worth the dev time, the special features you want aren't allowed and if a plugin were to be created it would be 1 less click and probably far less ideal.
