### ISSUE TITLE
Suspicious Link Checker

### ISSUE THREAD

**Issue by misaiming** [powercord-community/suggestions#119]
**Describe the plugin**
A plugin that would add a command called '.check <link>' and would scan a website and send the results of the test; how high the risk is, if the website is on any blacklists, and anything else. The plugin could use a site such as sucuri.net, etc.

**Expected behavior**
Results of a website check would appear.

This plugin would pretty much be for lazy people like myself.

----

 - [X] I checked if this request wasn't already proposed

 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by KyzaGitHub** [comment]
[This](https://global.sitesafety.trendmicro.com/) could possibly be used to check the safety of websites.

**Comment by Juby210** [comment]
Claimed

**Comment by kam02** [comment]
Another suggestion for this, make the result also show where a link leads if it is a shorturl or redirect.

**Comment by KyzaGitHub** [comment]
> Another suggestion for this, make the result also show where a link leads if it is a shorturl or redirect.

Many short URL services have systems in place to prevent this so that they can show their advertisements and not be bypassed.

**Comment by MulverineX** [comment]
You can mostly get around this by using a webframe (would be headless chrome if you weren't already in chromium), and waiting for loading to stop, perhaps bundling an adfly(and similar services) skipper/parser script to make sure it redirects (in case it requires user interaction)

**Comment by KyzaGitHub** [comment]
> You can mostly get around this by using a webview (would be headless chrome if you weren't already in chromium), and waiting for loading to stop, perhaps bundling an adfly(and similar services) skipper/parser script to make sure it redirects (in case it requires user interaction)

The problem with this would be you're loading the website you want to check for safety.

**Comment by MulverineX** [comment]
I mean its isolated (the webview), and it would still go through the list checks first. Perhaps you could also do some performance monitoring? Not sure if that's within the capability of webview

**Comment by Juby210** [comment]
done, https://github.com/Juby210/check-site

> Another suggestion for this, make the result also show where a link leads if it is a shorturl or redirect.

but without it (for now, probably)
