### ISSUE TITLE
Emoji hover

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#12]
**Describe the plugin**
When you hover over an emoji it enlarges to a set multiplier.

**Expected behavior**
Yes this is possible with CSS however it doesn't look good and is under certain elements. ![Image](https://kanin.cannot.date/2019/10/14/jMgawc75jV.png)  ![Gif](https://kanin.cannot.date/2019/10/14/bKro5ShEpp.gif)
Preferably the emoji would be in the tooltip, with the emoji name and guild name/id where possible.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
https://www.reddit.com/r/discordapp/comments/dprn97/someone_made_a_submission_for_better_emoji/?utm_medium=android_app&utm_source=share

**Comment by CodingKanin** [comment]
> https://www.reddit.com/r/discordapp/comments/dprn97/someone_made_a_submission_for_better_emoji/?utm_medium=android_app&utm_source=share

Yes chief, this is it.

**Comment by Juby210** [comment]
I can do it like on this reddit post, so claimed, i think.

**Comment by Juby210** [comment]
done, https://github.com/Juby210/better-emoji-tooltips
