### ISSUE TITLE
Custom Bot Tags

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#120]
**Describe the plugin**
Allow the user to set the content for tags, such as server, bot, and webhook independently. 

**Expected behavior**
Settings where you type things and they change badges please uwu

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
Could this request be merged with #77 and make a "Better Tags" plugin, which would serve both purposes?

**Comment by CodingKanin** [comment]
Definitely could! I didn't find that in searching, my bad.
