### ISSUE TITLE
Trigger Words

### ISSUE THREAD

**Issue by ghostlydilemma** [powercord-community/suggestions#122]
### Description
Due to the increase in small brain Twitch lingo I have experienced multiple high intensity headaches, so I need a plugin to censor that (client side, obviously). Messages with blocked words should display in a blocked box such as they do with people you have blocked, if possible with a changed text though, so that it is obvious that the message is **not** from someone you have blocked.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Jerrynicki** [comment]
i do think that would be pretty pogchamp

**Comment by Tangytube** [comment]
so it would look kind of like this?
![image](https://user-images.githubusercontent.com/71666730/94907786-aa006b80-046e-11eb-986b-0765fc4dcf84.png)

**Comment by ghostlydilemma** [comment]
Exactly!
Maybe make it toggable if it should show the word itself but I imagined smth just like that :D

**Comment by A-Trash-Coder** [comment]
https://github.com/A-Trash-Coder/WordFilter here is a Plugin that blocks words, was not made specifically for this Plugin Request, so this can remain open if this doesn't suffice.

**Comment by Kanin** [comment]
@ghostlydilemma does this work for you?

**Comment by ghostlydilemma** [comment]
I will take a look at it in the next couple of days, dont have too much time atm

**Comment by ghostlydilemma** [comment]
Not quite what I wanted but this is way better anyways! Thanks a ton :3
(issue can be closed)

**Comment by A-Trash-Coder** [comment]
<3
