### ISSUE TITLE
Bring back image urls

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#123]
**Describe the plugin**
So Discord recently made it to where images posted via URL with no extra text hide the URL. This is a security issue and just downright stupid. I looked through the css and don't see a way to bring it back that way but tbh I probably looked over it, if not a plugin would be nice.

**Expected behavior**
Show me dem image urls
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
done, i added it to discord-tweaks

https://github.com/NurMarvin/discord-tweaks/pull/8
