### ISSUE TITLE
Install from link

### ISSUE THREAD

**Issue by Noxillio** [powercord-community/suggestions#124]
**Describe the plugin**
This plugin allows the user to right-click a GitHub link for a Powercord plugin and get a context menu option to install said plugin. It was [previously available](https://github.com/cloudrac3r/powercord-install-from-link) (created by Cadence) but no longer functions.

**Expected behavior**
It's all above. Simple.

----

 - [•] I checked if this request wasn't already proposed
 - [•] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by LandenStephenss** [comment]
https://github.com/LandenStephenss/PowercordPluginDownloader
