### ISSUE TITLE
No Quick Start Menu

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#125]
### Description
Gets rid of the games listed in the "super secret menu" thing. If possible of course. 

### More info
Basically gets rid of the area between _Discord_ and _Check for Updates..._
![img](https://anime.is-terrible.com/flo4NG.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by ghost** [comment]
Discord might have removed it themselbes by now. I'm not seeing those options anymore. If a few others don't see it aswell this issue can be closed.

**Comment by chasecrampton** [comment]
I don't see it so it probably was removed.
