### ISSUE TITLE
Delete last message sent

### ISSUE THREAD

**Issue by darkhappy** [powercord-community/suggestions#127]
**Describe the plugin**
Command that deletes the last message sent by the user

**Expected behavior**
`[p]delete` deletes the last message sent by the user
~~(optionally) `[p]delete number` purges an amount of messages sent by the user, although not sure if this complies with guidelines~~

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by KyzaGitHub** [comment]
Generally, for something to not be considered selfbotting there must be at least one user action per automatic action. I don't see why just `[p]delete` wouldn't be fine, but multiple messages are definitely not fine.

**Comment by darkhappy** [comment]
Makes sense, `[p]delete` would still be nice to have, since it's a more convenient way to delete a message without lifting your hand from your keyboard.

**Comment by Bowser65** [comment]
UpArrow Ctrl+A Delete Enter Enter

currently not working due to what we believe to be a bug (need to press tab two times between the two enter presses), but this will in normal times do the trick

**Comment by Bowser65** [comment]
Closing as this feature is achievable through vanilla Discord with only keyboard interaction required
