### ISSUE TITLE
Soundcloud Modal (Similair to Spotify Modal)

### ISSUE THREAD

**Issue by Controlfreak707** [powercord-community/suggestions#128]
**Describe the plugin**
Basically the same as the Spotify Modal, but with Soundcloud. Maybe it could even set a rich presence status similar to Spotify.

**Expected behavior**
I expect that the modal would appear once I begin playing music on the Soundcloud website with information about the song, artist, album and possibly playlist as well as controls (if possible). Instead of the theme being green it would be orange.

_Please note that I have no idea how difficult any of this would be or if it's even possible so if you're only able to make a plugin with some of the above features then I will understand._

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by mrrobboss** [comment]
https://github.com/powercord-org/powercord/issues/197 idk if the api is open at this point but its been requested before

**Comment by Bowser65** [comment]
This has been previously suggested and classified as non feasible due to the lack of API on SoundCloud's end. Their API is still closed to this day and scraping/using other's API keys would interfere with SoundCloud's ToS and therefore our guidelines.

**Comment by ADoesGit** [comment]
also soundcloud cant control the player themselves, ahthough it could be done through a custom soundcloud client ~~*caugh* mine *caugh*~~

**Comment by SKBotNL** [comment]
Im not 100% sure but it actually looks like SoundCloud's API/SDK is open
