### ISSUE TITLE
Clickable send button

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#13]
**Describe the plugin**
A button to send the content in the chat box.

**Expected behavior**
*coughs* some people *coughs* are lazy and don't want to move their hand off of their mouse when inputting text via voice to text or something similar and would like a way to send messages in the client.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by intrnl** [comment]
Working on it :^)

**Comment by intrnl** [comment]
[intrnl/powercord-send-button](https://github.com/intrnl/powercord-send-button)
Adds a clickable send button in chat
