### ISSUE TITLE
Quicker CSS

### ISSUE THREAD

**Issue by Sidemen19** [powercord-community/suggestions#133]
**Describe the plugin**
A plugin to add the "Quick CSS" button to the main Powercord settings bar/menu, so it's actually quick instead of having to go through Themes.

**Expected behavior**
Expected is a plain simple button to be added to mentioned menu which then forwards the user to the CSS editor, preferably under Themes, but it doesn't really matter.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This would more be of a request for Powercord Core. Also, there's an experimental feature that lets you access the QuickCSS popout simply with a right click (note that it's an **experimental** feature and no support, suggestions, bug reports, or anything is done for those features)
![image](https://user-images.githubusercontent.com/9999055/89337336-104d5580-d69b-11ea-8593-afe001bbfdcd.png)
