### ISSUE TITLE
Voice Chat Move All

### ISSUE THREAD

**Issue by QzyxTpik** [powercord-community/suggestions#134]
### Description
I would like to see a plugin where you can move all the users connected to a specific voice channel to another.

### More info
Make it show when you right click the channel you are connected to and have a modal with all the channels and when you press a voice channel name all the users connected to your voice channel (you too) will get moved into the clicked voice channel.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BloodDragooner** [comment]
Very useful. +1

**Comment by hellbound1337** [comment]
claimed

**Comment by hellbound1337** [comment]
i'll be going on holiday so sadly i can't complete this. you can feel free to un-assign me

**Comment by hellbound1337** [comment]
flight got cancelled 😐  you can re-assign me.

**Comment by hellbound1337** [comment]
@QzyxTpik Done. https://github.com/hellbound1337/vc-move-all

**Comment by QzyxTpik** [comment]
> @QzyxTpik Done. https://github.com/hellbound1337/vc-move-all

Thanks you so much ❤🖤🌙

**Comment by SomeAspy** [comment]
Hellbound has one. not sure how you want to handle it though. https://github.com/slow/vc-move-all

**Comment by TheShadowGamer** [comment]
This has existed forever. It’s in the plugin-links channel. https://github.com/Twizzer/move-all-vc

**Comment by SomeAspy** [comment]
so wouldnt that mark this as closed/duplicate

**Comment by TheShadowGamer** [comment]
It should just be closed as the plugin came out after this request was opened. I’m guessing the person who made this just didn’t post the link here, or didn’t realize this existed. @Kanin @cyyynthia Could you close this and mark it as completed please?
