### ISSUE TITLE
Ability to see if you have the Embed Links permission in a guild channel

### ISSUE THREAD

**Issue by joshuapatel** [powercord-community/suggestions#135]
### Description
The plugin would allow the user to know if they have the Embed Links permission in a guild channel (not a DM channel since they always have that permission regardless). This would be for people who use custom media uploaders for images and videos to know if they are able to use their media uploader in the channel and that the image or video will display, or if they should upload directly through Discord if applicable.

### More info
I propose to show if the user has the permissions to use Embed Links to the right in the space for the channel topic in a red font by default (this should be customizable for users who use themes). It should also be customizable whether to display only if the user has the Embed Links permission, if the user doesn't have the permission, or to display it if they do or don't have the permission.

The user should also be able to select which text to display if they have the permission (should be "EMBED LINKS" by default) or if they do not have the permission (should be "NO EMBED LINKS" by default). The text should clearly be distinguishable from the rest of the channel topic and should not overlap the text in the channel topic.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by A-Trash-Coder** [comment]
https://github.com/A-Trash-Coder/EmbedLinksUtility

**Comment by joshuapatel** [comment]
Awesome. Thank you so much!
