### ISSUE TITLE
Temporary CSS Plugin + Theme Settings Menu

### ISSUE THREAD

**Issue by Controlfreak707** [powercord-community/suggestions#137]
**Describe the plugin**
A temporary plugin to toggle CSS plugins and manage theme settings until the official theme manager is released.

**Expected behaviour**
A menu that allows you to select a certain installed theme, toggle CSS plugins, and manage theme settings.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
You mean something like [theme-toggler](https://github.com/redstonekasi/theme-toggler)? There's also [themer](https://github.com/LandenStephenss/Themer) which is unmaintained but I still use it with no issues, I haven't used theme-toggler personally but I assume it's something similar and still maintained.

**Comment by Controlfreak707** [comment]
[theme-toggler-](https://github.com/redstonekasi/theme-toggler) only toggles themes as a whole, that's it. I haven't seen themer before, I'll go check it out.

**Comment by CodingKanin** [comment]
What? You want to toggle individual files in the theme? You should do this with imports in your main file or something, I'm not sure if that's possible with how themes are loaded though I could very well be wrong, if it is though you should request it as a feature on the already existing plugin

**Comment by Bowser65** [comment]
This is the roadmap of Powercord Core as part of the css modules specification in theme manifests. There's no ETA or tracking for this issue though, and it'll depend on the theme developer to adapt their theme to enable this functionality. You can learn more about what's planned for themes in the [WIP powercord_manifest.json documentation](https://github.com/powercord-org/powercord-backend/blob/my-awesome-branch/docs/1-themes/manifest.md)
