### ISSUE TITLE
Auto collapsing guild folders

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#14]
**Describe the plugin**
If you're not looking at a server in a folder it collapses

**Expected behavior**
When you click out of a server in a folder that folder collapses

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by intrnl** [comment]
Working on this one too

**Comment by intrnl** [comment]
[intrnl/powercord-auto-collapse-folders](https://github.com/intrnl/powercord-auto-collapse-folders)
Collapse folder when moving away from a server in that folder
