### ISSUE TITLE
See More Channels

### ISSUE THREAD

**Issue by notlouis** [powercord-community/suggestions#141]
**Describe the plugin**
It would behave similarly to the Zoom Out feature on discord, but will only affect the channel list, allowing you to see more channels at a time.

**Expected behavior**
A way to zoom out just the channel list, this is because when i take screenshots with my entire discord zoomed out, they can seem low quality to people without it zoomed out. So it could be that when you zoom out whilst hovering over the channel list it'll zoom that out, or maybe something to manually set the zoom inside the plugin.

----

 - [YES ] I checked if this request wasn't already proposed
 - [ YES] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by botatooo** [comment]
i think this is the thing you're talking about https://github.com/HooferDevelops/sidebar-zoom

**Comment by Shocks50541** [comment]
> i think this is the thing you're talking about https://github.com/HooferDevelops/sidebar-zoom

Thats exactly what I was looking for, thank you so much!

**Comment by MulverineX** [comment]
@notlouis you can close the issue now lol
