### ISSUE TITLE
Role ID Copy

### ISSUE THREAD

**Issue by thewilloftheshadow** [powercord-community/suggestions#142]
**Describe the plugin**
Clicking on a role in the user dropdown menu causes the ID of the role is copied to your clipboard. This would allow for another easy way to copy role IDs, since I frequently visit this dropdown for users in a VC, etc

**Expected behavior**
When clicking on a role in the user dropdown menu, the ID of the role is copied to your clipboard
this would allow for another easy way to copy role IDs, since I frequently visit this dropdown for users in a VC, etc

![image](https://user-images.githubusercontent.com/35580099/89720713-e5187e00-d99a-11ea-8c56-48a6f11b0359.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Juby210** [comment]
is this really needed? you can just

![image](https://user-images.githubusercontent.com/31005896/89720777-3eea6980-d9d6-11ea-99a0-be9a055e3eb9.png)

**Comment by thewilloftheshadow** [comment]
Since when is that a thing?!? I've been wasting so much time doing that the hard way 😂
I guess that makes this idea pretty much a waste of time then. Thanks for showing me that
