### ISSUE TITLE
Collapse all categories

### ISSUE THREAD

**Issue by Ser-Ames** [powercord-community/suggestions#145]
### Description
Allow the user to collapse all categories in a server by opening the context menu on the guild icon on the sidebar or on the empty space in the channel list

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
Pointing out what has been said in Powercord's server to clarify some possible confusion: The feature somewhat exists through keyboard shortcuts (`Ctrl+Shift+A`), but the requested feature is a clickable UI element

**Comment by Sidemen19** [comment]
Done: https://github.com/Sidemen19/collapse-all-cats
