### ISSUE TITLE
Quick mute channels

### ISSUE THREAD

**Issue by John4167** [powercord-community/suggestions#147]
### Description
A mute button next to a channel you hover your mouse over, to quickly perm mute the channel, and unmute it too. When you hover over a channel with your mouse, a mute button should appear, as shown here: https://i.imgur.com/NZrFdjp.png Once the mute button is pressed, it should permanently mute the channel. Once the mute button is pressed on a muted channel, it should unmute the channel.

### More info
I used a BD plugin for this, but it has since been broken and I'd love to see a powercord plugin for this.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by botatooo** [comment]
i am pretty sure this is a default feature ![mute](https://support.discord.com/attachments/token/FcQydVgam148Ryl7fxC5HsZXM/?name=4ee8ba755f.png)

**Comment by John4167** [comment]
> i am pretty sure this is a default feature
> ![mute](https://camo.githubusercontent.com/f8a1db0bd230f53ed6b96c62de34bd248db70262/68747470733a2f2f737570706f72742e646973636f72642e636f6d2f6174746163686d656e74732f746f6b656e2f46635179645667616d31343852796c376678433548735a584d2f3f6e616d653d346565386261373535662e706e67)

No, I mean when you hover over the channel, a mute button will appear on it to mute it faster, as shown here. [https://i.imgur.com/NZrFdjp.png](url)

**Comment by A-Trash-Coder** [comment]
WIP

**Comment by A-Trash-Coder** [comment]
Done: https://github.com/A-Trash-Coder/Quick-Channel-Mute
