### ISSUE TITLE
Read all button.

### ISSUE THREAD

**Issue by John4167** [powercord-community/suggestions#148]
**Describe the plugin**
A clear and concise description of what the plugin would do.
A small button at the top of your server list to mark everything as read, including pings and DMs.
**Expected behavior**
A clear and concise description of what you expect to happen.
Once the button is clicked, it will mark all DMs, pings, and new messages in all servers as read, and make them disappear. 
You can add other context, mockups or anything else here.
Pretty sure this was also originally in betterdiscord. It was made by devilbro.
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by BenSegal855** [comment]
That is a vanilla feature. shift + esc

**Comment by John4167** [comment]
> That is a vanilla feature. shift + esc

wait what.... had no idea lol. no wonder nobody has made this. silly me

**Comment by Sialss** [comment]
> That is a vanilla feature. shift + esc
I think he means a button to do it kinda like in the betterdiscord plugin
