### ISSUE TITLE
Server information

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#15]
**Describe the plugin**
Somewhere in the server it would display information about said server. Such as when it was created, how many channels, and the guilds features. 

**Expected behavior**
N/A

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by cloudrac3r** [comment]
Claimed? owo

**Comment by ghostlydilemma** [comment]
Maybe also show people that share this server with you?

**Comment by cloudrac3r** [comment]
https://github.com/cloudrac3r/powercord-server-info
