### ISSUE TITLE
Hide Voice Channels

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#150]
### Description
A way to hide voice channels the same as text channels.

### More info
For text channels you can mute them and then hide muted channels, but that is not the case for voice channels. Id love a way to hide them completely, the same as text ones. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
Wouldn't this be a duplicate of #19?

**Comment by botatooo** [comment]
> Wouldn't this be a duplicate of #19?

y e s   i t   i n d e e d   i s

**Comment by DracoClaw** [comment]
oh i guess it is. didnt see that as its fairly old, also it does not mention voice channels.

**Comment by Bowser65** [comment]
Yeah, might be worth commenting on this issue rather than opening a new one
