### ISSUE TITLE
CopyRawMessageOption

### ISSUE THREAD

**Issue by VyrekXD** [powercord-community/suggestions#151]
### Description
Is a plugin that adds a plugin just like this but copy the entire message whith all the things

https://cdn.discordapp.com/attachments/741078107955658877/744345723436269618/Screenshot_1.png

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Already exists:  https://github.com/Juby210/view-raw

**Comment by MulverineX** [comment]
Its kinda annoying because it requires you open the message in a prompt

**Comment by BenSegal855** [comment]
> Its kinda annoying because it requires you open the message in a prompt then copy it, then exit out.
Would still probably be better as a pr than a fresh plugin
