### ISSUE TITLE
Messages Utilities Like BD

### ISSUE THREAD

**Issue by VyrekXD** [powercord-community/suggestions#154]
### Description
A plugin that exists in bd that can be used to quickly delete, edit, pin messages, etc.

### More info
Using keyboard keys that you can configure in the configuration tab like:
Delete Message:
Ctrl + D + (Click or Double Click)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
This has now been implemented by Discord natively; Press shift while hovering a message and you get tons of shortcuts.
