### ISSUE TITLE
Listening status for TIDAL.

### ISSUE THREAD

**Issue by smellyfinger** [powercord-community/suggestions#161]
### Description
Get a listening status with TIDAL.

### More info
With this plugin hopefully there would be a way to have a "Listening to" status with tidal support. For example, I was thinking of something around the lines of "Listening to (the name of the song) on TIDAL" Although I'm not sure if this would look the best. I'd really love similar to this, as there is already a Discord RPC of it. It works by using the Discord Rich Presence feature, and it grab the name of the name of window from TIDAL it self although it doesn't look the greatest and it doesn't say the name of the song right away and also you have to run a separate exe every time you boot up your pc (I've tried to make it run on start up and it doesn't work for me). I think having the option of having the status of "Listening to" would look nicer and be convenient being it loads up on discord instead of finding and running the exe yourself. 

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by CodingKanin** [comment]
Are you aware that we can't make this public? Best case scenario would be other people with the plugin being able to see it, but not anybody else.. if thats possible lol. Opinions @Bowser65 ?

**Comment by Bowser65** [comment]
Depends, you can do a clever implementation and use a classic rich presence to set it, and then just alter how it looks like for the plugin users (based on the application id).

However, as far as I know TIDAL doesn't provide a realtime websocket we can listen to to get realtime updates, so the only way of getting the currently playing song is via scraping. Maybe on Linux if TIDAL has a proper desktop app you might be able to get some data via dbus but that's linux only anyway. I don't know if scraping can be considered a viable option.

**Comment by smellyfinger** [comment]
I don't know how this works but or if it's possible with a plugin , but for example (which I know is bad to use) a self bot can easily switch your status to listening to. Or even a browser extension. If only you can grab the window name [(](https://i.imgur.com/EbfeT6c.png) ) and make your status "listening to" and then the name of the window and change accordingly Maybe that can work?

**Comment by Bowser65** [comment]
We will not accept any plugin that sets a Listening To status. At this time Spotify is the only way of having this status as a user, using it for something else is a clear indication for Discord you are selfbotting.

As of scraping, as I said, scraping is the only way to do it but I'm unsure if there are any sane ways of scraping it and get accurate enough results. I don't even know if we'll consider such a viable approach.

**Comment by Bowser65** [comment]
With the upcoming changes to Powercord plugin access level, scraping is no longer a viable method. The use of external RPC tools will be required.

**Comment by MulverineX** [comment]
@smellyfinger ^^
