### ISSUE TITLE
FastReaction

### ISSUE THREAD

**Issue by VyrekXD** [powercord-community/suggestions#162]
### Description
A plugin that make that you can faster react a message using the last emoji, etc.

### More info
A plugin that like in the image make that you can fast react a message with the last emoji used or with the configurable emoji
https://cdn.discordapp.com/attachments/741078107955658877/747546973602840638/unknown.png

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Built into discord: send `+:emojiName:` to quickly react with the last message. Also you can right click a message and bring up your four most used reactions to quickly react.
