### ISSUE TITLE
Multiple statuses

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#163]
### Description
Display every status a user has enabled, custom, playing, and spotify.

### More info
N/A

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
done, https://github.com/Juby210/show-all-activities
