### ISSUE TITLE
Custom DM list

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#164]
### Description
Have a white list of users who's DMs show up as normal, everyone else gets added to the badge that shows on the home icon for friend requests.

### More info
Would be nice to be able to customize the bage, e.g having an option to remove the badge itself and change the color of the home button itself, with the number of notifs in the middle. Should be able to white list people in settings and by right clicking them.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by hellbound1337** [comment]
claimed

**Comment by hellbound1337** [comment]
i'll be going on holiday so sadly i can't complete this. you can feel free to un-assign me
