### ISSUE TITLE
Read All Notifications Button

### ISSUE THREAD

**Issue by Curvuu** [powercord-community/suggestions#169]
### Description
Read All Notifications Button

### More info
Adds a little button at the top of your serverlist that enables you to clear all mentions and messagesnotifications at once.
https://prnt.sc/u8lzdt
More info at : https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReadAllNotificationsButton

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Juby210** [comment]
![image](https://user-images.githubusercontent.com/31005896/91670347-dd24a780-eb1c-11ea-88b0-ce1321cb72bd.png)

not needed, discord has this built-in

**Comment by Bowser65** [comment]
As Juby mentioned, this is a native Discord feature. Click the Inbox icon, go to Unreads and click the button shown above.
