### ISSUE TITLE
Owner / Admin Tag

### ISSUE THREAD

**Issue by ohlookitscurvu** [powercord-community/suggestions#170]
### Description
Owner & Admin Tag

### More info
Adds a Tag like Bottags to the Serverowner and users that have permissions of "ADMIN".
Like this: https://prnt.sc/u8m26q
More info at : https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/OwnerTag

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
https://github.com/Puyodead1/powercord-ownertag
