### ISSUE TITLE
Multiple Discord accounts in one client

### ISSUE THREAD

**Issue by Ashley1227** [powercord-community/suggestions#174]
### Description
Like, on the bottom bit, where your little icon and buttons are, rearrange that so when you click your profile picture it gives you an option to change accounts on the fly, could add a new button for statuses

### More info
Could be useful for: people with school accounts/work accounts, people with private/public accounts, people with DID, people who have horny/main accounts, etc

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by hellbound1337** [comment]
https://github.com/powercord-community/multitask
