### ISSUE TITLE
Client Sync

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#175]
### Description
A plugin you can use to sync two Powercord Clients

### More info
It would allow for plugins, themes, quick css, and maybe even settings to be the same on multiple Powercord clients. I use a PC and Laptop, both with Powercord and I'd love for them to be the same. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
This is on the roadmap for Powercord Core
