### ISSUE TITLE
Auto Join Back

### ISSUE THREAD

**Issue by NotAtomicBomb** [powercord-community/suggestions#177]
### Description
Basically this plugin reconnects you to the VC you were just in after being disconnected from it or moved

### More info
For those annoying friends that like to disconnect you or move you.
Maybe add a keybind or button to enable/disable it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
This would be against guidelines 1 and 3, so I won't accept this.
