### ISSUE TITLE
Better Folders Plugin

### ISSUE THREAD

**Issue by Snapperito** [powercord-community/suggestions#179]
### Description
A plugin similar to devilbros "serverfolders" plugin 

### More info

When a folder is selected, it pops out to the right (in a column) rather than downwards 
also, the ability to change the folder icon to a .png or .jpeg

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by TrueXPixels** [comment]
I'll give this a shot

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
https://github.com/Juby210/better-folders

**Comment by SomeAspy** [comment]
@cyyynthia I think you should be able to close this now
