### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#18]
**Describe the plugin**
Lets you when you're a lazy person google things from Discord

**Expected behavior**
Add a search command that does make a search on ddg and returns the 3 first results as a clyde message. Maybe consider implementing others search engines (Google might be tricky but should be possible)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by juby210-PL** [comment]
claimed

**Comment by juby210-PL** [comment]
done

https://github.com/juby210-PL/quick-search
