### ISSUE TITLE
Owner Tag Plugin

### ISSUE THREAD

**Issue by StarRush22** [powercord-community/suggestions#181]
### Description
A plugin that displays who is owner of the server and who has Administrator permissions
### Extra Info
there is a better discord plugin that devil bro made but it does not work anymore. Here is the link https://betterdiscordlibrary.com/plugins/Owner%20Tag
Good luck!

- I checked to make sure no one else posted this idea

**Comment by Kanin** [comment]
Duplicate of #170 also doesn't follow the format provided to you, please use the template when clicking new issue.

**Comment by StarRush22** [comment]
w o o p s.
