### ISSUE TITLE
RemindMe plugin

### ISSUE THREAD

**Issue by ezist** [powercord-community/suggestions#182]
### Description
Given a duration/datetime and a message, remind the user of the message when the duration has passed.

### More info
ex: .remindme 12h "check if your plugin idea was claimed"

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DanKGooGLy** [comment]
IIRC Snapperito has already started this

**Comment by DanKGooGLy** [comment]
https://github.com/Snapperito/Moar-Info here, it's really unfinished so I'm not sure if it would help at all

**Comment by Controlfreak707** [comment]
> https://github.com/Snapperito/Moar-Info here, it's really unfinished so I'm not sure if it would help at all

Uh... I think you've got the wrong plugin. This request is for a plugin that reminds the user something at a specified time, the link you gave seems to give "Moar" info about a user...

**Comment by DanKGooGLy** [comment]
Try looking at the description and the files of the plugin

**Comment by Controlfreak707** [comment]
...I did. the description of the plugin is "Lierally just more info ." There is a `remindme` command mentioned in the `index.js` file, but this request has not been claimed and no-one else has commented on it. I'll go ask Snapperito just in case...

**Comment by DanKGooGLy** [comment]
Alrighty

**Comment by Snapperito** [comment]
yes i had it partially working locally, but ended up dropping it because of time reasons. feel free to work on it liam :D

**Comment by Controlfreak707** [comment]
And here it is: https://github.com/Controlfreak707/remind-me
There's probably some bugs here and there... if you find any, send me the error it produces and I'll sort it out.
