### ISSUE TITLE
@everyone Ping Hider

### ISSUE THREAD

**Issue by arcbarkzap** [powercord-community/suggestions#183]
### Description
Hides going notification icons in servers where you marked the "suppress @everyone and @here" box under notifications settings for that server
### More info

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by theGordHoard** [comment]
From testing, @ everyone/here mentions do not add to the total notification count on a guild when this option is enabled. As such, this is already in the vanilla client.
