### ISSUE TITLE
Show Blocked Messages

### ISSUE THREAD

**Issue by Magi1053** [powercord-community/suggestions#184]
### Description
I have run into multiple occasions where I want to block somebody but I still want to see their messages. I'm requesting this plugin to still show blocked messages in dms, groups and servers, possibly with a custom text color to distinguish it as well.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
I think this request can be merged with #36. Feel free to add a comment there, so the plugin dev who'll look at it will know that's a feature people want.
