### ISSUE TITLE
Free emojis like better discord plugin

### ISSUE THREAD

**Issue by VyrekXD** [powercord-community/suggestions#186]
### Description
Its a plugin that make url the emojis that you need nitro

### More info
Here is the orginal idea: https://github.com/An00nymushun/DiscordFreeEmojis
Its only make url the emojis that you can use

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
After some internal decision we've decided to not approve plugins being workarounds for what can be described as "Free Nitro". Premium perks are premium, getting them for free is kind of cheating. And cheating' bad

**Comment by VyrekXD** [comment]
> After some internal decision we've decided to not approve plugins being workarounds for what can be described as "Free Nitro". Premium perks are premium, getting them for free is kind of cheating. And cheating' bad

Oh okay thank u

**Comment by IveMalfunctioned** [comment]
Just use the BetterDiscord plugin with [bdCompat](https://github.com/Juby210/bdCompat)
