### ISSUE TITLE
Reverse Image plugin?

### ISSUE THREAD

**Issue by shai16** [powercord-community/suggestions#187]
### Description
A plugin where you right click on image then Image reverse on multiple websites similiar to DevilBro.
Apparently his one stopped working on Powercord for some reason.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
There is a long outdated, unmaintained (and possibly broken plugin) here: https://github.com/cloudrac3r/powercord-reverse-image-search

It might be a good starting point to someone willing to make/maintain it

**Comment by TrueXPixels** [comment]
I'm not sure if I implemented this correctly, but I needed it as well, so I made this: https://github.com/TrueXPixels/powercord-reverse-image-search

**Comment by shai16** [comment]
Thanks a lot.

Is it possible you add more reverse image websites?  The outdated one had more and they were really useful. I could suggest some or try to list them all but the best one was Yandex, it helped me when I was talking to a catfish :[ Without yandex i would've been catfished LOL.

yandex.com

I would highly recommend yandex.com.

If you want the image reverses websites of the outdated plugin, theyre:

yandex.com
saucenao.com
trace.moe
graph.baidu.com
pic.sogou.com
bing.com
karmadecay.com
iqdb.org


These were all the websites in the outdated plugin, I hope I didn't miss any.

**But the best one was honestly Yandex for sure**

Also you could add "Open all" or "Image Reverse All" so it opens multiple tabs instead of clicking one by one, that was also a good feature.

**Comment by TrueXPixels** [comment]
Added! Unfortunately, I wasn't able to figure out how to get `graph.baidu.com` & `pic.sogou.com` to work. If someone knows how, feel free to add it to the providers.json file.

To enable, simply toggle the options in the settings menu.
![](https://i.plexidev.org/fXQj2oN)
