### ISSUE TITLE
Amazon Music Plugin

### ISSUE THREAD

**Issue by LolTDMMMOs** [powercord-community/suggestions#189]
Ok, so I personally use Amazon Music and was hoping someone would be able to make an Amazon Music plugin. It is ok if this is not possible. Thanks
----

 - [x ] I checked if this request wasn't already proposed
 - [ ]x I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
This plugin does not follow the provided template for requesting plugins.

I doubt Amazon Music provides a realtime API for getting player updates like Spotify does, so it's not feasible (unless I'm wrong and they do provide one).
