### ISSUE TITLE
Quick-delete messages

### ISSUE THREAD

**Issue by TheFloppyBanana** [powercord-community/suggestions#193]
### Description
A simple plugin that allows users to quickly delete messages just by clicking at them. Useful for deleting tons of messages instead of right clicking for each messages.

### More info
A configurable hotkey can be useful to avoid accidental deletion of messages.
The hotkey must be held pressed down while deleting the messages.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Hold shift and a quick delete button pops up. This is native to discord.

**Comment by KyzaGitHub** [comment]
Holding shift exposes the delete button on messages. This accomplishes nearly the same thing. If this still leaves something to desire, [this](https://github.com/KyzaGitHub/show-all-message-buttons) plugin exists.
