### ISSUE TITLE
Open Spotify links in Spotify

### ISSUE THREAD

**Issue by ezist** [powercord-community/suggestions#196]
### Description
A plugin that would open spotify links such as `https://open.spotify.com/track/7GhIk7Il098yCjg4BQjzvb` in the Spotify app.

### More info
Possible with `window.open("Spotify URI")`.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ezist** [comment]
A BetterDiscord version exists [here](https://github.com/Strencher/BetterDiscordStuff/blob/master/OpenSpotifylinksInSpotify/OpenSpotifylinksInSpotify.plugin.js) if you need something to base it off of.

**Comment by TrueXPixels** [comment]
Here you go! https://github.com/TrueXPixels/powercord-open-in-spotify

![](https://i.plexidev.org/IYPLIGc.gif)
