### ISSUE TITLE
Element Selector

### ISSUE THREAD

**Issue by cyleja1234** [powercord-community/suggestions#197]
### Description
Highlights and copies the element's selector

### More info
while the pops out quick CSS, there would be a button that you press and now, while you hover over an element it will outline the element. After clicking on an element it will copy the element's selector to the clipboard. if you re click the button it will turn off the css selector. There is a chrome extension that does the same thing [here](https://chrome.google.com/webstore/detail/crx-extractordownloader/ajkhmmldknmfjnmeedkbkkojgobmljda/related?hl=en-US). 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ADoesGit** [comment]
1. devtools exists and lets you do exactly this 
2. That extension does not do this, its an extension for downloading Chrome extensions.
3. QuickCSS pop out is broken

**Comment by botatooo** [comment]
Adding to what aa said, 
4.  An element can have multiple selectors, and parents or children with the same width / height making it almost impossible to select those.
