### ISSUE TITLE
Typing speed indicator

### ISSUE THREAD

**Issue by tobimori** [powercord-community/suggestions#198]
### Description
A typing speed indicator for Discords Slate textarea

### More info
5 characters per second are usually counted as 1 word per second (WPM)
Could be put next to a slowdown indicator

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by voidbehemoth** [comment]
I decided to start working on this today... Will update this thread with progress.

**Comment by romdotdog** [comment]
rip

**Comment by romdotdog** [comment]
Done. https://github.com/romdotdog/pc-wpm

**Comment by Bowser65** [comment]
Plugins **must *__absolutely__* not** be prefixed with pc-.

**Comment by romdotdog** [comment]
sorry for that stupid mistake. edited.
