### ISSUE TITLE
Plugin for Discord Call Remix

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#2]
*[Original issue](https://github.com/powercord-org/powercord/issues/163)*

### Description
There's a 0.1% chance of when someone calls you a remixed version of the default song is used. With this plugin enabled, whenever you get a call, it should play the aforementioned song instead of the default.

### More info
Asset url: https://canary.discord.com/assets/b9411af07f154a6fef543e7e442e4da9.mp3

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by CodingKanin** [comment]
Possibly with the ability to set a custom call sound?

**Comment by Elliite** [comment]
where is the link to download
?

**Comment by Juby210** [comment]
`up for grabs` means no one is working on this plugin and this plugin isn't finished. You can't download non-existing things.

**Comment by botiapa** [comment]
I think meant the download link to the aforementioned song, didn't he?

**Comment by botatooo** [comment]
> I think meant the download link to the aforementioned song, didn't he?
if so, its https://canary.discord.com/assets/b9411af07f154a6fef543e7e442e4da9.mp3

**Comment by ADoesGit** [comment]
ill take this, i have a partially working version using code from betterfriends

**Comment by ADoesGit** [comment]
Done. https://github.com/ADoesGit/ringtoner
