### ISSUE TITLE
Timed custom statuses

### ISSUE THREAD

**Issue by theGordHoard** [powercord-community/suggestions#20]
**Describe the plugin**
A plugin that allows you to set times that a custom status would automatically be set on your account. I understand that this would only work while powercord is running, but I still think it would be a great feature.

**Expected behavior**
Changes your custom status on a schedule.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by theGordHoard** [comment]
I've gotten started on this, it won't be super fancy but it'll work

**Comment by Bowser65** [comment]
Any update on this? There don't seem to be much going around here and Kanin's request #83 would cover this request (and actually do it better than the proposed feature set here)

**Comment by Bowser65** [comment]
Closing this due to the lack of response and in favor of #83
