### ISSUE TITLE
Better Emojis In Channel Names

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#200]
### Description
Currently the emojis used in channel names look different than the ones used in chat. Have them display the same. Also flags do not show up at all, and instead show as the country code.

### More info
![image](https://user-images.githubusercontent.com/34274162/94083166-3d9cc100-fe0b-11ea-889f-3ba4d75564bd.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Mara-Li** [comment]
Hello !
[A plugin already exist and work for the moment in Betterdiscord](https://github.com/micelle/BetterDiscordPlugins/blob/master/plugins/Twemoji.plugin.js), but doesn't with BD adaptator. 
I try to understand why but, I don't know JS, so...

I check some CSS with the plugin, on a channel name for exemple : 
![image](https://user-images.githubusercontent.com/30244939/107929632-3755df80-6f7a-11eb-960a-971591eaf197.png)

The plugin add directly a "function" on img.emoji, and use Twemoji. Also, it uses the Zlibrary to work.

If anyone can help us... I really want use Powercord with good emoji :(

**Comment by Vendicated** [comment]
Done! https://github.com/Vendicated/PowercordTwemojiEverywhere

**Comment by Mara-Li** [comment]
Thank you!
