### ISSUE TITLE
User Status options on Tray utility icon right click

### ISSUE THREAD

**Issue by WinstonSepruko** [powercord-community/suggestions#207]
### Description
Adds options to the right click context menu for the Discord tray icon.

### More info
List the options as
Online, Idle, DND, Invisible.
A custom status would most likely be too difficult as well as emoji picking being not even worth bothering with I mean just open the damn client.
This is mostly just for quickly toggling your status to stop notifications rolling in by setting yourself to DND etc. without having to tab to the window or open the client window.
![image](https://user-images.githubusercontent.com/33651534/94408367-09812180-01b8-11eb-8ded-57ac382a3291.png)
This menu, obviously.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
With the upcoming changes to Powercord plugins access levels I can't define the technical constrains of such plugins. If possible, It'll most likely require additional APIs from Powercord. Until we can have a clear idea on what's possible and what's not I'll leave the suggestion pending.

**Comment by jaydns** [comment]
This can be closed, https://github.com/jaydensar/tray-status-picker
