### ISSUE TITLE
PowerReplies - Replies using the custom embed links.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [powercord-community/suggestions#208]
### Description
Add a quick button to reply to others messages and provide a quote of the original message via a linked custom embed.

### More info
A long time ago there was a plugin for BetterDiscord called "Citador". It used embeds in a neat way to quote others while showing the PFP of the user, when the original message was posted, as well as who posted the original message. The big problem with Citador was it wasn't using linked embeds, but bot generated ones. Therefore against TOS which is _bad._

However just recently I noticed the custom embed links from Kyza/Liam the Protogen on the Powercord discord server and thought: "Hey, now that we have a way to generate embeds safely without it really being against TOS, why not try and make a safer version of Citador?". Basically just call it either PowerReplies or SafeCitador.
To get into further detail:
- The plugin I was speaking of from the Powercord server was [Safe Embed Generator](https://github.com/KyzaGitHub/safe-embed-generator) 
- The button to reply to a message should be in that small little bar to the top right of messages. I don't know the exact name of it but the one where the add reaction button sits.
- The embed should be formatted in a way similar to [this image.](https://user-images.githubusercontent.com/45246118/94593523-4a7c4300-0257-11eb-8a1e-ccc9073bbe2c.png)

- Color of the embed should be the color of the replied-to user's role color.
- The link embed should be sent in a separate message before any appending one as to be above the repliers message.
- Any attached image to the original message should be linked to the side of the embed.
- The author URL of the embed should be a message link so others can jump to the original message.
- Allow the plugin user to select multiple messages to reply to, either making each message a separate linked embed or combine them into a single embed.
- Allow the selected replies to be sent to other channels, servers, and DM's.

Now, while hiding the link of the embed via current methods is possible and would be recommended for the plugin to be as clean as it can be, I understand if it's not allowed due to it being hard to tell between whether it was generated via a bot or a linked embed.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
@Mr-Foxtrot heyo so AAGaming and I have been working on a plugin that might fit this bill, here's a link to show what it does (on the powercord discord)
https://discord.com/channels/538759280057122817/755012949180940391/761793689185681418

**Comment by MulverineX** [comment]
Done! https://github.com/ADoesGit/rich-quotes

![showcase](https://i.imgur.com/XuonFAH.gif)

(note: further features/improvements planned/coming!)

**Comment by Mr-Foxtrot** [comment]
Thanks! It works great!

**Comment by MulverineX** [comment]
For those who were using the discord experiment for replies, this is loosely based on their initial UI. They have since redesigned a more custom one for replies, and it is a component in the frontend. All that has to happen is a switch flipped on the backend and it will be available in vanilla, they're probably saving it for a feature drop. Once that happens ours will be updated to not interfere, and still provide a nice thing for in-message links, and quotes.
