### ISSUE TITLE
Pinned DMs

### ISSUE THREAD

**Issue by seany** [powercord-community/suggestions#209]
### Description
Similar to the BetterDiscord plugin, Pinned DMs allows you to pin DMs to the DM/Server list for quick accessibility. 

### More info
Makes it easier to access users/groups that you use frequently in a clean dropdown menu. Nothing too special.
The BD example can be found at https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/PinDMs

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by redstonekasi** [comment]
@killua how about this, is this what you need?
https://github.com/powercord-community/betterfriends

**Comment by killua** [comment]
> @killua how about this, is this what you need?
> https://github.com/powercord-community/betterfriends

Not exactly, that may pin friends to the top but you don't have the option of pinning group chats. I figured out there is a way to import the BD version of PinDMs in Powercord using bdCompat, but if anyone wants to make it natively for Powercord they can.

**Comment by MulverineX** [comment]
@killua perhaps file a suggestion on betterfriends to let you do it with group dm's? imo would be better than a whole other plugin.

**Comment by killua** [comment]
> @killua perhaps file a suggestion on betterfriends to let you do it with group dm's? imo would be better than a whole other plugin.

true, but some of the features in betterfriends i don't want and there isn't a way to toggle said features off, also, to recreate pinned dms it would need to allow you to change the name of the pinned message category and change the categories color, which i'm not sure they would want to add to betterfriends. like i said, i figured out there is a way to import the BD version of PinDMs in Powercord using bdCompat, but if anyone wants to make it natively for Powercord they can, no rush.

**Comment by MulverineX** [comment]
Toggles for features can be added, not sure what you mean by that second thing (maybe send a screenshot), and one of our guidelines is to keep relevant features together to serve users more rich plugins, so its better that they stick together :).

**Comment by MulverineX** [comment]
@killua

**Comment by enzofrnt** [comment]
up ?
I really need that, the BD version doesn't work.

**Comment by Bricklou** [comment]
I'm also interested in a port for powercord since I would like avoid using bdcompat which make lag my discord.

Edit: I will look about this plugin if I have the time but I won't be able to maintain it.

**Comment by Bricklou** [comment]
Some updates ! I finished a first part of the plugin. You can now pin users and groups in Channel List.
If you find any bug, don't hesitate to create a new issue.
https://github.com/Bricklou/powercord-pindms
