### ISSUE TITLE
Quickly cycle through last message editing

### ISSUE THREAD

**Issue by C07733** [powercord-community/suggestions#211]
### Description
You know when you've made a mistake and you need to fix that horrendous typo 2 messages above your last one? And you can't seem to find the button to edit as the chat's moving as fast as ever?

Well, that's why I'm suggesting a quick snippet, or option inside Powercord itself to allow navigation upwards when you go to edit your last message, allowing you to edit the message above that which you're currently editing.

### More info
**The default shortcut for this is pressing "ArrowUp".**
It could be made so "ArrowUp" goes to the message above for editing.
As of now It just goes to the start of the currently being edited message, which is also a useful feature.

**My preference is "ArrowUp" to go upwards the message stack, and "Shift+ArrowUp" to go to the start of the message.**
_For those unaware you can also go to the start of your message by doing the combo "Ctrl+A" + "LeftArrow"._

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
Wouldn't this request be somewhat covered by #116?

**Comment by C07733** [comment]
> 
> 
> Wouldn't this request be somewhat covered by #116?

Technically I'm asking for a redefinition of how an action works. He's asking for more actions.
Please be patient with me as I use github sparingly, this my first ever issue heheh, so tell me what I should do. Is this considered the same issue?

**Comment by cyyynthia** [comment]
Discord now implemented this in the official client with their new keyboard navigation.
