### ISSUE TITLE
Auto Play Gifs plugin

### ISSUE THREAD

**Issue by supermxn** [powercord-community/suggestions#215]
### Description
https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AutoPlayGifs

### More info
Would be nice to have as I mainly use this for BD

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ADoesGit** [comment]
already exists https://github.com/griefmodz/autoplayGifAvatars

**Comment by supermxn** [comment]
is this outdated?
