### ISSUE TITLE
See who are typing

### ISSUE THREAD

**Issue by ZarevGt** [powercord-community/suggestions#218]
### Description
When too many people are typing, Discord just shows “Several people are typing...”
May we have a plugin that allows us to hover over the “Several people are typing...” and actually see who are the specific people that are typing?

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Fezalion** [comment]
https://github.com/GriefMoDz/smart-typers
This has the feature to show users who typing up to 8

**Comment by MulverineX** [comment]
@ZarevGt next time please look and/or ask for a plugin before you suggest it, and now please close this GitHub issue.
