### ISSUE TITLE
Scan File via VirusTotal

### ISSUE THREAD

**Issue by Giangamerino** [powercord-community/suggestions#220]
### Description
A plugin that would check a file using the VirusTotal service. Can be accessed by right-clicking on a file > hitting scan.
Could have an UI inside discord or just open the page going directly to the scan page.

### More info
I've been getting some malicious files through Discord DMs lately. (I reported these Individuals already.) VirusTotal always helped me out here. I always wanted a way to simplify this process than always going to the page, pasting the link, etc. It could help less experienced users be a tiny bit more secure across Discord. This can most likely be utilized by using VirusTotal's API.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Sidemen19** [comment]
I made [the plugin](https://github.com/Sidemen19/virus-checker), right now it just opens the result in a new browser tab, but I might add an option to show it in a modal someday.
