### ISSUE TITLE
Permission Viewer

### ISSUE THREAD

**Issue by transodonyx** [powercord-community/suggestions#222]
### Description
View permissions for each role, BD alternative made by Zerebos

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
@transodonyx this is already a thing https://github.com/powercord-community/permission-viewer . If you want improvements, updates, etc, you can file an issue on there. (and/or ask on the porkord for someone to pick it up again).

**Comment by MulverineX** [comment]
Relevant-ish plugin https://github.com/Puyodead1/powercord-ownertag

**Comment by transodonyx** [comment]
> @transodonyx this is already a thing https://github.com/powercord-community/permission-viewer . If you want improvements, updates, etc, you can file an issue on there. (and/or ask on the porkord for someone to pick it up again).

i tried downloading this plugin, its broken for some reason. i can't use it, or maybe there are dependencies

**Comment by MulverineX** [comment]
@transodonyx okay then again, you can file an issue on there. If the original author doesn't intend on fixing it, you can try to get some plugin dev to pick it up on the powercord discord. In the meantime you may have some luck with the BD version of the plugin using https://github.com/Juby210/bdCompat

**Comment by transodonyx** [comment]
> @transodonyx okay then again, you can file an issue on there. If the original author doesn't intend on fixing it, you can try to get some plugin dev to pick it up on the powercord discord. In the meantime you may have some luck with the BD version of the plugin using https://github.com/Juby210/bdCompat

okay, i'll try

**Comment by A-Trash-Coder** [comment]
A PR was made that fixed: https://github.com/Rodentman87/permission-viewer
