### ISSUE TITLE
BadgesEverywhere Plugin

### ISSUE THREAD

**Issue by Us3rNqmed** [powercord-community/suggestions#223]
### Description
BadgesEverywhere. The ability to see Badges Everywhere.

### More info
The Badges will be shown in chat messages and memberlist, like DB.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Sidemen19** [comment]
This plugin already exists.

**Comment by Bowser65** [comment]
Please make sure there isn't already a plugin before requesting: https://github.com/powercord-community/badges-everywhere

You can find the list of available plugins in our support server.
