### ISSUE TITLE
AutoRead

### ISSUE THREAD

**Issue by Us3rNqmed** [powercord-community/suggestions#224]
### Description
A plugin which will basically automatically read messages in a certain server.

### More info
You will have the ability to chose certain channels in servers to autoread.
Or make a time which all servers would be autoreaden.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Juby210** [comment]
timed mutes exists, your idea would fall under self-botting like actions guideline

**Comment by MulverineX** [comment]
yeah and if its cause you don't like the styling of a muted channel use/make a css snippet/theme to change that.

**Comment by Bowser65** [comment]
This would be in violation of our guidelines regarding selfbotting:

> **4. Plugins are prohibited from implementing selfbot-like behavior**
> This is to ensure our users do not get banned from indirect ToS violations, and to avoid abuse.
> https://powercord.dev/guidelines

**Comment by slow** [comment]
@Us3rNqmed https://github.com/slow/mark-all-read

**Comment by BenSegal855** [comment]
@Us3rNqmed, That repo is from a known malicious software developer. They have used powercord plugins in the past to steal users tokens and preform malicious actions. Avoid any and all software from @slow at all costs.

**Comment by ghost** [comment]
This doesnt quite look like a virus tho
