### ISSUE TITLE
DiscordMyTyping

### ISSUE THREAD

**Issue by RektWithStyle** [powercord-community/suggestions#225]
### Description

A plugin that shows the gif when you're typing.

### More info

Similar to [this plugin](https://github.com/An00nymushun/DiscordMyTyping), this will show the "username is typing..." gif at the bottom of the textbox whenever Discord shows to other members that you're typing something.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
This would probably better served as a feature addition to [Smart Typers](https://github.com/GriefMoDz/smart-typers), can file an issue on there asking for this.

**Comment by GriefMoDz** [comment]
This suggestion can now be closed as "Smart Typers" provides self-typing as a configurable setting (https://github.com/GriefMoDz/smart-typers/commit/44a500f26e14f7e7c3f650cc7bdf2ecfeaedd708). Thanks!

**Comment by RektWithStyle** [comment]
Thank you @GriefMoDz for the commit, I'll go ahead and close this now.
