### ISSUE TITLE
WhoIs Command

### ISSUE THREAD

**Issue by pythonmcpi** [powercord-community/suggestions#227]
### Description
`.whois <username#discrim>` or `.whois <userid>`
Shows user info in the form of an embed

### More info
Embed could look something like this but maybe with more details, like mutual servers/friends
https://plz.go-outsi.de/AIdUjQ
It would be even better if the name could be (right)clicked to show the normal user modal.
I mainly want this plugin so I can quickly check info about a user without pinging them, or letting others know I'm checking someone.
If this is run in a server the target is not in, it will not show roles.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Allow me to introduce you to [User Detials](https://github.com/Juby210/user-details.git)

**Comment by MulverineX** [comment]
@pythonmcpi ^^. If thats sufficient you can close this issue

**Comment by Bowser65** [comment]
User Details is completely out of the request scope, the idea would be to have an actual command to fetch based on a user ID or more generally when you don't have access to the user modal.

**Comment by MulverineX** [comment]
Ohhhh okay, that makes sense. Ideally from there, it'd then open a user modal (with some info removed if you can't access it). Fair enough then, sounds neat.

**Comment by webtax-gh** [comment]
[Userid-info](https://github.com/webtax-gh/userid-info) exists but it's only for id's.

**Comment by romdotdog** [comment]
would this plugin friend the username#discrim to get the id? maybe unfriend after that?

**Comment by MulverineX** [comment]
Ideally if someone wrote the code to do that it would be directly integrated with webtax's plugin. (And hopefully that'd then get renamed)

**Comment by pythonmcpi** [comment]
I'll probably try making this plugin.

**Comment by pythonmcpi** [comment]
On second thought, improving [Userid-info](https://github.com/webtax-gh/userid-info) seems like a better idea.
