### ISSUE TITLE
Category search

### ISSUE THREAD

**Issue by albert-softie** [powercord-community/suggestions#23]
### Description
A plugin that allows you to search for something in every channel in a given category.

A button in the search box that appears when typing something that allows you to select a category to search, and when searching, will return results from every channel within that category.

----

- [x]  I checked if this request wasn't already proposed
- [x]  I made sure this request follows Powercord's plugin guidelines

**Comment by Bowser65** [comment]
This request has been suppressed by #156; I'll be closing this one in favor of the more complete/feature rich suggestion.
