### ISSUE TITLE
Deezer integration, (Deezcord)

### ISSUE THREAD

**Issue by KingKusuo** [powercord-community/suggestions#230]
### Description
You know the little Spotify menu in Powercord? So, it would be the same, but with the Deezer app/website (if possible to do with both)

### More info
I am not a programmer, so i don't really know if it possible to do such a thing, but here is a simple idea:
The Spotify menu looks like that: 

![](https://cdn.discordapp.com/attachments/644220552554217506/768283670963421214/unknown.png)

And the Deezer menu would look like that (Their logo color pallete): 

![](https://cdn.discordapp.com/attachments/644220552554217506/768285799175028756/test_deezerpowercord.png)

You'd be able to pause, to skip the song and everything the current Spotify does, but as i already said, with Deezer instead. I don't know how many info i can give since it's just "replacing" the Spotify integration with a Deezer one, but yeah thats my suggestion, as a Deezer user i would absolutely LOVE this plugin, thanks for reading.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by mrrobboss** [comment]
There is an API https://developers.deezer.com/ (requires logging in to access) but im not sure if you can stuff like skip songs with it. Would probably require local media controls.

**Comment by Bowser65** [comment]
Deezer does not provide a realtime interface to get status updates. It does not even include a now playing status endpoint.
