### ISSUE TITLE
In-App Media Controller

### ISSUE THREAD

**Issue by MulverineX** [powercord-community/suggestions#234]
### Description
A fork of pc-spotify that includes any media player thats supported by the [Media API](https://github.com/powercord-org/powercord/issues/418).

### More info
N/A, see Media API suggestion.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
#138 #129 #161 #232

**Comment by MulverineX** [comment]
Since all sites that use audio now report to mediasession on chromium-based browsers & firefox, this would automatically have support for any music webapp/pwa. Obviously you'd want to do some filtering, to make sure you're not picking up some news site or a web game, this could probably be done easily by requiring album art and/or having an app whitelist.

**Comment by Bowser65** [comment]
As per https://github.com/powercord-org/powercord/issues/418#issuecomment-719934067, the only actual implementation case is already covered by #138 making this a duplicate.
