### ISSUE TITLE
Native Media Activity

### ISSUE THREAD

**Issue by MulverineX** [powercord-community/suggestions#236]
### Description
Allows you to send rich presence from native media players supported by the [Media API](https://github.com/powercord-org/powercord/issues/418)

### More info
- Allow the user to customize the format of the presence, with variables for song title, artist name(s), album name, playlist name, platform/app, etc, similar to [BetterQuoter](https://github.com/Juby210/better-quoter)'s markdown customizer.
- Toggles for time/play-pause state/etc reporting
- Provide multiple built-in discord app id's for popular music players with their respective logo's and app names.
- For getting the necessary data see the Media API suggestion.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
Relevant suggestions: #138 #161

**Comment by MulverineX** [comment]
Also #234

**Comment by Bowser65** [comment]
Refer to https://github.com/powercord-org/powercord/issues/418#issuecomment-719934067.

Updating media status is already possible through web APIs on all platforms, powered by Chromium backend. #138 remains the only relevant implementation case.
