### ISSUE TITLE
Searchable Badges 

### ISSUE THREAD

**Issue by Motzumoto** [powercord-community/suggestions#237]
# What im asking for
To be able to search by Badges to see if there for really one purpose, to see if there are any discord staff members in a server, or see whos the highest booster in a server, I'll figure out more ways I could possibly use that later on if the plugin gets made. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by romdotdog** [comment]
Not sure if this is possible, since members are lazy loaded, meaning they're only loaded when needed. Force loading them would probably break guideline 3.

**Comment by NotExactlyMeButMeh** [comment]
Not only ^, I believe badges are only loaded when you visit the profile unless you otherwise request it which could get you ratelimited.

**Comment by Bowser65** [comment]
Next time, please follow the template provided. Request might get automatically rejected in the future if not complying.

As mentioned, members are lazy loaded to help improve performance and memory usage when browsing big servers. Force loading them is not really a viable solution easier (Self-botting).
