### ISSUE TITLE
Slow Mode Auto Edit

### ISSUE THREAD

**Issue by tobimori** [powercord-community/suggestions#238]
### Description
A plugin that adds your new message to your last message (edits that) if its under the last x messages if you're still in slow mode at the moment you're sending that message.

### More info
![image](https://user-images.githubusercontent.com/29142128/97437044-39405800-1923-11eb-9364-a1269fb763c1.png)
Sending now would edit the message like that:
![image](https://user-images.githubusercontent.com/29142128/97437107-4cebbe80-1923-11eb-86fc-92a5c9e54f32.png)
("SLOW MODE" was part of the previous content, "slowmode" got added)

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by c0dine** [comment]
OML I would totally do this! that would be so useful

**Comment by cyyynthia** [comment]
Is there any other use case that isn't related to abuse, or attempting to facilitate the circumvention of permissions set by server administrators? Unless another use case is brought this is not allowed as per our [guidelines](https://powercord.dev/guidelines).

**Comment by tobimori** [comment]
Do you really think this would provide an opportunity to abuse?
For me it seems more like a QoL improvement, it would just remove the need to `ARROW UP`. And editing within the time limit is per se not forbidden by the slow mode.

**Comment by cyyynthia** [comment]
A lot of people who want this feature uses it to edit their message as a way to "send another one" but without having the send permission because of the slow mode. Which is effectively an attempt to bypass a restriction set by admins.

**Comment by tobimori** [comment]
They could also just edit their last message by themselves. I don't see a problem here.

**Comment by cyyynthia** [comment]
The guidelines are very clear: **facilitating** abusive behavior is not allowed. You've been pointed at them 2 times and you declared that you read them when filling the template.

**Comment by tobimori** [comment]
I don't think editing a message is abusive behavior at all, adding information to a message is a very normal thing in chat rooms.

**Comment by cyyynthia** [comment]
To actually edit the message to add complementary information you'd have either to retype it, or hit Ctrl+Z, or hit arrow up. Retyping it seems very unlikely, Ctrl+Z is 2 key strokes and arrow up is only 1 key stroke.

The only logical reason one would want such behavior is to fully rewrite the previous message during slowmode cooldown, which is as I said **attempting to bypass the restrictions set by administrators**. Features used 1% for legit purposes and 99% abuse do fall under abuse guidelines for obvious reasons.

**Comment by tobimori** [comment]
I do not encourage to fully rewrite the previous message, but automatically add the sent message to the last one.

This is just `ARROW UP` + `SHIFT+ENTER` + typing your message + `ENTER`, but made easier.

**Comment by TheMadHau5** [comment]
I don't see why this got declined, how does _adding_ a new message via editing (not a full rewrite) facilitate abuse?
