### ISSUE TITLE
Powercord Plugin Manager

### ISSUE THREAD

**Issue by NurMarvin** [powercord-community/suggestions#24]
### Description
Like NPM. but for Powercord plugins.
Basically will allow you to do `ppm install plugin-name-here`  in Discord or in the command line, as well as a website containing all the plugins that you can install via a click of a button.

### More info
This is a stupid idea, hence I will do it myself.
I'm only posting this here so no one else thinks about doing something like this while I'm working on it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by NurMarvin** [comment]
This plugin is postponed till Powercord's plugin marketplace is done.

**Comment by CodingKanin** [comment]
@NurMarvin will the plugin manager nullify this or would you like to keep it open?

**Comment by NurMarvin** [comment]
I think this will be nullified, I'll close the issue till and will reopen it if I ever want to actually make it a reality.
