### ISSUE TITLE
Message context button to show/hide embed & link-preview on per-message basis

### ISSUE THREAD

**Issue by glox18** [powercord-community/suggestions#240]
### Description
Sometimes bot/webhook embeds and image previews can simply be _too_ large. This plugin would allow users to show and hide embeds, images, and link previews on a per-message basis through the clicking of a button, while still showing the message text.

### More info
+The button should be in the message context menu.
+The button should act as a toggle, hiding and showing a messages' embed/images/link preview.
+**Message text and reactions should still be shown even if the embed/images/link preview is hidden.**
-The plugin/client remembering which messages have their embed/preview containers hidden is **NOT** necessary.

If it's possible: 
When a user has hidden a message's embed/image/link preview, append a `(content hidden)` line similar to the `(edited)` line that appears after the message text on an edited message. 
Or have the button be dynamic, like being a "-" to hide things when they are shown, and a "+" to show things when they are hidden.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by A-Trash-Coder** [comment]
WIP

**Comment by A-Trash-Coder** [comment]
https://github.com/A-Trash-Coder/preview-hider

**Comment by glox18** [comment]
Good job! Is it possible to leave the reactions visible?

**Comment by A-Trash-Coder** [comment]
I did not realize it removed the reactions, I will look into this. Apologies

**Comment by A-Trash-Coder** [comment]
Fixed in https://github.com/A-Trash-Coder/preview-hider/commit/612d5237aff4f33c650faa34754c5419f6d96ecb
