### ISSUE TITLE
powercord themes installer

### ISSUE THREAD

**Issue by imadtg** [powercord-community/suggestions#242]
### Description
basically https://github.com/LandenStephenss/PowercordPluginDownloader but for #theme-links

### More info

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This already exists https://github.com/ploogins/PowercordThemeDownloader
