### ISSUE TITLE
Plugin Categories

### ISSUE THREAD

**Issue by DanKGooGLy** [powercord-community/suggestions#244]
### Description
Plugin Categories

### More info
A plugin that would allow you to put plugins in categories, allowing for easier organization.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
This request would be better suited for Powercord's base repository, rather than a plugin request since it's heavily discouraged (and will no longer be possible at some point in the future) to alter other plugins settings UIs.
