### ISSUE TITLE
Support for new Discord slash commands UI

### ISSUE THREAD

**Issue by Aktimoose** [powercord-community/suggestions#246]
### Description
A powercord section in the new Discord slash commands UI (available through Discord Experiments)

### More info
Here's an example where I added a 2nd button
![image](https://user-images.githubusercontent.com/44620677/97648339-65a3c380-1a4c-11eb-96e5-49d1bb3ffe13.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
We do not accept requests for feature not released by Discord available under experiments, because they are subject to change and aren't officially released.
