### ISSUE TITLE
Quick Delete

### ISSUE THREAD

**Issue by xFastx** [powercord-community/suggestions#249]
### Description
Quick delete function: By holding the `delete` key, you click anywhere on a message, and it deletes. Lets you quickly delete multiple messages by just clicking on every message.

### More info
Idea taken from DevilBro's "MessageUtilities" plugin, but I am just looking for the quick delete function. 
Just to clarify: it doesn't delete multiple messages at once (I was informed this would be breaking guidelines), its 1 click per message; but instead of having to hold `shift` and clicking the small trashcan icon, you hold `delete` and press anywhere on the message to delete it. Useful for times where you can't purge (*cough* carl rate limits).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NEvana0003** [comment]
If you want a solution quick, you can use [Lighty's QuickDeleteMessages](https://_lighty_.gitlab.io/bdstuff/plugins/QuickDeleteMessages.plugin.js) with [bdCompat](https://github.com/Juby210/bdCompat)

**Comment by Bowser65** [comment]
This idea has already been declined in #193 in favor of new behavior Discord introduced when holding shift, which lets you delete messages with a single click (and actually more).
