### ISSUE TITLE
quick bot invite links

### ISSUE THREAD

**Issue by MightySword** [powercord-community/suggestions#250]
### Description
A plugin that allows you to quickly open an invite link to the selected bot.

### More info
 This would best be done through context menu and/or profile

there could even be settings for what the permissions integer would be set to.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by A-Trash-Coder** [comment]
WIll do

**Comment by A-Trash-Coder** [comment]
Done: https://github.com/A-Trash-Coder/Quick-Bot-Invite

**Comment by MightySword** [comment]
well damn, that was fast.
