### ISSUE TITLE
Favourited Gifs

### ISSUE THREAD

**Issue by moebamba** [powercord-community/suggestions#252]
### Description
Plugin to permanently store favourited gifs

### More info
When you log out of your account, the gifs that you star/favourite disappear. This plugin would store them so they don't disappear when you log out or if something happens.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
This would be especially powerful with settings sync once it comes, +1

**Comment by DracoClaw** [comment]
If this is being made, can Favorite Emojis/Most Used also be included?

**Comment by Vendicated** [comment]
I will make this plugin, seems like a cool idea! and yeah I will also include emotes

**Comment by Vendicated** [comment]
Done! It does Emojis too

https://github.com/VenPlugs/PersistFavourites
