### ISSUE TITLE
View .zip content

### ISSUE THREAD

**Issue by Snapperito** [powercord-community/suggestions#253]
### Description
A simple plugin to view .zip content

### More info
A plugin like Juby's text-file-viewer, but to view and navigate through the files of .zip folders.

If any help is needed with styling, feel free to message me.

this might help too :D  https://github.com/Stuk/jszip

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
I could make this part of Rich Embeds 👀 (#136)

**Comment by DanKGooGLy** [comment]
You're making rich embeds?

What would it be like?

**Comment by DanKGooGLy** [comment]
Nvm i'm dumb sorry mate

**Comment by Snapperito** [comment]
being implemented in #136
