### ISSUE TITLE
Open in Tidal

### ISSUE THREAD

**Issue by smellyfinger** [powercord-community/suggestions#254]
### Description
Tidal links open in tidal

### More info
For example, open in Spotify or open in steam plugins. Someone sends a link for a tidal song or playlist, you press it then it opens up in the Tidal desktop app. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
I'll close this in favor of more general #319, since this kind of platform-specific requests is starting to make a few somewhat duplicated requests and will definitely lead to tons of micro-plugins which isn't ideal.
