### ISSUE TITLE
Modifying chromium flags from within Discord

### ISSUE THREAD

**Issue by Robzyy** [powercord-community/suggestions#256]
### Description
A plugin which will add a new settings page where the user can enable/disable chromium flags

### More info
Would be helpful for those (like me) who don't want the media keys to interact with the dumb discord memes, but with Spotify, this being achievable thru the Hardware Media Key Handling flag

 ### N. B.
It can also be just a simple toggle for that one flag, but I believe that the intellectuals will probably find the other flags useful

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
With the upcoming restrictions Powercord v3 will impose on plugin runtime this will not be possible as a plugin. This request would be better suited for Powercord's core, so I suggest you to open an issue there.
