### ISSUE TITLE
Open In Twitch

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#258]
### Description
Same as all the other "open in..." plugins, opens twitch links in the desktop app and not the web browser.

### More info
With all these individual plugins, maybe it would be a good idea to have one "Open In App" plugin?

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
+1 on consolidating these open in-app features

**Comment by DracoClaw** [comment]
Seeing as [Open-In-App](https://github.com/Litleck/open-in-app) plans to do this ill close the issue.
