### ISSUE TITLE
Base 64 encoder

### ISSUE THREAD

**Issue by coveryourselfinoil** [powercord-community/suggestions#260]
### Description
A command, something to the likes of .b64 that sends the message you typed, but encoded

### More info
This idea was got after i used https://github.com/lorencerri/powercord-message-tooltips, since it translates base64, but not other ciphers like morse or binary.
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
Done: https://github.com/dutake/base64encoder
Completed by @dutake
