### ISSUE TITLE
File Hash Viewer

### ISSUE THREAD

**Issue by hairyfred** [powercord-community/suggestions#261]
### Description
Shows the hash of the file

### More info
Shows the hash of the file next to the download button
https://cdn.discordapp.com/attachments/755004260902764646/776033628177563698/tOJwSerclJEY.png
EG similar to that ^

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
I can implement this in Rich Embeds, the in-progress resolution of #136

**Comment by hairyfred** [comment]
> I can implement/add this in Rich Embeds, the in-progress resolution of #136 

Sounds goox

**Comment by cyyynthia** [comment]
Closing this in favor of #136 as per previous comments.
