### ISSUE TITLE
Quoting Feature Along Side Replies

### ISSUE THREAD

**Issue by Fahrenheit** [powercord-community/suggestions#265]
### Description
Bring back the quote feature for when replies has completely been roled out.

### More info
Having the quote feature along with the reply feature in the popup menu when selecting a message.
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Sidemen19** [comment]
I'll work on this.

**Comment by BenSegal855** [comment]
Isn't this already covered by [better quoter](https://github.com/Juby210/better-quoter)?

**Comment by Juby210** [comment]
it is

**Comment by MulverineX** [comment]
Yeah go ahead and close this @Fahrenheit cause there's overlap. If you want additional features that aren't in BQ already submit an issue on it's repo.
