### ISSUE TITLE
Audit Logging

### ISSUE THREAD

**Issue by ae-the-programmer** [powercord-community/suggestions#269]
### Description
I'm not sure but from some plugins I've found I believe you can listen for events that usually need permission to audit logs to see, could someone possibly make a plugin that has basically an audit logs plugin but for users. Preferrably looks the same as discord audit logs. I don't know if this falls under the "do not make plugins that normal clients cant see" guideline but please let me know if it does. Thanks, bye!

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by imadtg** [comment]
discord made this a separate feature and server owners choose to not allow everyone to have it, making a powercord plugin that circumvents this is like making a plugin that shows hidden channels.

**Comment by Bowser65** [comment]
This falls under guidelines 2 and 3.
