### ISSUE TITLE
Make message links show an embed like invites or store links

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#27]
**Describe the plugin**
read title thanks

**Expected behavior**
read title thanks

We must be careful on the amount of requests generated to prevent spamming the API too much, since we don't want accounts to get yeeted.

*[Original issue](https://github.com/powercord-org/powercord/issues/35)*

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by ghostlydilemma** [comment]
Eyyy my idea i never worked on ;w;
Didnt you make something that grabs the last messages already?

**Comment by Bowser65** [comment]
i think i wrote something that should be lost in one of the powercord's channels, but as i mentonned a major concern is not making too much requests to the API else the discord police will arrest u and that doesnt sound very cute to me

**Comment by CodingKanin** [comment]
However anything can be cute if @ghostlydilemma is involved.

**Comment by Juby210** [comment]
claimed

**Comment by ohlookitsderpy** [comment]
Juby has completed at https://github.com/Juby210/message-link-embed

Please close this issue
