### ISSUE TITLE
DM Typing Indicator

### ISSUE THREAD

**Issue by jeffboy70** [powercord-community/suggestions#270]
### Description
This plugin would add a typing indicator that would show up when ever someone starts typing in your dms.

### More info
The indicator would be under the home/dm button(under/above where the online friend count plugin is), and it would be text.  For example "User is typing" or "User#1234 is typing" or a setting to include the discriminator or not.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by dutake** [comment]
Hasn't that already been made? https://github.com/powercord-community/channel-typing

**Comment by jeffboy70** [comment]
> Hasn't that already been made? https://github.com/powercord-community/channel-typing

No.  The plugin I want would show if someone is typing in your dms, even when you are in a server.  That plugin only has support for group dms when you are in the dm screen anyway.

**Comment by MulverineX** [comment]
Perhaps this instead should be an issue over on that repository/plugin, as this feature would fit well with it (as it's essentially the same thing). @jeffboy70

**Comment by Litleck** [comment]
I could probably make this its own plugin if the channel-typing plugin doesn't add it.

**Comment by BenSegal855** [comment]
Completed: https://github.com/Litleck/DM-Typing-Indicator
