### ISSUE TITLE
Plaintext Emojis

### ISSUE THREAD

**Issue by SekoiaTree** [powercord-community/suggestions#272]
### Description
A plugin that adds on to the default discord emojis (doesn't have to have the same prefix, could be /name/ for example) by adding plaintext emojis.

### More info
Discord already *kinda* has this, with for example /shrug. However, this only works at the start of a message and overwrites the whole message content. It'd be nice if we could simply write /shrug/ and get the nice plaintext emoji. If possible, it'd be nice if the plugin lets you
1. Change the prefix/suffix
2. Add your own plaintext emojis

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
The Find and Replace plugin was made for just this reason.
https://github.com/power-plugs/powerfnr

**Comment by SekoiaTree** [comment]
god dammit I was sure I had checked well enough. Thanks.
