### ISSUE TITLE
Better Sytnax Highlighting

### ISSUE THREAD

**Issue by Daggy1234** [powercord-community/suggestions#273]
### Description
Replace discord's default syntax highlighter `highlightjs` with `prismjs` which imo has far better syntax highlighting. The highlightjs highlightung hasn;t been good for python, and prism looks a lot better.

### More info
https://prismjs.com/

Discord uses `code` for code syntax highlihting and is very similar to highlight.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
Ideally, if you were to replace it you'd use a library that implements a universal standard for syntax highlighting (like TextMate), because otherwise, it would still be quite restricted.

**Comment by katlyn** [comment]
[vpc-shiki](https://github.com/Vap0r1ze/vpc-shiki) replaces Discord's inbuilt Highlight.js with [Shiki](https://github.com/shikijs/shiki). While this does not directly fit the request of the plugin in regards to using Prisim.js, it fulfills all other requirements (and then some).
