### ISSUE TITLE
Inline Replies Keybind for Toggling Pings

### ISSUE THREAD

**Issue by LilKurisuu** [powercord-community/suggestions#274]
### Description
a keybind for toggling enabling or disabling pinging on replies

### More info
similar to the disconnect keybind for VC plugin but instead of disconnecting, it toggles the mention feature that you have to click on manually every time you reply to someone's message which could get very annoying. 
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Snapperito** [comment]
this could be included in #116

**Comment by Bowser65** [comment]
This would already be covered by #116
