### ISSUE TITLE
Quote Reply with Shift + Left Click

### ISSUE THREAD

**Issue by Hypertyrannical** [powercord-community/suggestions#278]
### Description
Shift + Left Click on messages to quote reply to a message, overriding the default (i.e. pasting a mention ping into the textbox).

### More info
The new quote reply functionality is definitely better than just mentioning someone, but I'm used to Shift + Left Clicking. Worse yet, you have to click on a button on the far right or use the context menu. So, overriding the default functionality would be preferred.

You might need to make sure it's compatible with this recent plugin that lets you set the ping default for quote replies: https://github.com/NotExactlyMeButMeh/no-auto-reply-ping (Or just include an option for it within the plugin.)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Sidemen19** [comment]
Bowser's recent plugin includes this feature - [better-replies](https://github.com/Bowser65/better-replies).
