### ISSUE TITLE
Read All Notifications Button.

### ISSUE THREAD

**Issue by ignAudioz** [powercord-community/suggestions#279]
### Description
Basically reads all of your notifications.

### More info
Nothing really to add just a button located under the home button of discord that reads all of your notifications.

----
 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines).

**Comment by Sidemen19** [comment]
This is a feature built into Discord, you can press the Inbox button then press the double checkmark in the top right corner.

**Comment by Bowser65** [comment]
As mentioned, this feature already exists in Discord. Here's where it's located:
![image](https://user-images.githubusercontent.com/9999055/99902047-32ef9280-2cbb-11eb-9af3-76f9f89a99cb.png)
