### ISSUE TITLE
in chat 8ball wizard thing

### ISSUE THREAD

**Issue by Soheab** [powercord-community/suggestions#28]
**Describe the plugin**
Like many bots have this, you ask a question and it gives a answer like as example 
Question: is powercord awesome?
Answer: Perhaps.

**Expected behavior**
Made this example with my bot, should be clear 

![image](https://user-images.githubusercontent.com/33902984/68037457-0cce0d80-fcc8-11e9-9582-c65c66a8a6f5.png)

The answers are from the nekos.life api.
----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
I strongly suggest against using an API for such a feature. It's pretty simple to implement and API's typically have special answers (that's really the only point for having an API, afterall). I have provided a table and a code snippet from `theGordHoard#9607` [here](https://canary.discordapp.com/channels/538759280057122817/631595204935155743/639894265727680522) including all 20 of the original responses.

Affirmative | Neutral | Negative
----------- | -------- | ---------
It is certain. | Reply hazy, try again. | Don't count on it.
It is decidedly so. | Ask again later. | My reply is no.
Without a doubt. | Better not tell you now. | My sources say no.
Yes - definitely. | Cannot predict now. | Outlook not so good.
You may rely on it. | Concentrate and ask again. | Very doubtful.
As I see it, yes.
Most likely.
Outlook good.
Yes.
Signs point to yes.

```javascript
const answers = [
  "It is certain.",
  "Reply hazy, try again.",
  "Don't count on it.",
  "It is decidedly so.",
  "Ask again later.",
  "My reply is no.",
  "Without a doubt.",
  "Better not tell you now.",
  "My sources say no.",
  "Yes - definitely.",
  "Cannot predict now.",
  "Outlook not so good.",
  "You may rely on it.",
  "Concentrate and ask again.",
  "Very doubtful.",
  "As I see it, yes.",
  "Most likely.",
  "Outlook good.",
  "Yes.",
  "Signs point to yes."
]

var answer = answers[Math.floor(Math.random()*answers.length)];
```

**Comment by Soheab** [comment]
Made it myself 🤷‍♂️ Here: https://github.com/Soheab/eightball
