### ISSUE TITLE
Chat games

### ISSUE THREAD

**Issue by DanKGooGLy** [powercord-community/suggestions#281]
### Description
A plugin that would allow you to play party games in chat such as Pool, Chess, Connect 4 etc. I got this idea from apps such as Gamepigeon for iOS and games on Snapchat.

### More info

This will probably only work with powercord users who have the plugin.
----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by SomeAspy** [comment]
https://github.com/powercord-community/minesweeper its a start.
