### ISSUE TITLE
PowerLinks

### ISSUE THREAD

**Issue by PWalll** [powercord-community/suggestions#283]
### Description
* Add a link preview (aka embed) when pasting a link into the message box
* Add a option to the context menu when right clicking a link to disable the embed (adding < at begging and > at the end of the link)
### More info
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by AAGaming00** [comment]
maybe this could be included somewhat in [PowerEmbeds](#136)?
