### ISSUE TITLE
Username Color Customizator

### ISSUE THREAD

**Issue by Sans3108** [powercord-community/suggestions#286]
### Description
We all know usernames in discord servers take the color of the highest role with a defined color a member has, what I want to suggest is a plugin that lets it's users customize that color.

### More info
The plugin should have 2 options: 

1. "Color 1" and "Color 2" - Those are colors that can be set by the user to be used for the username's color/s, they should each have a special option on top of a field where users paste the hex/rgb color they want and that is "User Role 1" and "User Role 2".
2. Gradient - _true_/_false_ type of option - Wether or not to make the final color a gradient using the colors set.

Options explanation:

1. "User Role 1" and "User Role 2" are colors defined by a user's first and second role's colors, if the roles have a color set, otherwise those 2 will be white as roles without a color set are by default shown white.
2. If this option is set to _false_ then "User Role 1" will be used as the color of the username, but if this option is set to _true_ then the username will be a gradient made out of "Color 1" and "Color 2", also when this option is _true_ another option should appear below it:
- Gradient Orientation - "Left to Right", "Right to left", "Up to Down", "Down to Up", pretty self explanatory, first direction is "Color 1" and the second one is "Color 2".

That is it, for any contact my discord is Sans#0001. Thank you for reading and if you decide working on my suggestion, thank you for doing so.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Snapperito** [comment]
Local Nicknames can accomplish everything listed besides the gradient. if anyone would like to create this plugin, please consider forking/contributing rather than creating a new plugin. also maybe consider adding a setting to use the Gradient-Names database as an option for names :D

**Comment by Sans3108** [comment]
> Local Nicknames can accomplish everything listed besides the gradient. if anyone would like to create this plugin, please consider forking/contributing rather than creating a new plugin. also maybe consider adding a setting to use the Gradient-Names database as an option for names :D

I just started using Powercord, I'm not sure what is possible and what is not, also I don't know what is gradient-names database... I'm not that great with english, I had to edit my issue to fix some things... sorry

**Comment by Snapperito** [comment]
> I just started using Powercord, I'm not sure what is possible and what is not, also I don't know what is gradient-names database... I'm not that great with english, I had to edit my issue to fix some things... sorry

Gradient names database - https://github.com/Discord-Custom-Gradient-Names/gradient
Local nicknames -  https://github.com/Oocrop/local-nicknames

**Comment by cyyynthia** [comment]
Local nicknames lets you do that. As mentioned, if you really want to have gradients you should request this feature on the local nicknames issue tracker.
