### ISSUE TITLE
Tray icon changer

### ISSUE THREAD

**Issue by Nixuge** [powercord-community/suggestions#287]
### Description
A plugin to replace the tray icons with any png you want

### More info
nothing

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Snapperito** [comment]
This can be accomplished easily without a plugin. you can follow [this guide](https://www.makeuseof.com/tag/change-taskbar-icons-programs-windows-10/) to change the taskbar icon, or use any of the hundreds of applications that change the system icon rather than just the tray icon.

**Comment by Nixuge** [comment]
Idk if it was worded right but i want to change this icon: 

https://cdn.discordapp.com/attachments/510264841303359498/785517965117227028/unknown.png

I did it by just changing it while discord was starting but every restart it resets to default so it's quite annoying

**Comment by SomeAspy** [comment]
That would probably require access to the files of discord, and powercord V3 would probably kill that with sandboxing.
as far as I know, you shouldn't be able to modify it. I could be wrong though.

**Comment by Nixuge** [comment]
Ye was quite excepting that but isn't it possible to at least prevent it from redownloading it so you just have to put it there once? It doesn't happen when you ctrl+r and I doubt powercord can access it when it's starting tho

**Comment by cyyynthia** [comment]
Changing the system tray icon is too low level for a plugin to do it, and as it's been mentioned, it won't even be possible to workaround in v3 as plugins won't be able to access arbitrary files on the system.
