### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#29]
### Description
Add a tab in the friends list on discord that would be the "Contact" list, showing contacts as a list/grid.

### More info
I'm really not sure if this is even possible but:
Preferably have a whitelist/blacklist toggle with the ability to add people to those lists. Blacklist ofc excluding the members you add to it from the tab and whitelist only showing the members you add to it. When clicking on a contact it should take you to their page of your contact book, allowing you to set email, phone number, timezone, etc etc. for said person. I feel like this could be really useful. Would also be nice to be able to have a list of various links for that contact and even a longer note section (higher character count) would be nice. Just look at your contacts on your phone and imagine that in Discord I suppose.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
I'm going to leave this as "pending review" until someone says if this is even doable.

**Comment by CodingKanin** [comment]
I've been told this is doable so I'll go ahead and set it as up for grabs. Bowser also mentioned the possibility of connecting it to external contacts such as Google contacts. Sounds like a lot of work but I hope someone takes it on!
