### ISSUE TITLE
Track my emoji usage

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#291]
### Description
So, I'm in too many emoji servers. A lot of which I'm not even sure I use the emojis from. It would be nice to have every emoji I use be counted and to be able to pull the list of them and see which I use the most. Bonus points for tracking gifs from the gif selector as well.

### More info
Emojis sent in chat, used as reactions, and used for your custom status should be tracked.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment]
For people who may want to implement this, Discord already tracks emoji use internally (used for the emoji picker). This data can be fetched using
```js
require('powercord/webpack').getModule(m => m.constructor?.persistKey === 'EmojiStore', false).getState().usageHistory
```

As of gifs, I don't think Discord tracks this so it'll require a custom tracker for this purpose.

**Comment by MulverineX** [comment]
Would be fantastic if this logged to the settings object as well, to persist & later on sync

**Comment by Kanin** [comment]
> Would be fantastic if this logged to the settings object as well, to persist & later sync

Was the intended result
