### ISSUE TITLE
Quick file previewer

### ISSUE THREAD

**Issue by Pepperspraylaugh** [powercord-community/suggestions#292]
### Description
A plugin that allows a user to preview a file quickly inside of Discord without having to open a file manager or browser.

### More info
Instead of having to open a file via browser or file manager, a user can hover their mouse over a file to get a quick preview of the code in a window within Discord (without executing it, of course.) This would apply to .txt and most common code formats (I.E. .py, .html, .css, .js, etc etc.) Users would still have the option to download/open files if they needed to. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Do you mean something like [text file viewer](https://github.com/Juby210/text-file-viewer)?

**Comment by MulverineX** [comment]
What exactly is wrong with text file viewer? Because I was planning on making Rich Embeds do it very similarly

**Comment by MulverineX** [comment]
I can consider adding inline text previews as an option to Rich Embeds.

**Comment by cyyynthia** [comment]
Discord added this as a vanilla feature.
