### ISSUE TITLE
Open Links in Steam

### ISSUE THREAD

**Issue by Aeywoo** [powercord-community/suggestions#294]
### Description
Open Steam Links in Desktop Steam Application.

### More info
A plugin that allows Powercord open the links from steamcommunity.com or store.steamcommunity.com in the Steam Desktop App, just like the Open Spotify Link plugin works with the Desktop Spotify App.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
Going to reference #258 where i said all the "Open in" plugins should be merged.

**Comment by Litleck** [comment]
I think I got this to a working state. I might work on it a little more though before sharing.

**Comment by DracoClaw** [comment]
@Litleck I think it would make more sense to pr an existing "Open In" plugin rather than adding another tiny plugin to the ecosystem.

**Comment by Litleck** [comment]
> @Litleck I think it would make more sense to pr an existing "Open In" plugin rather than adding another tiny plugin to the ecosystem.

I could just make one that opens in multiple apps and slowly add on to it.

**Comment by DracoClaw** [comment]
> I could just make one that opens in multiple apps and slowly add on to it.

I think that would be nice. Maybe speak with @lorencerri to make one larger plugin.

**Comment by Aeywoo** [comment]
So how long would the plugin take to create or put together?

**Comment by Litleck** [comment]
> So how long would the plugin take to create or put together?

So far I got the plugin to work with Steam links, here it is if you wanna try it. I'm not sure if it'll work perfectly but it seems to work for me. [Open-In-App](https://github.com/Litleck/open-in-app)

**Comment by cyyynthia** [comment]
I'll close this in favor of more general #319, since this kind of platform-specific requests is starting to make a few somewhat duplicated requests and will definitely lead to tons of micro-plugins which isn't ideal.
