### ISSUE TITLE
Keep the emoji picker open when an emoji is chosen.

### ISSUE THREAD

**Issue by Ryano81** [powercord-community/suggestions#297]
### Description
By default, the discord emoji picker closes the menu whenever you choose an emoji. This plugin would keep the menu open until it is clicked off of, allowing the user to choose multiple emojis, or the same emoji multiple times, without having to re-open the menu. 

### More info
It is pretty self-explanatory, nothing to add here.  

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by theGordHoard** [comment]
If you hold shift when clicking an emoji the menu will not close.

**Comment by Ryano81** [comment]
> 
> 
> If you hold shift when clicking an emoji the menu will not close.
-_- Yeah, never-mind then. I dint know you could do that.
