### ISSUE TITLE
'Read By:' message plugin

### ISSUE THREAD

**Issue by Maxukus0816** [powercord-community/suggestions#298]
### Description
plugin for powercord to see if your message was read and by who.

### More info
plugin for powercord to see if your message was read and by who. like in dms it would be read by whoevers in dms.
but in a server it would be read by who ever saw it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ezist** [comment]
This isn't possible, (iirc) Discord doesn't collect this information.

**Comment by Sidemen19** [comment]
Yes, Discord doesn't provide seen/read information.

**Comment by Litleck** [comment]
Yes, like others said I don't think this would be possible

**Comment by BenSegal855** [comment]
Declined as discord doesnt send this information to the client and may not even collect it.

**Comment by quincynyan** [comment]
I know this is closed and I'm 2 years late but I just had an idea. What if this feature is available only to people who have the plugin (like encrypted chat by sammy) and the plugin actually sends information to a 3rd party server when messages are marked as read locally. Of course, this would be messy on large servers but it'll work nicely in DMs.
