### ISSUE TITLE
Guild/Friend count above guild list

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#30]
**Describe the plugin**
Above the guild list and under the DM button it would bring back the "x friends online" label

**Expected behavior**
Clicking said label would then rotate between various info. Total friends, friends online, and guild count are the 3 that came to mind first. Maybe block count as well.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
/_**claimed**_

This suggestion is no longer up for grabs, but rather a work in progress. It's hammer time! :hammer:

**Comment by CodingKanin** [comment]
Unmaintained with some slight issues: https://github.com/GriefMoDz/online-friends-count read the unmaintained plugins channel for more information
