### ISSUE TITLE
Spotify - Context Menu "Controls"

### ISSUE THREAD

**Issue by lightcords** [powercord-community/suggestions#300]
### Description
A spotify "send song url" and "send playlist url" via the context menu (like Message Loggers "open logs") [I think message logger has smt like it? idk]

### More info
No extra information

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Already exists;
![image](https://user-images.githubusercontent.com/9999055/102697234-8dd1c680-4234-11eb-9587-2e4a29c517f3.png)

It'd also be preferable if you could refrain from mentioning plugin which violates our [guidelines](https://powercord.dev/guidelines).
