### ISSUE TITLE
Anti-typing status plugin

### ISSUE THREAD

**Issue by BootSwitch** [powercord-community/suggestions#301]
### Description
In Discord, when you are typing it shows that you are typing. However, with a plugin, the plugin could make it so it does not show that you are typing.

### More info
There is not really anymore information. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This plugin already exists https://github.com/kableko/silent-type
