### ISSUE TITLE
Fast resend

### ISSUE THREAD

**Issue by wathhr** [powercord-community/suggestions#302]
### Description
Whenever you press the up and down buttons, you scroll thru your most recently sent messages (like in CLI)

### More info
Of course this would have to remove the quick edit messages thing, so there should be an option to change hotkeys for all 3 buttons. 

----
 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by georgetzlp** [comment]
seems that discord already has this, instead of the up and down arrow you use ctrl + z and ctrl + y
