### ISSUE TITLE
User Count in Voice

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#309]
### Description
A count of how many members are in the voice channel. 

### More info
Currently the only way to see a count of users in the voice channel is when there is a member limit turned on. I'd like for something in the same style as that but for voice channels with no limit. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by tuanbinhtran** [comment]
@DracoClaw A bit late but done: https://github.com/tuanbinhtran/pc-voice-user-count

**Comment by DracoClaw** [comment]
Ayyy. Thank you so much! <3
