### ISSUE TITLE
sending large codeblocks

### ISSUE THREAD

**Issue by LandenStephenss** [powercord-community/suggestions#310]
### Description
A plugin for whenever the send large messages modal pops up. Specifically for code

### More info
Whenever you are sending a codeblock and the code is over 2,000 characters, discord trys to tell you to send the `.txt` file. But instead it could be `.whatever-language-the-codeblock-is`. Just a little thing to make life a bit better.

Although maybe this could be implemented in another way, splitting the message and making them both codeblocks, not sure if that is possible though.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
It'd be preferable imo to upload it to a haste server (e.g. haste.powercord.dev) and throw in the link with the proper extension, so people can look it up more easily even if they don't use client mods. Maybe this could be an additional feature of the built-in `pc-hastebin`?

**Comment by LandenStephenss** [comment]
That could work too, not sure how to do it tho so im requesting it :keuch:

**Comment by cyyynthia** [comment]
Discord allows changing the language used to highlight the file in their native preview thing, and to rename the file, so I guess it's fine to close this.
