### ISSUE TITLE
Per-message hiding for unwanted NSFL posts

### ISSUE THREAD

**Issue by MintLily** [powercord-community/suggestions#311]
### Description
Local hiding of per-post.

### More info
Some people post some NSFL / gore things on servers. This plugin will let you hide messages, on a per-message basis, upon expanding the more options menu on a message. [Image of Expanded Menu of a message -Example- Self-hosted image](https://kortyboi.com/img/upload/DiscordCanary_mQWA8JbLl0.png) <br>
I'd like this to have some sort of cache in-case server moderators never remove the post and that you don't ever have to see that message again.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by lavgup** [comment]
Already exists: https://github.com/cyyynthia/block-messages

**Comment by MintLily** [comment]
> Already exists: https://github.com/cyyynthia/block-messages

I've looked for a while, could not for the life of me, thanks
