### ISSUE TITLE
Hot Injection JS Window

### ISSUE THREAD

**Issue by 00face** [powercord-community/suggestions#312]
### Description
Hot inject/run JS on the fly, for things like adding snowing or typing effects. Editing would be done in the themes section, with a new JS editor tab.

### More info
Would operate just like the CSS window for themes.

----

 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
There will be no way to execute arbitrary code in the upcoming V3 release.
