### ISSUE TITLE
Reload Discord notification

### ISSUE THREAD

**Issue by georgetzlp** [powercord-community/suggestions#316]
### Description
Gives a notification every X amount of time to reload Discord.

### More info
The notification will include 2 buttons:
1. Reload
2. Remind me later

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by LandenStephenss** [comment]
why tho, whats the point in this

**Comment by georgetzlp** [comment]
> why tho, whats the point in this

to help free up memory and stuff like that

**Comment by cyyynthia** [comment]
You're better off with a plugin like #53 for this purpose rather than a super specific plugin. I'm unsure if it supports periodic reminders, but if it doesn't you should request this feature there instead.
