### ISSUE TITLE
Group typing indicator

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#32]
### Description
Replace the member count with the typing indicator that is usually below the text bar on groups. While someone in a group is typing, this will change to the typing indicator. It will just look normal if nobody is typing. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This is now part of https://github.com/powercord-community/channel-typing
