### ISSUE TITLE
DM Deleter

### ISSUE THREAD

**Issue by ShadowS132** [powercord-community/suggestions#320]
### Description
I was hoping that maybe someone could make a plugin which deletes your DM messages which you sent to another person.

### More info
I am not sure if this is considered as a self-bot but I think it will be very useful.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by k6d** [comment]
you can use  `slow/message-cleaner` and this is selfbotting  ( Breaks plugin guideline: 4 )

**Comment by BenSegal855** [comment]
@k6d please do not recommend people use plugins by a known bad actor. That plugin author has used their plugins to steal peoples tokens in the past

As mentioned, this idea is against our guidelines.
