### ISSUE TITLE
Change other people's names

### ISSUE THREAD

**Issue by Aluorine** [powercord-community/suggestions#323]
### Description
The plugin would change how other people's names would appear to me.

### More info
For example, I could choose that user User#0000 would always appear to me as "James". Kinda like in other messengers you choose names when saving contacts. This would override their server specific names and their name in the DMs.

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
Already exists. https://github.com/Oocrop/local-nicknames
