### ISSUE TITLE
Video Background Plugin.

### ISSUE THREAD

**Issue by MoltenCoreDev** [powercord-community/suggestions#328]
### Description
A video Background plugin, that can play links ended with `.mp4`. BetterDiscord alredy has this kind of [plugin](https://github.com/Fuguu/videoBackground)

### More info
All this plugin needs to do is inject a video player in the background.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by chasecrampton** [comment]
Just use [bdCompat](https://github.com/Juby210/bdCompat)

**Comment by BenSegal855** [comment]
> Just use [bdCompat](https://github.com/Juby210/bdCompat)

Or don’t because the bd plugin uses BDFDB and therefore has memory leaks. It is also almost always better to run a plugin made for powercord than to run one through a compatibility layer.

**Comment by MoltenCoreDev** [comment]
Yes, i submitted this suggestion so we don't need compatibity layers. Also when v3 releases bdcompat maybe broked tor some time. So for now, a good alternative is using bdCompat, but native version of that plugin would be better to run.
