### ISSUE TITLE
Extend discord's keybinds system

### ISSUE THREAD

**Issue by matortheeternal** [powercord-community/suggestions#330]
### Description
- Allow changing default keybinds
- Default tab focus selection on the last message visible in the chat
- Allow focusing a message by Control+Clicking it
- Allow skipping all messages in a group with Ctrl + Up
- Fix Ctrl+C not copying message content
- Add bindings for copying message id/link
- Restore quote message hotkey? (was removed when reply was added)

### More info
See [Discord Keyboard Navigation](https://support.discord.com/hc/en-us/articles/1500000056121-Keyboard-Navigation-FAQ
).  This existing functionality is nice but it's very incomplete.  I'm going to look into doing this myself if someone else doesn't pick it up first.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
I suggest you look at Discord's help article on [keyboard navigation](https://support.discord.com/hc/en-us/articles/1500000056121-Keyboard-Navigation-FAQ).

**Comment by matortheeternal** [comment]
> I suggest you look at Discord's help article on [keyboard navigation](https://support.discord.com/hc/en-us/articles/1500000056121-Keyboard-Navigation-FAQ).

edit- updated issue

**Comment by cyyynthia** [comment]
I'd consider this to be duplicate of #116, it'd probably be better to note your suggestions to that issue instead.

**Comment by matortheeternal** [comment]
Ah, I didn't see that.  Guess I didn't search for the right terms.  Will comment there.
