### ISSUE TITLE
Pinning DMs

### ISSUE THREAD

**Issue by Alfred-207** [powercord-community/suggestions#333]
### Description
Pin DMs to the DM list.

### More info
See screenshot below, you can make categories and assign people to said categories.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

![](https://i.vgy.me/sBTT9D.png)

**Comment by BenSegal855** [comment]
Duplicate of #209
