### ISSUE TITLE
Block people without them knowing

### ISSUE THREAD

**Issue by 15696** [powercord-community/suggestions#334]
### Description
The plugin would allow you to hide messages, pings, and DMs from a user without them knowing I blocked them.

### More info
There would be a button similar to "Block" but called "Ghost", which would:
1. Still let them ping me, but you wouldn't be notified.
2. Still let them send friend requests to you without getting an error, but you wouldn't see the request.
3. Still let them DM me without getting an error, but you wouldn't see the DM.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by aenriii** [comment]
this might work as a new feature to cutecord (if thats still active) bc it already allows for some user-specific notification settings

**Comment by kewdf** [comment]
https://github.com/powercord-community/cutecord

**Comment by 15696** [comment]
I don't want to see any of their messages or DMs though, is that a feature in cutecord as well? @jdadonut @kewdf

**Comment by cyyynthia** [comment]
There is already an issue about better management of blocks at #36. Prefer adding comments there, to keep everything at a same place.
