### ISSUE TITLE
Port of DateViewer

### ISSUE THREAD

**Issue by NyxIsBad** [powercord-community/suggestions#337]
### Description
Show the date in a box in the lower right corner

### More info
![image](https://user-images.githubusercontent.com/58749666/106332616-7ae9f180-62ca-11eb-8401-79da2904cecd.png)
Already created in BD

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by CodingArctic-zz** [comment]
loved this in BD, hope someone makes it!

**Comment by E-boi** [comment]
After doing some playing around I could do this.

**Comment by E-boi** [comment]
Done: https://github.com/E-boi/powercord-dateviewer

**Comment by NyxIsBad** [comment]
Very nice!
