### ISSUE TITLE
Message Logger/Deleted Message

### ISSUE THREAD

**Issue by carterlasalle** [powercord-community/suggestions#341]
### Description
A recreation of the BD MessageLoggerV2.  This would perform the same actions as the original plugin.
LINKS:
https://gitlab.com/_Lighty_/bdstuff/blob/master/public/plugins/MessageLoggerV2.plugin.js

### More info
The better discord Compatability plugin does not work with this one. This plugin helps ghost pings, deleted messages, purged channels, and more. 

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Next time maybe actually read the guidelines before checking off that your suggestions follows them.

**Comment by carterlasalle** [comment]
@BenSegal855 i did, how does that violate it

**Comment by BenSegal855** [comment]
From, guideline 2
￼> For example, logging all deleted messages is prohibited.

**Comment by carterlasalle** [comment]
> From, guideline 2
> ￼> For example, logging all deleted messages is prohibited.

Sorry man, I skimmed over it quickly and its super late here
