### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by NGTV1234** [powercord-community/suggestions#343]
### Description
Customizable Discord Rich Presence plugin in Powercord. Optional: Option to have Discord Rich Presence auto start with Powercord.

### More info
I'm aware there is a way to install this via bdcompact plugin, although it would be cool to have one designed for Powercord users as a powercord plugin.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
This has been done with [custom-rpc](https://github.com/E-boi/custom-rpc) by @E-boi.
