### ISSUE TITLE
Port of VoiceEvents

### ISSUE THREAD

**Issue by NyxIsBad** [powercord-community/suggestions#346]
### Description
When you interact with a voice channel/someone else interacts with the one that you are in, it will give TTS announcements i.e. [user name] has joined your channel, or You have joined [channel], etc. 

This has already been made in BetterDiscord, but does not work with bdcompat.

### More info
https://betterdiscordlibrary.com/plugins/VoiceEvents
The link to the original plugin is above ^^ 

Original also has options to change what the voice says and which voice to use (out of a selection of standard voices). 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
I think I can do this. So far it isn't too hard

**Comment by NyxIsBad** [comment]
This worked for a small while recently with bdcompat but just started crashing discord again ^^

**Comment by E-boi** [comment]
Once this gets approved I will make it.

**Comment by E-boi** [comment]
Hello, I have finished the plugin It's mostly like the original https://github.com/E-boi/voice-events

**Comment by NyxIsBad** [comment]
Thanks! That's astonishingly close and way beyond expectations. Someone can close with finished ^^
