### ISSUE TITLE
Continue to listen to music

### ISSUE THREAD

**Issue by Gnoun** [powercord-community/suggestions#348]
### Description
A plugin which allows to continue to listen to a music track after leaving the channel it is sent in.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
I'm unsure if I understand what you mean. Could you be a bit more specific?

**Comment by cyyynthia** [comment]
Closing due to the lack of reply.
