### ISSUE TITLE
Video confirmation dialog

### ISSUE THREAD

**Issue by hwalker928** [powercord-community/suggestions#349]
### Description
A popup window when you click the video button, saying are you sure you would like to turn on your camera.

### More info
Loads of buttons are all crammed together in the bottom left of Discord, meaning it is easy to accidentally press the video button, compared to the screen button which asks which window to use.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by LoganDark** [comment]
This has happened often enough that my webcam is actually taped over now

**Comment by hwalker928** [comment]
https://i.redd.it/djcb9y18nck71.jpg Just seen this on reddit
