### ISSUE TITLE
PinDMS like devil on BD

### ISSUE THREAD

**Issue by enzofrnt** [powercord-community/suggestions#351]
### Description
We can create DM folder like do devil on BD
Choice the color of the folder and the placement of all the dm folder
### More info
check devil code to help IDK

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Duplicate of #209
