### ISSUE TITLE
Copy Mentions

### ISSUE THREAD

**Issue by Sans3108** [powercord-community/suggestions#352]
### Description
Y'all know how there's context menus for when you right click a channel or even a role on a user or in the server settings?
This plugin will add a new button on that context menu, where if you click it, it will copy that user's/role's/channel's mention to your clipboard.

### More info
The button can be case specific, for example when you right click on a role it will say "Copy role mention" and when you click on a user it will say "Copy user mention" etc. or it can just be "Copy mention".

How it will work: I'm not sure how the coding for this will work, but the basic idea is that when the user clicks the button, the id of that channel/user/role is saved and to it is added the corresponding formatting symbols.

Example 1: I click on that button from a channel, the channel id, let's say "755012629457535026", will have added to it the channel formatting symbols turning it into "<#755012629457535026>" then the plugin will save that into my clipboard.

Example 2: I click on that button from a user, the user id, let's say "284122164582416385", will have added to it the user formatting symbols turning it into "<@284122164582416385>" then the plugin will save that into my clipboard.

There's really nothing more to explain, it's a simple, yet useful plugin.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by tealingg** [comment]
happy to do this, please mark it as in progress

**Comment by Sans3108** [comment]
> happy to do this, please mark it as in progress

Thank you for working on this! :)
Sorry I don't really know how to add labels though, github is not really a thing I know how to use properly...

**Comment by tealingg** [comment]
no worries, cyyynthia will tag it for you (they are the person that tags things after they are checked over and everything)

**Comment by tealingg** [comment]
completed, visible here: https://github.com/tealingg/copy-mentions/
