### ISSUE TITLE
Apple Music Rich Presence & Hook

### ISSUE THREAD

**Issue by girlvibe** [powercord-community/suggestions#354]
### Description
A plugin to connect/hook apple music directly to discord. Being able to see what is playing right from your profile & some other cool features.

### More info
Apple Music has api support now. It is called "MusicKit" it allows other programs to connect to the service. Being able to use it on software and sites of such. The only issue here is Discord might need your api token. I am not sure if that would have to be the case. But this plugin could definitely spark an idea for Discord to actually do it. Before it wasn't possible because of no api support but Apple Music supports it entirely. So I am a bit confused on why Discord has not added this feature yet if it's out to the public and many other sites and programs are starting to use it. Not many people use Spotify and this is a good alternative. I have seen many posts and forums of people asking for this since Discord was released and it has yet to come. Of course this would only be for Apple Music because it is a streaming service like Spotify. Hopefully you can help! I can submit an idea too if you'd like but basically it would be kind of similar to the way Spotify works with Discord. This might be a hard project but someone should give it a try and improve it as time goes! Thanks! Hopefully we can bring this dream feature for many to life! Much appreciated.

### Some Implemented Ideas I'd like to see:
- Rich presence showing what song you're playing with the artist, time, album artwork, and a highlight color to match the theme of Apple Music on your profile. for example Spotify is green so maybe like a white with red or a blur color to match the aesthetic of apple music and it's logo? ***Reminder:*** If you Google "**Apple Music Logo**" you can find a good color scheme to work with.
- The ability to add it to your profile so others can see your Apple Music profile. Yes there are apple music profiles. Apple added this feature a few years ago. So it could possibly work!
- Any other ideas that are similar to the Spotify feature on Discord.

### Some provided links to help [All Credit Goes to Apple]:
[What is Music Kit?](https://developer.apple.com/musickit/)
[Overview of the Apple Music API](https://developer.apple.com/documentation/applemusicapi/)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Unfortunately, while the API allows for static queries it does not provide sufficient APIs to implement something similar to the Spotify integration. Spotify has a websocket system that allows for real-time synchronization and is how Discord knows what you're listening to. Apple Music doesn't have this (and it's only possible on Spotify through commercial agreement as the real-time websocket is locked).

> Rich presence showing what song you're playing

This would be possible-ish, using an application but it won't be as pretty as Spotify unless Discord implements it themselves. Of course, the plugin could decorate it for other plugin users but the majority of users would see "Playing Apple Music".
