### ISSUE TITLE
A Port of DevilBro's NotificationSounds plugin

### ISSUE THREAD

**Issue by RinLovesYou** [powercord-community/suggestions#355]
### Description
I'd love a port of DevilBro's NotificationSounds plugin. Including the preset sounds it comes with. I might actually have a crack at this myself but I've never made plugins before so i figured i'd suggest it here

### More info
It would basically function just as DevilBro's plugin does
It comes with built-in sound alternatives
If no sound is chosen, it defaults to the native sounds
option to turn down volume per notification sound (An alternative to muting every discord server. Some servers don't set notifications to pings only, so muting the message sound for that is handy, as only keeping the ping volume up helps sound spam when in many servers) 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NyxIsBad** [comment]
https://github.com/ploogins/notif-sound-changer

Might already exist. I think this is what you're looking for.

**Comment by RinLovesYou** [comment]
This is definitely close! sadly it does not discriminate between server messages/pings/dms
but thank you for showing me this!!
