### ISSUE TITLE
Quick Delete Messages

### ISSUE THREAD

**Issue by NotDarkn** [powercord-community/suggestions#356]
### Description
What this plugin would do is that you would hold either the backspace key or a custom keybinded key and then click on a message and then it would quickly delete. Basically just hold a key, and click on a message and BOOM! It has been deleted.

### More info
This should work not only just on your own messages, but if you have Manage Messages permissions in a Discord server then those should be able to be deleted quickly aswell.

Now yes, while you can quickly delete messages by holding shift then clicking the red trash can on the side, it would be a lot more faster if you just had to already hold a button then click, it doesn't sound like it from my words but when you actually use the plugin it is indeed faster.

And yes, while a QuickDeleteMessages plugin already exists for BetterDiscord made by Lighty, it doesn't wanna work properly with Powercord, I've tested on both Discord Stable running BetterDiscord and then Discord Canary running Powercord, and it didn't seem to work with Powercord whatsoever.

----

 - [x] I checked if this request wasn't already proposed **(I kind of did?)**
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by aenriii** [comment]
I went head and made this, right now it's hardcoded to be the Backspace key, but custom keybinds are in the TODO for the (hopefully) near future

link: https://github.com/jdadonut/quick-delete-pc
