### ISSUE TITLE
Auto finish message

### ISSUE THREAD

**Issue by ciankellyy** [powercord-community/suggestions#360]
### Description
What i want this plugin to do is auto finish your message with whatever you want.
(example: you write "Hi" plugins writes "How are you?"
finished message: "Hi how are you!
### More info
No more info to say

----

 - [ x] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by sepruko** [comment]
I feel like `pc-tags` that is bundled with Powercord can fill this gap for you, at least with the provided example.

**Comment by katlyn** [comment]
as @NatSepruko has said, this is something that `pc-tags` can handle easily.
