### ISSUE TITLE
A plugin to change Discord's sounds (custom sound effects)

### ISSUE THREAD

**Issue by Patrosi73** [powercord-community/suggestions#363]
### Description
DevilBro's plugin that changes sound effects crashes Discord when you try to select a custom sound under bdCompat in PowerCord, so a plugin designed for PowerCord would be nice. With a plugin like this, you could change (if not every single one) Almost every sound effect in Discord to your choice. An option to select a custom sound effect would be very cool.

### More info
If it's possible, you could also change the Discord sound effects to another Discord sound effect, if that makes sense.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
https://github.com/ploogins/notif-sound-changer
