### ISSUE TITLE
Status Cycle

### ISSUE THREAD

**Issue by chasecrampton** [powercord-community/suggestions#364]
### Description
You would set a list of statuses and it would automatically cycle through them for you at random

### More info
Maybe you could set a time between changes

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
That would be [selfbotting](https://powercord.dev/guidelines#definitions:~:text=Selfbotting%3A)
