### ISSUE TITLE
Message logger 

### ISSUE THREAD

**Issue by shadmehr-salehi** [powercord-community/suggestions#367]
### Description
message logger : 
plugin that logs deleted / edited messages . this already exists in BD so i thought it would be great if we can have it in powercord too 

### More info
👍 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Kanin** [comment]
I take it you didn't read the guidelines at all, we don't allow message loggers.
