### ISSUE TITLE
Typing Status indicator

### ISSUE THREAD

**Issue by conrad-mo** [powercord-community/suggestions#368]
### Description
An animation on the side of certain channels that indicates when someone is typing in that channel

### More info
https://betterdiscordlibrary.com/plugins/TypingIndicator

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This plugin already exists https://github.com/powercord-community/channel-typing
