### ISSUE TITLE
Snippet adder

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#37]
**Describe the plugin**
This plugins would add a right click menu entry with the text "Add snippet" to CSS codeblocks.
It loads the snippet right after copying the code.

**Expected behavior**
Make it able to load multiple CSS snippet files. After clicking "Add snippet", you should get a small pop up asking you to name it. Once a name entered, it adds the snippet to a folder inside the plugins folder and loads those files. A tab in the settings would be nice to easily disable / re enable / delete them easily.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Another plugin for people who are too lazy to do things normally and too impatient for powercord updates :^)

**Comment by mrrobboss** [comment]
yes, so add it. now. or else i will make all eyes everywhere the latest
twemoji ones

**Comment by Bowser65** [comment]
This got added as a Powercord core feature
