### ISSUE TITLE
Open a program at discord start...

### ISSUE THREAD

**Issue by Blazzycrafter** [powercord-community/suggestions#372]
### Description
A plugin which starts any number of programs after Discord is started
### More info
is this required with my request?
I dont think so

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by zt64** [comment]
Wouldn't it just be better to start the programs when the system starts? I know for Windows you just drag a shortcut of the exe to some folder and it works.

**Comment by Blazzycrafter** [comment]
> Wouldn't it just be better to start the programs when the system starts? I know for Windows you just drag a shortcut of the exe to some folder and it works.

i dontknow why i send this here.... sry
