### ISSUE TITLE
Isolated video viewer 

### ISSUE THREAD

**Issue by AugustusUKR** [powercord-community/suggestions#373]
### Description
Play a video in a isolated space

### More info
If someone were to send a Discord crasher video and you watched it, the isolated space would be the only thing to crash, not the entire application 

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This is too low level to get integrated into a plugin. There is https://github.com/1Lighty/discord-crasher-checker which will warn you if a video will crash your system, and it seems Discord is working on mitigating the issue themselves anyway.
