### ISSUE TITLE
NoReplyMention Port

### ISSUE THREAD

**Issue by Zoriot** [powercord-community/suggestions#378]
### Description
NoReplyMention
### More info
Set the Reply Mention default to false. Port from https://github.com/somebody1234/userscripts/blob/master/NRM.plugin.js

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
i think this is the plugin your looking for https://github.com/cyyynthia/better-replies
