### ISSUE TITLE
Make Clyde Powercord™

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#38]
**Describe the plugin**
All plugin messages that are the default Clyde would be changed. The name would be changed to `Powercord` and the avatar would be ![image](https://cdn.discordapp.com/attachments/538759280497786890/555071986527633429/this-is-a-file.png)

(Possibly with the ability to customize the name/avi)

**Expected behavior**
N/A

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Bowser is a while asscheek <3

**Comment by Bowser65** [comment]
https://epic.weeb.services/0dbc326cdb.png
