### ISSUE TITLE
Plugin to Increase Voice Chat Volume Over 200%

### ISSUE THREAD

**Issue by Qoes** [powercord-community/suggestions#380]
### Description
A plugin that lets you increase user's volume by over 200% in a voice channel. 

### More info
Discord currently lets you raise a user's volume up to 200%. But sometimes, the user is still too quiet, so I want to raise it above 200%.
![image](https://user-images.githubusercontent.com/80235726/110272225-85a93d80-7f7e-11eb-8330-7b80806dc976.png)
I want there to be a way for us to customize the limit by changing it in the plugin settings. 
![image](https://user-images.githubusercontent.com/80235726/110272818-f0a74400-7f7f-11eb-9138-e615736f81a3.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
A nice QoL feature that might be nice to include would be a text box to input an exact number right above the slider.

**Comment by PandaDriver156** [comment]
Is this good enough?
![Preview](https://raw.githubusercontent.com/PandaDriver156/Custom-Volume-Range/master/screenshots/preview.png)

Limit is customizable through plugin settings

https://github.com/PandaDriver156/Custom-Volume-Range

**Comment by Qoes** [comment]
Yes it's good enough
