### ISSUE TITLE
Receive a notification anytime a specific user in a server sends a message

### ISSUE THREAD

**Issue by c133** [powercord-community/suggestions#385]
### Description
This plugin will send a Discord notification to the end user anytime a specific user in a server sends a message. User ID will be inputted into the plugin settings. If User ID 123 and 234 are inputted, then anytime those two users say anything in a specific server, (server that both the end user and specified users are in) a notification will be sent/displayed.

### More info
The closest plugin I have found that does this is Cutecord by katlyn. You input someone's User ID in Cutecord settings and a keyword and you will receive a notification if they say something that matches the keyword. However I spoke with katlyn and she mentioned Cutecord will not work in my desired way since it is based on keywords in someone's message. Cutecord is not able to notify you if a specific user sends any message in general which is what I am looking for. So for anyone who is willing to work on this suggested plugin, maybe the easiest way would be to fork Cutecord. 

This will not be used for stalking people; I am in several trading discords and I follow one or two specific people who make calls / give instructions. Currently there is no way for me to enable message notifications for only those specific people that I follow. This plugin would really help reduce noise. This plugin is basically like turning on alerts for someone you follow on twitter, except for someone's discord messages.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by RazerMoon** [comment]
[Here you go](https://github.com/RazerMoon/userNotifs), feel free to @ me if there are any issues. Definitely needs more testing.

Also decided to use context menu instead of id field cause validation is a pain.
