### ISSUE TITLE
Embed TikTok videos

### ISSUE THREAD

**Issue by RealRedcodi** [powercord-community/suggestions#386]
### Description
A plugin to embed Tik Tok videos like YouTube videos get embedded.

### More info
It should accept both short (https://vm.tiktok.com/ZMeB6hPCh/) and long links (https://www.tiktok.com/@the_amazon_driver/video/6939248362998861062?sender_device=pc&sender_web_id=6918911637194704390&is_from_webapp=v3&is_copy_url=0). Embedding guides can be found [here](https://developers.tiktok.com/doc/Embed)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This would fall as a duplicate of #136 which is a broader issue about enhancing what gets embedded in chat. Add a comment there with the resources you've listed here so it's all in one place!
