### ISSUE TITLE
Port of CrashRecovery

### ISSUE THREAD

**Issue by iblowmymind** [powercord-community/suggestions#387]
### Description
As the BD plugin's name suggests: recover you from a crash.

### More info
An issue I was facing recently made me found this plugin that tries to both recover a crash, report which plugin / feature might be the culprit, print a pretty-printed description of the error in the console, can fix startup crashes / softlocks, random crashes etc. but it was only for BetterDiscord. I mean, it does work through bdCompat perfectly fine, but I just thought that an appropriate Powercord port could make it more optimized / fluent / faster, since it's targeted for this platform, while keeping the same set of features, if not more. It could also allow it to run without any library overhead. The link to the original repo of the plugin is [here.](https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/CrashRecovery)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This is planned as a core feature as I've described in [this issue on the main repo](https://github.com/powercord-org/powercord/issues/347), 3rd point
