### ISSUE TITLE
Artemis RGB plugin

### ISSUE THREAD

**Issue by milovincent** [powercord-community/suggestions#391]
### Description
The plugin would provide JSON data to Artemis RGB

### More info
It'd send data like whether the user is muted and what channel is active for use in lighting conditionals, basically anything accessible from the API, and be received by an equivalent plugin on the Artemis side. (Artemis is a unifying RGB software for gaming hardware)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
It is already possible to send discord information to Artemis. https://wiki.artemis-rgb.com/en/guides/user/plugins/discord

**Comment by milovincent** [comment]
you're right, whoops lol

**Comment by zt64** [comment]
If there's nothing else make sure to close this issue
