### ISSUE TITLE
Spotify Modal Background

### ISSUE THREAD

**Issue by leeprky** [powercord-community/suggestions#394]
### Description
Spotify Modal Changes With What Is Currently Playing in the avatar and displayed on the background instead like a fullscreen.

### More info
This Imgur Might Help: https://imgur.com/kPd8us5
I Recreated It In CSS

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Crenshaw1312** [comment]
I had the same idea just today, I'm working on a plugin to do this rn, I'm also adding game support.

**Comment by Crenshaw1312** [comment]
this is taking longer then I though bc it won't fetch the user area, the user modal works fine, just the popout is being a pain in the ass for no good reason >:(
