### ISSUE TITLE
Redirect embeds (eg YouTube) to privacy friendly alternatives (eg Invidious)

### ISSUE THREAD

**Issue by EmeraldSnorlax** [powercord-community/suggestions#396]
### Description
Similar to the features of https://github.com/SimonBrazell/privacy-redirect, but for embedded links (eg Twitter, YouTube previews, etc)

### More info
Poor mockup:
![invidious](https://user-images.githubusercontent.com/43452521/112316325-e89b1400-8ca2-11eb-9e60-df53edcbf03f.png)
![nitter](https://user-images.githubusercontent.com/43452521/112316329-e9cc4100-8ca2-11eb-9c39-3eec71dc8e7c.png)

Opening the link in browser should also open to an Invidious / Nitter / Bibliogram instance
Ideally, no (client) requests should go to Twitter / YouTube / Instagram

While Discord says that they don't allow your IP to hit websites, it looks like the YouTube / Twitter media embeds have your client hit the respective services directly for the video embeds, as it looks like just a normal iframe.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by TaiAurori** [comment]
https://github.com/TaiAurori/embed-redirect ight bet :ok_hand:
