### ISSUE TITLE
Automatic New Server Mute

### ISSUE THREAD

**Issue by MuseBamba** [powercord-community/suggestions#398]
### Description
A plugin that would mute any server the user joins (preferably permanently) to save the user's mouse 3 clicks. A mere convenience tool.

### More info
I don't think any more specific information is needed. I guess it'd be cool if it had options to choose if it also mutes @'s or not while doing this. I find a mere permamute sufficient.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by RazerMoon** [comment]
[Here you go](https://github.com/RazerMoon/muteNewGuild), feel free to @ me if there are any issues.
