### ISSUE TITLE
a plugin that changes your status on discord

### ISSUE THREAD

**Issue by gyarisuta** [powercord-community/suggestions#399]
### Description
it changes your discord status every 10 seconds

### More info
You go to the page of the plugin and there you put 10 status and then let the bot cycle through them

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This would be a violation of guideline 4
