### ISSUE TITLE
Access Discord's developer portal through Discord client

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#4]
**Describe the plugin**
A plugin to access Discord's developer portal through Discord client

**Expected behavior**
When running a command/clicking a button the  [Developer Portal](https://discordapp.com/developers) is opened in the Discord client.

>  i was thinking about adding it there - Bowser65#0001
![Bowser's idea](https://i.bowser65.xyz/ca11897830.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
OwO whats this https://github.com/powercord-community/inapp-devportal
