### ISSUE TITLE
Better Status Indicator

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#40]
### Description
I have included the SVG files for all of the mobile statuses, this includes online (default, idk why, live with it), idle, dnd, and streaming (because that's possible?). Basically instead of showing the normal status indicators while a user is on mobile, it shows the mobile one of said status color. I'm making this way more complicated than it needs to be just take [the files](https://drive.google.com/drive/folders/1JACF8vPbiAO8ibiZTQlWbhgckmgXYLjL?usp=sharing)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Note that these are just the default mobile indicator but recolored and with a `xmlns="http://www.w3.org/2000/svg"` I kept all of the classes and what not if that's important :^) they look wack so just making it clear that it literally is the default. Not resized or anything.

**Comment by Bowser65** [comment]
I'm claiming this owo

**Comment by ghostlydilemma** [comment]
OWO

**Comment by Bowser65** [comment]
Since I plan on also shipping other status-related features (such as new status like "Pingable dnd" w/ possible Better Friends integration, dnd but online and dnd but idle (and others if you can think about some), mind if I rename the issue "better status"? 👀

**Comment by CodingKanin** [comment]
Go for it, I love this idea.

**Comment by Bowser65** [comment]
I don't have the time nor the motivation to work on this, and the very few lines of code I wrote ages ago aren't even working anymore

**Comment by theGordHoard** [comment]
This plugin has been created by @GriefMoDz and can be found here: https://github.com/griefmodz/better-status-indicators
