### ISSUE TITLE
Plugin to view channel permissions.

### ISSUE THREAD

**Issue by xPolar** [powercord-community/suggestions#402]
### Description
Allow users to view the channel permissions of channels they're able to see.

### More info
This would allow users to view who can and can't view channel, what permissions each user / role has for each channel.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by sitiom** [comment]
Maybe a port of [PermissionsViewer](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/PermissionsViewer).

**Comment by D-Brox** [comment]
[There already is one tho.](https://github.com/powercord-community/permission-viewer)

Anyway, what xPolar meant is something on the channel list context menu that shows what roles have access to a channels you have access to.

**Comment by sitiom** [comment]
> [Theres already one tho.](https://github.com/powercord-community/permission-viewer)

PermissionsViewer also does that as well.

![image](https://user-images.githubusercontent.com/56180050/112739379-90b42400-8fa6-11eb-94f3-00eda5e9adca.png)

> Maybe a port of [PermissionsViewer](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/PermissionsViewer).

It might be a good idea to combine user permissions with channel permission and guild permissions into one, that's why I suggested it.
