### ISSUE TITLE
Adds all the aria-labels

### ISSUE THREAD

**Issue by doggybootsy** [powercord-community/suggestions#404]
### Description

Adds all the aria-labels for a element. So it would be easy to get them and not go through and do each language.

### More info

Adds the aria-labels for each language on one language. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ghost** [comment]
This would be very great

**Comment by cyyynthia** [comment]
I've briefly mentioned the idea in Powercord server a while back, but the main problem I've been thinking about is that there's a lot of aria-labels that rely in variable text (such as the [mute channel](https://user-images.githubusercontent.com/9999055/112757092-80249d80-8fe8-11eb-8f62-b45c95569cb5.png) one for example), which makes it not easy at all to work with.

If the code ends up being a massive pile of exceptions, I'd rather go the add classes and/or data attributes way, which would be easier to use and less likely to face issues like the one I mentioned.

I'd also advocate against doing it as a plugin and rather look into adding it to the core itself, as I've been trying to keep the classes and data attributes as neutral as possible so other mods like BD could take the same structure and it'd make for much better compatibility of themes between mods, without relying on third-party plugins.

**Comment by doggybootsy** [comment]
> I've briefly mentioned the idea in Powercord server a while back, but the main problem I've been thinking about is that there's a lot of aria-labels that rely in variable text (such as the [mute channel](https://user-images.githubusercontent.com/9999055/112757092-80249d80-8fe8-11eb-8f62-b45c95569cb5.png) one for example), which makes it not easy at all to work with.
> 
would there be like a way to have exceptions(like channels, users, etc)

**Comment by cyyynthia** [comment]
We then fall back to what I said in the 2nd paragraph, if it becomes just a bunch of exceptions, might as well use proper classes which are easier to use and are way better in terms of performances (and because of how React works there are most likely ways to have something generic for a lot of things)
