### ISSUE TITLE
Show how long I am connected in a voice channel

### ISSUE THREAD

**Issue by sitiom** [powercord-community/suggestions#405]
### Description
Something like this so I could keep track of time.

### More info
Would look something like this:
![image](https://user-images.githubusercontent.com/56180050/112739557-c3125100-8fa7-11eb-8fd5-c7256ac208f0.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by RazerMoon** [comment]
[Here you go](https://github.com/RazerMoon/vcTimer), feel free to @ me if there are any issues.

**Comment by sitiom** [comment]
@RazerMoon Thanks for doing this. However, time does not reset when switching to another channel. I have posted the issue on the repo.

**Comment by RazerMoon** [comment]
@sitiom fixed, check the issue for example
