### ISSUE TITLE
Hide unavailable emojis (e.g. no nitro)

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#407]
### Description
Get rid of or hide unavailable emojis. 

### More info
I think this might be possible using `hidden` but I'm not quite too sure.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This already exists as part of [Discord Tweaks](https://github.com/NurMarvin/discord-tweaks.git)
