### ISSUE TITLE
Server search/filter

### ISSUE THREAD

**Issue by Evo-c** [powercord-community/suggestions#41]
### Description
An icon or tooltip that once clicked shows a search box to filter servers. When searching for a server either filtering what servers are shown on the side or having it's own popout UI to display matching servers. Once you select the result from the filtered list it would wipe the search box and return to normal taking you to the server you have selected.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by theGordHoard** [comment]
This is possible with Discord's built in [Quick Switcher](https://support.discord.com/hc/en-us/articles/115000070311-Quick-Switcher-T-A-Y-N-E-). To use, press ctrl + k and begin your search with `*` to limit your search to guilds.
