### ISSUE TITLE
Port of BD's ChatAliases

### ISSUE THREAD

**Issue by salty-tuna** [powercord-community/suggestions#410]
### Description
A Powercord port of BetterDiscord's "ChatAliases by DevilBro".

### More info
Pretty much what the title says. I know that there is the core tags plugin, and an aliases plugin, but those both require starting the message with your powercord prefix, and they don't allow any other content in the message. 

ChatAliases allows you to set a list of aliases, and an autocomplete menu shows after typing a configurable amount of characters (by default 2). When you either press tab with an autocomplete suggestion open or click on the suggestion, it replaces the alias key with the alias value. It only replaces the key, and works anywhere in the message, which is the major difference between this and the plugins I mentioned earlier.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
Okay, but what exactly does that plugin do? Saying "port xyz" doesn't help if there's no explanation of what it does.

**Comment by salty-tuna** [comment]
@DracoClaw I've added more of a description, should I add more details or is what I have sufficient?

**Comment by cyyynthia** [comment]
> they don't allow any other content in the message

Tags include a syntax to use arguments within the tag contents (`$$@` to get everything, `$$n` where `n` is the `n`th word after the tag name)
![image](https://user-images.githubusercontent.com/9999055/117477844-c6153f80-af5e-11eb-9897-4690e363ed13.png)

**Comment by LandenStephenss** [comment]
this plugin works similarly. Might not be exactly what you are looking for but /shrug. https://github.com/LandenStephenss/PowerAliases
