### ISSUE TITLE
Auto push in push to talk

### ISSUE THREAD

**Issue by sitiom** [powercord-community/suggestions#411]
### Description
Automatically "push" whenever speaking in push to talk, essentially becoming like voice activity mode.

### More info
None.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
what would be the point of this? You can just set "Voice Activity" in Voice and Video.

**Comment by sitiom** [comment]
> what would be the point of this? You can just set "Voice Activity" in Voice and Video.

For push to talk voice channels. Perhaps Im lazy to push a button everytime I talk.

**Comment by E-boi** [comment]
> For push to talk voice channels. Perhaps Im lazy to push a button everytime I talk.

as I said before you can change push to talk to "Voice Activity" in Voice and Video, no button to talk.

**Comment by BenSegal855** [comment]
@E-boi Some VCs have there permissions set up to only allow push to talk.

**Comment by E-boi** [comment]
oh ya I forgot about that.

**Comment by cyyynthia** [comment]
I think this would fall under our guideline 3 as it is circumventing a permission set by server admins & mods.

**Comment by cyyynthia** [comment]
Closing as this would be in violation of our [guidelines](https://powercord.dev/guidelines).

**Comment by sitiom** [comment]
To those trying to find this feature, there is a BetterDiscord plugin for it: https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/DiscordBypass.plugin.js
