### ISSUE TITLE
Hide the footer when in an announcement channel

### ISSUE THREAD

**Issue by Aktimoose** [powercord-community/suggestions#414]
### Description
This css snippet/theme/plugin would simply get rid of the message at the bottom of announcement channels that says "Follow to get this channel's updates in your own server.".

### More info
Something similar to the css snippet by PoorPockets McNewHold#2546 (Snippet ID: 757138357888352287) that removes the chatbox when you are in a channel you can't talk in, but for announcement channels

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by akisblack** [comment]
This can easily be done in css with a display:none . I don't see the point of asking here. Maybe go to the themes channel in the powercord server and ask there?

**Comment by cyyynthia** [comment]
This can be done with simple css, there's not the need for a plugin here.
