### ISSUE TITLE
Markdown table image from message

### ISSUE THREAD

**Issue by Mara-Li** [powercord-community/suggestions#419]
### Description
As the latex plugin, parse the message from a command (like `table`) to create a table using Markdown syntax.
The plugin must send an image with a preview tab, like that : 
![image](https://user-images.githubusercontent.com/30244939/114532942-a6d00e80-9c4d-11eb-9766-cd67a11292be.png)

So first, we need to write a table with Markdown syntax, like that : 
```md
| Aime                 | Déteste              |
|:-------------------- |:-------------------- |
| Les grenouilles      | L'ordre              |
| L'argent             | L'état               |
| L'anarchie, le chaos | Les faibles          |
| Les jeux-vidéos      | Les cigarettes       |
| * * * *              | Dépenser de l'argent |
```

After, the message is replaced by an image, with the table preview. 

### More info
/

----

 - [ x] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
Would also be neat if the message included the original markdown by encoding it in zwc, and people with the plugin installed automatically see a functional themed/component version that you can copy from.

**Comment by MulverineX** [comment]
Can this be reopened? There is interest for this from others.

**Comment by Mara-Li** [comment]
Done ! Sorry, I close a lot of stale issue and forgot that this issue can interest future user.
