### ISSUE TITLE
Right-Click embeds

### ISSUE THREAD

**Issue by Benricheson101** [powercord-community/suggestions#42]
**Describe the feature request**
In Discord, you aren't able to right-click an embed to open the context menu with the delete button, pin button, etc.

**What Plugin would it be for?**
n/a

**Expected behavior**
Right-clicking inside or beside an embed would open the context menu so you don't have to click the 3 dots button.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This has been fixed in Discord vanilla
