### ISSUE TITLE
CharCounter port/alternative

### ISSUE THREAD

**Issue by GGORG0** [powercord-community/suggestions#420]
### Description
A character counter, port of [BD CharCounter](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/CharCounter/CharCounter.plugin.js) by DevilBro.

### More info
It shows you the number of characters you've typed in the message box and the Discord's message length limit.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by sitiom** [comment]
Duplicate of #140.
