### ISSUE TITLE
Quick mention button

### ISSUE THREAD

**Issue by pillarcat** [powercord-community/suggestions#423]
### Description
Adds a button to quickly mention a person 

### More info
![image](https://user-images.githubusercontent.com/61384886/115345644-c15b3800-a1b7-11eb-98aa-aebf5a6aad77.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
Not sure this is entirely needed - you can already quickly mention a user by shift clicking on their username (both in chat, the username in a reply, and in the member list). Right click > mention user also does the job pretty quickly, and unlike shift click it works to when right clicking a mention within a message. With how many methods are already available, is a button still a must have for you?

**Comment by pillarcat** [comment]
_Firstly I didn't even know you can just shift click a persons name to mention them, thanks i guess_
And I'm pretty sure most people don't too.
to me a button would just be another method that doesn't need looking trough the context menu or using the keyboard

**Comment by Swishilicous** [comment]
I know I'm not allowed to publish plugins due to my ban but if anyone wants to fork this you're welcome to.

https://github.com/Swishilicous/quick-mention
 
~~also yeah this plugin's still useless I don't see what's so hard about shift clicking someone's name~~

**Comment by fluzzeon** [comment]
I'll go ahead and fork that code from Swishillicous and update it whenever it has errors.

**Comment by MulverineX** [comment]
They published it ^^ [GitHub](https://github.com/Killerjet101/quick-mention), [Discord](https://discord.com/channels/538759280057122817/755005584322854972/841714789028855868).
