### ISSUE TITLE
DnD Invisible

### ISSUE THREAD

**Issue by ghostlydilemma** [powercord-community/suggestions#43]
**Describe the plugin**
Do not disturb for the invis mode, or any other mode as a toggle switch.

**Expected behavior**
Either add new status or add a toggle switch to mute any incoming message

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
Related to https://github.com/powercord-community/suggestions/issues/40#issuecomment-554619054

**Comment by CodingKanin** [comment]
> 
> 
> Related to [#40 (comment)](https://github.com/powercord-community/suggestions/issues/40#issuecomment-554619054)

It is related though the toggle switch seems intriguing and might make your life with that plugin much easier. Should we consider them the same plugin or mark this as up for grabs?

**Comment by Bowser65** [comment]
Well tbh implementation wise nothing changes much, it's about as easy as adding a bunch of elements, and i'll probably implement it this way in my plugin (because i don't have ideas of what icon you could use if you do all inputs xd)

**Comment by CodingKanin** [comment]
Sounds good, closing.
