### ISSUE TITLE
Search option but for multiple servers/DMs at once

### ISSUE THREAD

**Issue by voidplayer212121** [powercord-community/suggestions#430]
### Description
 A plugin that search keywords and the result would bring up multiple selected servers at once with specific keyword instead of 1 server that you searched in.

### More info
Tabs to choose between DMs and servers would be nice and blacklist/whitelist feature would be nice too.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
This could probably get integrated into #156 if the premise is acceptable. However it's somewhat problematic because it involves multiple automated search requests. Perhaps if interaction is required for each one, kind of like how it runs the search request when you change parameters.

**Comment by cyyynthia** [comment]
This would generate a lot of requests in burst, which falls as selfbotting which is not allowed as per our [guidelines](https://powercord.dev/guidelines).
