### ISSUE TITLE
Undo the new discord ping look

### ISSUE THREAD

**Issue by wizar-d** [powercord-community/suggestions#437]
### Description
ok so like the awful change to pinging that discord made last night, undo it.

### More info
it looks so bad......

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This can be done using a simple theme, you're better off asking in our Discord server, in the themes channel. Someone may already have the piece of css you're looking for.

Additionally, please watch your language next time.
