### ISSUE TITLE
DM Nicknames (Client-sided)

### ISSUE THREAD

**Issue by Heart-Artistic** [powercord-community/suggestions#438]
### Description
Just like nicknames for servers, except its in DMS, and client sided

### More info
Could also be used for naming friends which use fake names as usernames

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
there is a experiment that does this
![image](https://user-images.githubusercontent.com/54505527/117716934-28ad4c00-b1a8-11eb-861f-a2533d1cb856.png)

**Comment by Heart-Artistic** [comment]
yeah but thats only for friends, and i mean this for everyone, including non friends

**Comment by cyyynthia** [comment]
I have the feeling you're looking for https://github.com/Oocrop/local-nicknames

**Comment by Heart-Artistic** [comment]
yep, thanks alot
