### ISSUE TITLE
Remove all reactions button

### ISSUE THREAD

**Issue by fluzzeon** [powercord-community/suggestions#439]
### Description
Add "remove all reaction" buttons near the "reaction" button on the drop-down menu. Kind of like how mobile is.

### More info
I have seen on mobile where there is remove all reaction button on the drop-down menu for a message. I thought it would kind of be useful for many people to have that rather than clicking an x many times just to do the same action.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
This is a native feature. Simply right click a reaction to remove all reactions.
![](https://i.imgur.com/vf1znoq.gif)
