### ISSUE TITLE
Time In command

### ISSUE THREAD

**Issue by NyxIsBad** [powercord-community/suggestions#440]
### Description
When command /timein [timezone], return the time in that timezone

### More info
Should accept both abbreviated timezones (i.e. JST, EST, EDT, GMT) and Coordinated Universal/GMT notation i.e. GMT+5 or UTC-5

Unsure how difficult this one is. Am aware that this is doable with plugins like the wolfram plugin, but was thinking that if a distinct plugin was made for it, it could do it much faster. 

Kind of a weird suggestion and *technically* already done by wolfram plugin (although that plugin technically does a lot). Checked if this is duping something but I might have missed one if there is one

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment]
this would be pretty simple to do with

`Date.toLocaleString(locale, { timeZone: "..." })` 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

**Comment by aenriii** [comment]
I did this, it allows you to select from a list of almost 350 timezones, with autocomplete!

repo: https://github.com/jdadonut/time-in-pc
