### ISSUE TITLE
Stupid-Proof Vision

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#441]
### Description
A plugin that reverts most of discord's stupid layout changes would be nice, such as getting turning these new reactions back to the old one

### More info
![image](https://user-images.githubusercontent.com/40442784/117897491-f0356d00-b290-11eb-9087-ac842cb55896.png)

----

 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by doggybootsy** [comment]
Css can easily do this. And there's a snippet already in the snippets channel

**Comment by ghost** [comment]
> Css can easily do this. And there's a snippet already in the snippets channel

yeah this was my first plugin request so sorry if idk much about how snippets and plugins work

**Comment by katlyn** [comment]
As was said, this would be the job of CSS - many snippets have already been created for a similar use.
