### ISSUE TITLE
Own Role Viewer

### ISSUE THREAD

**Issue by seeLelouch** [powercord-community/suggestions#443]
### Description
A quick way to see your roles on current server.

### More info
This is so you don't have to scroll for 2 minutes to see your current roles on big servers. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This would be covered by #400

**Comment by DracoClaw** [comment]
Also possibly it could be cover by this. https://github.com/NurMarvin/guild-profile/issues/14
