### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by SharkLava** [powercord-community/suggestions#444]
### Description
Change fonts(to something like iosevka)

### More info
A plugin to allow us to change the default discord font to some other local font.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by doggybootsy** [comment]
snippet: https://canary.discord.com/channels/538759280057122817/755005803303403570/827415027354435594

theres already css that does it

**Comment by SharkLava** [comment]
@doggybootsy oh thanks but I'm not sure what I'm supposed to do with the link. Maybe I don't have access to the channel you linked me to?

**Comment by Dziurwa14** [comment]
doggybootsy
 Simple font changer
 Use https://fonts.google.com/ (to be simple)
 

```/* font Import */
 @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
 /* Font change */
> ::-webkit-input-placeholder, body, button, input, select, textarea{
> font-family: 'Roboto', sans-serif;
}```
once you find the one you want add it, get the import and replace the other import, and change the font family


that's what message said it was on powercord server

**Comment by SharkLava** [comment]
@Dziurwa14 Thanks!
