### ISSUE TITLE
Stealthcord: Hide Powercord from view

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#446]
### Description
A plugin that hides Powercord from detection.

### More info
Basically, it makes the whole thing look like normal Discord. Nothing related to Powercord should appear, and to disable it, you should press a keybind. 

A use-case for this is when giving a screenshot to a moderator (to report someone) while having Comfy on. I just press they keybind, screenshot, then press they keybind again and paste the (vanilla-looking) screenshot to the DMs of a moderator to report someone. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

edits: fix formatting

**Comment by Vendicated** [comment]
already exists https://github.com/LandenStephenss/Panikk

**Comment by ghost** [comment]
oh wow ok (ty by the way)
