### ISSUE TITLE
Custom text -> emoji

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#45]
### Description
Allow users to create custom text to emoji things. For example when typing :) you get 🙂. I would like the ability to both toggle the defaults individually and to make custom ones, allowing for custom emotes and such. Settings should be rather simple.. applying a string to an emoji. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by LilSizzurp** [comment]
Done (pretty much, settings are pretty shit as of now).
https://github.com/LilSizzurp/powerfnr

**Comment by Bowser65** [comment]
Any updates? I didn't test the plugin myself but it looks like it's fulfilling this request. @LilSizzurp can you confirm as the plugin dev?

**Comment by CodingKanin** [comment]
iirc I didn't mark this as completed because it was pretty difficult to use and needed a bit of work. Technically fulfills the request though.

**Comment by CodingKanin** [comment]
Because the person who claimed this plugin has yet to actually make it meet the requirements stated in the original issue (in 9 months) im going to re-open this. Powerfnr may be great for some peoples needs and works well for what its made for but its really not what I initially requested.

**Comment by SheepCommander** [comment]
PowerAliases? https://github.com/LandenStephenss/PowerAliases
