### ISSUE TITLE
custom status indicators

### ISSUE THREAD

**Issue by chyzman** [powercord-community/suggestions#452]
### Description
Replace the little circle on bottom right of users with their custom status emoji

### More info
This might not even need a plugin it could just be a css snip but idk

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
You should consider requesting it as a feature of https://github.com/GriefMoDz/better-status-indicators which has already tons of enhancements to status indicators and have probably already the necessary codebase for this feature.
