### ISSUE TITLE
Turn everything off when screensharing or taking a screenshot

### ISSUE THREAD

**Issue by Marki-dev** [powercord-community/suggestions#453]
### Description
When you go to take a screenshot of the discord client, or when screeensharing, all plugins and themes would turn off 
### More info
Essentially would allow us to share public screen shots of our discord client, without having to worry about someone freaking out about how "modifying your client is against TOS" or something

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
https://github.com/LandenStephenss/Panikk
https://github.com/ezist/quick-toggler

**Comment by LandenStephenss** [comment]
Pro-tip, Panikk use's powercord's native `shutdown`/`startup` functions. you might just have to switch channel/guilds to rerender the changes.

**Comment by Marki-dev** [comment]
I have updated Panikk to auto-panikk when going live
