### ISSUE TITLE
Favorited Gif Restorer

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#457]
### Description
When you log out of discord, your gifs will be wiped and you will have to favorite them all over again, I am looking for a plugin that backs up these gifs so that when you log out and log back in to either your own account or an alt account you will have those gifs restored.

### More info
There is currently a manual way to do this which is described here: https://gist.github.com/Gladuin/b00228769f154cb4ed2fcb266698cab1
Additionally it would be cool if frequently used emojis could be saved aswell and even have gifs and frequent emojis were saved on different accounts so if one account has one set of favourited gifs another account will not restore the same ones and will have its own gifs.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NyxIsBad** [comment]
This can be closed, dupe of 252

252 can also be closed
https://github.com/VenPlugs/PersistFavourites

**Comment by ghost** [comment]
Thanks
