### ISSUE TITLE
[p]math command

### ISSUE THREAD

**Issue by Hyperion-Dev** [powercord-community/suggestions#46]
**Describe the plugin**
A way to do basic math functions (+ , - , * , / , ^) with a Powercord command.

**Expected behavior**
[p]math [number1] [operation] [number2]
Number1 would be [operation] to Number2
```
Operations:
+ = Adds numbers obviously
- = Subtracts obviously
* = Multiplies obviously
/ = Divides... obviously
^ = Brings [number1] to power of [number2]
```
This plugin would be useful for the people that need it, without having to open a calculator, go to Google, or actually get a calculator for some simple math. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
It would be cool for it to act as an actual calculator though, not just `x does this to y` though any form of calculator would be helpful.

**Comment by LilSizzurp** [comment]
https://github.com/LilSizzurp/pc-calc/ (v1)

**Comment by Bowser65** [comment]
Henlo pc- prefix is strictly reserved for internal plugins

**Comment by LilSizzurp** [comment]
> Henlo pc- prefix is strictly reserved for internal plugins

Ok

**Comment by LilSizzurp** [comment]
> Henlo pc- prefix is strictly reserved for internal plugins

Renamed to "powercalc"

**Comment by Hyperion-Dev** [comment]
For those that may still see this, see https://github.com/LilSizzurp/powercalc thanks

**Comment by NurMarvin** [comment]
> 
> 
> Henlo pc- prefix is strictly reserved for internal plugins

henlo, please stop bullying people, thanks

**Comment by ghostlydilemma** [comment]
henlo this isnt bullying that is just upholding rules uwu
