### ISSUE TITLE
Powercord-omg-lol

### ISSUE THREAD

**Issue by ThijsNameIsTaken** [powercord-community/suggestions#460]
### Description
https://github.com/Penguin-Spy/powercord-ppl-moe This plugin, but for omg.lol instead.

### More info
Plugin adds a tab to the user profile named "omg.lol", when clicked it requests profile data from the user's omg.lol page if the web profile is enabled in the omg.lol settings.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
Perhaps I'm missing something, but it doesn't seem that there's a way to get someone's omg.lol page from their Discord account. Unless there is and I just didn't find it, this plugin won't be possible.
