### ISSUE TITLE
Voice Change Plugin

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#464]
### Description
A Plugin to voice change on a Discord Call

### More info
To make my voice funny, loud or deep.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by onixiya1337** [comment]
Just use external software made for this.

**Comment by MulverineX** [comment]
@onixiya1337 a lot of those suck and/or are paid

**Comment by katlyn** [comment]
Duplicate of #195
