### ISSUE TITLE
Add a lyrics button to the spotify controls

### ISSUE THREAD

**Issue by mr-miner1** [powercord-community/suggestions#465]
### Description
this could just be a button that takes you to link (genius.com is a good lyrics site) or maybe it uses the "only you can see this message" thing the one powercord commands and clyde uses or you could do something completely different

### More info
not sure if it would work but you could genius sorts lyrics like: genius.com/[artistname]-[songname]-"lyrics" example: **https://genius.com/Juice-wrld-righteous-lyrics** .i guess you could say why not just use spotify's lyric command; ik this is only a small portion of the community but it would be useful since genius has a larger list of lyrics and would work with local files and would be a cool feature in general

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
There is already a plugin for lyrics of songs: https://github.com/powercord-community/lyrics
