### ISSUE TITLE
Possible Automessage

### ISSUE THREAD

**Issue by Lobituki** [powercord-community/suggestions#467]
### Description
Literally I just want to autosend a copypaste message and I don't know how to already do this..If it's possible.

### More info
I'm not entirely sure if this would break the fourth guideline, so if it does let me know.
Also I didn't x the second option because I'm not sure.
----

 - [x] I checked if this request wasn't already proposed
 - [ ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by jaydns** [comment]
this exists, you can create tags with the `<prefix>tag add <name>` command then use it like `<prefix><tag name>`

**Comment by Lobituki** [comment]
Where? In a CSS editor?
