### ISSUE TITLE
Auto sort serverlist

### ISSUE THREAD

**Issue by doge-uk** [powercord-community/suggestions#468]
### Description
Auto sorts the serverlist by how frequent or alphabetical order.

### More info
N/A

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by TheShadowGamer** [comment]
Isn’t that just this? https://github.com/sparr/powercord-guild-list-order-shortcuts

**Comment by doge-uk** [comment]
> Isn’t that just this? https://github.com/sparr/powercord-guild-list-order-shortcuts

when was that a thing
