### ISSUE TITLE
LaTeX renderer

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#47]
**Describe the plugin**
Make codeblocks using "latex" language (\`\`\`latex) actually render LaTeX

**Expected behavior**
Make this
![image](https://user-images.githubusercontent.com/9999055/69130869-339e8900-0aa9-11ea-97e0-d8e2cad62a22.png)
render like
![image](https://user-images.githubusercontent.com/9999055/69130922-4c0ea380-0aa9-11ea-9c09-e075957c09d0.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Vap0r1ze** [comment]
https://github.com/Vap0r1ze/codeblock-latex
