### ISSUE TITLE
PERMANATELY HIDE ALL BLOCKED MESSAGES

### ISSUE THREAD

**Issue by Sand-Turtle** [powercord-community/suggestions#471]
### Description
a plugin that will make it seem like blocked users do not even exist and deletes all blocked messages client side automatically

----

 - [X] I checked if this request wasn't already proposed
 - [X ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by TrevTV** [comment]
This can be done with css (snippet was originally posted by DoggyBootsy#1333)
```css
[class^="groupStart-"]{
  display:none;
}
```

**Comment by Sand-Turtle** [comment]
> This can be done with css (snippet was originally posted by DoggyBootsy#1333)
> 
> ```css
> [class^="groupStart-"]{
>   display:none;
> }
> ```

yeah but i'm requesting that it be done automatically.

**Comment by TrevTV** [comment]
What do you mean? If you were to add that to Powercord's Quick CSS it will be done automatically.

**Comment by Sand-Turtle** [comment]
> What do you mean? If you were to add that to Powercord's Quick CSS it will be done automatically.

ah didn't know, thank you
