### ISSUE TITLE
Sticker Suggestion Remover?

### ISSUE THREAD

**Issue by Deftu** [powercord-community/suggestions#479]
### Description
Simply removes stickers from emoji suggestions for nitro users.

### More info
N/A.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
![image](https://user-images.githubusercontent.com/45984786/132376835-b7e998ef-b932-4ca5-bc50-f22ac96be1ab.png)
Built-in setting
