### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#48]
### Description
Like #46 but ~~good~~ better. A command that acts as a real calculator. Solving equations and doing all of the advanced calculator stuff.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Currently being worked on by `theGordHoard#9607` whom I can't assign the issue to because he didn't comment on it 😠

**Comment by theGordHoard** [comment]
no u

**Comment by CodingKanin** [comment]
Oops wrong button

**Comment by Bowser65** [comment]
Might be interesting to have something similar to what [SpeedCrunch](https://bitbucket.org/heldercorreia/speedcrunch) does offer :eyes:

**Comment by Bowser65** [comment]
It's been 5 months since last update on this request, anything new? @theGordHoard still working on (or willing to work on) this request or I should mark it as up for grabs?

**Comment by CodingKanin** [comment]
@theGordHoard ^

**Comment by abUwUser** [comment]
i can make it using math.js lib

**Comment by CodingKanin** [comment]
A new request for Gord or if he drops the project whoever claims it, having #47 as an optional dependency, using it where possible.

**Comment by CodingKanin** [comment]
@theGordHoard I understand you're busy with other things right now, would you like me to mark this as up for grabs? Its been 9 months and you didn't respond to our last comment.

**Comment by theGordHoard** [comment]
That would be fine, sorry for lack of response. Whatever I had is long gone as I hadn't gotten a git repo set up for it, but it was something using math.js's `math.evaluate` function if I remember correctly. I had something set up with persistent scope or something for variables but if someone just wanted a simple calculator all they would need is that method.

**Comment by CodingKanin** [comment]
> That would be fine, sorry for lack of response. Whatever I had is long gone as I hadn't gotten a git repo set up for it, but it was something using math.js's `math.evaluate` function if I remember correctly. I had something set up with persistent scope or something for variables but if someone just wanted a simple calculator all they would need is that method.

This was meant to be a more elaborate calculator, scientific (as much as a calculator in Discord can be). No need to be sorry, I know you've been busy 🧡
