### ISSUE TITLE
Google Translate Utility

### ISSUE THREAD

**Issue by flerouwu** [powercord-community/suggestions#480]
### Description
A button that is located next to the text area (near emojis, gifs and such) that would open up a menu that sends messages in different languages after sending your message to google translate. This could also just be a powercord command.

### More info
Similar to [GoogleTranslateOption](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/GoogleTranslateOption), but a port to powercord would be perfect.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
It would help to actually look for existing plugins before making suggestions. https://github.com/cyyynthia/message-translate
