### ISSUE TITLE
Desktop Message Report Menu

### ISSUE THREAD

**Issue by Jupith** [powercord-community/suggestions#481]
### Description
Add a report button onto the right click menu of messages

### More info
Using the api/v9/report endpoint discord allows you to cache messages so they can be looked at by Trust and Safety even after the message has been deleted, mobile devices have this exact feature but its not been added to desktop and probably wont be anytime soon.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Jupith** [comment]
The desktop client has this menu for reporting messages (under very limited circumstances) the same menu could be used in the plugin.
![XP6iL2I](https://user-images.githubusercontent.com/51760248/121368396-f4f24d00-c932-11eb-8eb2-c0e6926b8280.png)

**Comment by cyyynthia** [comment]
Discord has an experiment for in-app reporting that is currently disabled. Interfering with how Trust and Safety handles reports is a bad idea and may be counter productive for them, as well as an additional risk of getting your account banned (as they know if the request comes from the android app or the desktop app). If they have it disabled they probably have their reasons.

Despite that experiment being disabled, when deleting messages as a moderator, Discord already shows a checkbox to perform a report that TnS will receive and look at.

![image](https://user-images.githubusercontent.com/9999055/121389054-4e1aaa80-c94c-11eb-96b4-22a6fed18c37.png)
