### ISSUE TITLE
Sticker Enabler

### ISSUE THREAD

**Issue by rollingmoai** [powercord-community/suggestions#482]
### Description
Enabling stickers on regions where it is not available.

### More info
Reopening from #406 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by doggybootsy** [comment]
Could use the built in experiment feature. 
then enable stickers from there.

**Comment by rollingmoai** [comment]
> Could use the built in experiment feature.
> then enable stickers from there.

Hmm. Seems to work now. I remember it wasn't working the last time I enabled it.
