### ISSUE TITLE
Show connections in a User Popout

### ISSUE THREAD

**Issue by rollingmoai** [powercord-community/suggestions#484]
### Description
Show connections in a User Popout
![screenshot](https://mwittrien.github.io/BetterDiscordAddons/Plugins/ShowConnections/_res/screenshot1.png)

### More info
Maybe a port of [ShowConnections](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ShowConnections).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
done: https://github.com/E-boi/ShowConnections
