### ISSUE TITLE
Search Messages by Deleted User

### ISSUE THREAD

**Issue by Qoes** [powercord-community/suggestions#485]
### Description
Plugin that allows us to search for messages by a deleted user. 

### More info
Normally if you search for a user using their username+discriminator or user id, you'd be able to look at just his/her messages. But if you use the username+discriminator for the deleted user on the search, you'd get this.
![image](https://user-images.githubusercontent.com/80235726/121752107-4d0c8900-cac4-11eb-8153-706ebb8c49bd.png)
And if you use the deleted user's id, you'd just see a list of everyone's messages.
Some of the deleted user's messages are still up since I have checked the oldest messages on the server. But I am unable to use the search to look at messages by only him. I think a plugin to fix this bug would be nice.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
This isn't possible for a plugin to do, as it is the API that filters out results from deleted users, and not the client.
