### ISSUE TITLE
Is it possible to have a plugin that doesn't even see the phrase 'n number of blocked messages'?

### ISSUE THREAD

**Issue by ranger9703** [powercord-community/suggestions#488]
### Description
I don't want to even see what the blocked person said.

### More info
NA

----

 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Doable with a single line of css.

```css
[class^="groupStart-"] { display:none; }
```
