### ISSUE TITLE
Better Server Tooltips

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#49]
**Describe the plugin**
Option to put various information about the server in the tooltip.

**Expected behavior**
Switches to add things like member counts, online memebers, boost count, possibly even vanity url if one exists. Etc. Right into the tooltip. Hopefully this would allow you to toggle the voice status as well.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Extra credit points for allowing us to fully customize how this info is formatted, sort of like the quote command using variables. Also extra credit for adding the option to see how many guilds are in a folder. Possibly more info in folder tooltip though I'm not sure what all applies here.

**Comment by Bowser65** [comment]
Since [Guild Profile](https://github.com/NurMarvin/guild-profile) exists this is considered as complete
