### ISSUE TITLE
RPC for Netflix Windows app?

### ISSUE THREAD

**Issue by Deftu** [powercord-community/suggestions#491]
### Description
A simple plugin that displays the current show, minute, second and hour from Netflix.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment]
Does the Netflix UWP app have a WebSocket API you can connect to in order to fetch media info? Native Media Session access was denied because it requires the use of native code which is unsustainable for this kind of project, so you can't go that route.

**Comment by Deftu** [comment]
> Does the Netflix UWP app have a WebSocket API you can connect to in order to fetch media info? Native Media Session access was denied because it requires the use of native code which is unsustainable for this kind of project, so you can't go that route.

I'm unsure and I don't really know where I can ask. I would think of asking the Microsoft Discord server but it'd be a "suspicious" question
