### ISSUE TITLE
Hide Blocked Users

### ISSUE THREAD

**Issue by isXander** [powercord-community/suggestions#492]
### Description
1. Remove the messages that have reply to a blocked message / remove the reply indicator (an option)
2. Remove the `1 blocked messages - click to expand` from the chat
3. Remove blocked users from the user list sidebar
4. Auto leave group chats you are added to with blocked users in (toggleable)

### More info
number 2 can be made in quick-css with
```css
[class^="groupStart-"]{
    display:none;
}
```
but it would be cool if it was built-in to this plugin

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Deftu** [comment]
Remove the spaces between the x and the square braces.
(Edit: there's also a spelling mistake in "ccs")

**Comment by cyyynthia** [comment]
The very reason we keep closing these request is because it's already doable WITHOUT a plugin. Whenever you can avoid plugins, the better it is for performance.

**Comment by isXander** [comment]
For ex there is no class for replies that quote a blocked user so that couldn't be done in css.
