### ISSUE TITLE
Hide Powercord related badges on your profile.

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#493]
### Description
If you don't want Powercord badges for example Bug Hunter you could hide it and nobody could see it and if you want to unhide it then there is an option obviously.

### More info
I don't think this is already in and I don't believe anyone has suggested it either. It isn't really really needed but I guess and extra feature if you want it. If it isn't possible then leave it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
If you don't want a badge on your profile, you have to reach out to staff.
