### ISSUE TITLE
Auto Punctuation

### ISSUE THREAD

**Issue by Neppkun** [powercord-community/suggestions#495]
### Description
A plugin that automatically punctuates and checks if the first character of the message is capitalized or not.

### More info
Details: The plugin checks if there's a punctuation mark at the end of the message (a dot, command, question mark etc.), if not it adds a dot. If the message has a punctuation mark at the end of it, plugin doesn't change the end.

If the sent message's first character is capitalized, it doesn't change it. If it's not capitalized, it capitalizes it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment]
A plugin like this already exists, although the author transferred to vizality and the powercord fork is no longer maintained. This should be very simple to port to powercord though
https://github.com/swishs-client-mod-plugins/grammar-nazi

**Comment by Vendicated** [comment]
done xD https://github.com/VenPlugs/grammar-nazi

**Comment by Neppkun** [comment]
> 
> 
> done xD https://github.com/VenPlugs/grammar-nazi

Thank you my friend <3 Appreciate it.
