### ISSUE TITLE
AccountSwitcher (Login Details Supported)

### ISSUE THREAD

**Issue by johnaqu1no** [powercord-community/suggestions#496]
### Description
A button on the top right corner that can switch accounts with just a press of 2 buttons

### More info
There is an account switcher button on the top right corner, when clicked it opens up a UI with all of the accounts added in User Settings.

You can add accounts in the User Settings by either using a token or login details 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This better suits as a feature request for [multitask](https://github.com/powercord-community/multitask)
