### ISSUE TITLE
Syntax Highlighting Plugin for GDScript

### ISSUE THREAD

**Issue by raincaliber** [powercord-community/suggestions#497]
### Description
The plugin would allow for syntax highlighting in code blocks to support GDScript, a Python-esque scripting language used in Godot Engine.

### More info
For whoever it may concern that might pick this up, [an implementation for GDScript in Highlight.JS already exists](https://github.com/highlightjs/highlightjs-gdscript).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This would better fit as a request for [vpc-shiki](https://github.com/Vap0r1ze/vpc-shiki)

**Comment by raincaliber** [comment]
> 
> 
> This would better fit as a request for [vpc-shiki](https://github.com/Vap0r1ze/vpc-shiki)

You're right, I've opened a PR for that [here](https://github.com/Vap0r1ze/vpc-shiki/pull/18).
