### ISSUE TITLE
Shift+Up last message

### ISSUE THREAD

**Issue by ShadowS132** [powercord-community/suggestions#499]
### Description
Pressing shift+up copies the last message and puts it in the message box like cmd

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment]
https://github.com/1XC1XC/ArrowDownForLastMessage/

**Comment by ShadowS132** [comment]
thanks!
