### ISSUE TITLE
Sort Powercord settings

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#5]
**Describe the plugin**
A plugin that sorts the list of Powercord plugins alphabetically and/or lets you rearrange the tabs by dragging and dropping them. Possibly letting you hide tabs as well.

**Expected behavior**
Pretty well explained in the description, here's a screenshot of the settings for reference:
![Settings](https://user-images.githubusercontent.com/29491781/67531972-a70fcf00-f692-11e9-9e24-0e659cda26a5.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
__**/resolved**__

This suggestion is no longer up for grabs and should be marked as 'Completed'. You can find a direct link to the plug-in repository below.

Direct link: [GriefMoDz/manageable-powercord-settings](https://github.com/griefmodz/manageable-powercord-settings) 🎉
