### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by ShadowS132** [powercord-community/suggestions#503]
### Description
Added functionality of search reactions from particular user or in a particular channel.
### More info
If someone wants to find where the reaction :cat: has been used they can do this with the plugin.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
There are tons of things that are limited because of Discord's API, and your example typically falls into that. It's not possible to search for messages that way.
