### ISSUE TITLE
Slowmode Counter

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#504]
### Description
When you have Manage Message perms you bypass Slowmode, which is great, but it would be still nice to know how long would be left on the slowmode.

### More info
Sometimes its helpful to know the slowmode time, if you want to blend in, if you are trying to time something specifically. This should have the countdown show up even if you are immune, and then if you send a message before the time would be up, the countdown starts again.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by yousetoffmytrap** [comment]
neat

**Comment by 12944qwerty** [comment]
https://github.com/12944qwerty/Slowmode-Counter
