### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by ShadowS132** [powercord-community/suggestions#506]
### Description
A plugin that adds more search features

### More info
We can search for messages in a particular channel, from a certain user or mentions a user but it would be nice to be able to search for messages that do not mention the user, not in the channel, not from a certain user.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment]
that's not possible, since the search results are provided by the discord api. You should request it on https://feedback.discord.com

**Comment by katlyn** [comment]
As ven already mentioned, what can be done is fairly limited as the results are filtered and provided through the API. That said, #156 already covers what's able to be done with clever parameter manipulation.
