### ISSUE TITLE
Add time picker for discord's new time/date message component

### ISSUE THREAD

**Issue by BobbyTheCatfish** [powercord-community/suggestions#507]
### Description
Discord recently added a feature that lets you add a time/date component to a message by typing `<t:{enoch time code}:{timecode length}>`, but there isn't an easy way to use it. I think a time/date picker in the message bar that inserts the format into the message bar would be a really nice feature and a lot better than just typing it out.

### More info
format:
<t:1624855717>       short date time:    June 27, 2021 9:48 PM
<t:1624855717:f>     short date time     June 27, 2021 9:48 PM
<t:1624855717:F>    long date time:      Sunday, June 27, 2021 9:48 PM
<t:1624855717:d>    short date:             06/27/2021
<t:1624855717:D>    long date:              June 27, 2021
<t:1624855717:t>     short time:             9:48 PM
<t:1624855717:T>    long time:               9:48:37 PM
<t:1624855717:R>    relative time:          2 days ago

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment]
for now there's a tool that does this https://datetimecord.rauf.wtf

I feel like discord might implement this themselves sooner or later

**Comment by 12944qwerty** [comment]
Heyo, I just completed this: https://github.com/12944qwerty/send-timestamps

There is both a command {prefix}timestamp and a button in the message bar. Both open a modal that will do everything.
Bugs: Doesn't autofill the format and time for some reason. Button is slightly larger than normal.
To-Do: Make a preview

**Comment by AiezeL** [comment]
make a plugin i can copy banner photo

**Comment by BenSegal855** [comment]
> make a plugin i can copy banner photo

@AiezeL you can make a request by opening a new issue on this repository. Not by commenting on a completed request.
