### ISSUE TITLE
BetterVolume

### ISSUE THREAD

**Issue by krzychox** [powercord-community/suggestions#508]
### Description
BetterVolume port for Powercord

### More info
There is a plugin for BetterDiscord which lets you type someone's volume but doesn't work with Powercord. Sometimes it's annoying when you use the bar thing and it sets the volume to 101% instead of 100 especially with Custom Volume Range plugin. Also with this plugin changing volume could be faster.
![image](https://user-images.githubusercontent.com/38294500/124179922-bffd9400-dab3-11eb-9c5a-fa18be6f4327.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by doggybootsy** [comment]
This https://github.com/PandaDriver156/Custom-Volume-Range ?

**Comment by krzychox** [comment]
> This https://github.com/PandaDriver156/Custom-Volume-Range ?

Nope. It's this: https://betterdiscord.app/plugin/BetterVolume

**Comment by doggybootsy** [comment]
I misread what the I sent does.

**Comment by DracoClaw** [comment]
Per the opened issue on that repo, it's a requested feature. https://github.com/PandaDriver156/Custom-Volume-Range/issues/1. And according to the PC guidelines, it's better to pr a plugin than to make a new one with similar features.

**Comment by krzychox** [comment]
> Per the opened issue on that repo, it's a requested feature. [PandaDriver156/Custom-Volume-Range#1](https://github.com/PandaDriver156/Custom-Volume-Range/issues/1). And according to the PC guidelines, it's better to pr a plugin than to make a new one with similar features.

Oh, didn't see that when looking for similar requests. Thank you

**Comment by RDP8** [comment]
So if this was completed, where is the plugin for powercord with this feature?
