### ISSUE TITLE
Mark as read button

### ISSUE THREAD

**Issue by Sialss** [powercord-community/suggestions#509]
### Description
A button to read all

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
As in issues #148, #169, and #279 this is a native feature.
![](https://cdn.discordapp.com/attachments/398575198573428737/860284231346159636/unknown.png)
