### ISSUE TITLE
Plugin to fix back button issue on Linux Clients

### ISSUE THREAD

**Issue by TheStachelfisch** [powercord-community/suggestions#512]
### Description
A simple plugin which fixes the back button going back twice on Linux clients.

This issue was already reported to Discord many years ago, but unfortunately Discord doesn't care about their Linux client.

### More info
It's really simple to fix, but unfortunately I don't know a lot about Javascript. It's as simple as, just removing the `DISCORD_NAVIGATE_BACK` event.

I found a code snippet in the Powercord Discord which supposedly does this already
```js
require('electron').ipcRenderer.removeListener('DISCORD_NAVIGATE_BACK', require('electron').ipcRenderer._events.DISCORD_NAVIGATE_BACK)
```

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by aenriii** [comment]
i went ahead and made this since it's only like one line (it should work, but there's no uninjection yet)

https://github.com/jdadonut/no-double-back-pc

**Comment by TheStachelfisch** [comment]
Thank you very much. This works perfectly. 
I'll create an issue on the Repo, if any issues occur.
