### ISSUE TITLE
Pin DMS

### ISSUE THREAD

**Issue by niksey07** [powercord-community/suggestions#517]
### Description
Basically lets you make new categories where you can Pin DMs/GRoup Chats
Like this: https://i.imgur.com/5kYk8F3.png

### More info
Theres a version of this in BetterDiscord, but when using it with bdcompat its very buggy

----

 - [ ] I checked if this request wasn't already proposed
 - [ ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Duplicate of #209
