### ISSUE TITLE
"Join call" option for community moderation

### ISSUE THREAD

**Issue by Rannizord** [powercord-community/suggestions#52]
• For communities with many members and many active voice channels, a plug-in would allow the team to directly join the user's voice channel, preventing the moderator from searching for the user or moving around to avoid being found.

• The "Join Call" option would be possible for moderators to go straight to where the user in question is, so watching more quickly what they are up to or what rule they are violating would save a lot more time than searching for crowded rooms.

![Screenshot_2](https://user-images.githubusercontent.com/39033999/70838812-c3093480-1de8-11ea-8317-054a19fdb8a8.png)

**Comment by Bowser65** [comment]
Landed here https://github.com/TodFoxBR/powercord-join-the-call 🎉
