### ISSUE TITLE
Powercord reminders

### ISSUE THREAD

**Issue by creativforce** [powercord-community/suggestions#521]
### Description
Plugin that allows you to create reminders and reminds you of such reminders, for us who don't use reminder applications and spend too much time on discord.

### More info
Using the command prefix, you can use `remindme` followed by a date in `MM/DD/YY` and time in `HH:MM` using the system timezone (can be changed under its settings), which is then followed by `text` to indicate the reminder.
 
When the time of the reminder comes, the user receives a notification on the channel or on DMs with the time, date, and reason set previously.

You can also use `viewreminders` to view a list of the reminders, with possibly a setting to see the time until the reminder goes off (?)

Using `editreminder` you can edit a reminder, meanwhile `delreminder` deletes it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
https://github.com/Killerjet101/remind-me

**Comment by creativforce** [comment]
> https://github.com/Killerjet101/remind-me

Ah, looks like I didn't search further, thanks!
