### ISSUE TITLE
Select voice, stage, and store channels with # in addition to text

### ISSUE THREAD

**Issue by burritosoftware** [powercord-community/suggestions#522]
### Description
This plugin will allow you to select voice, stage, and store channels in addition to text channels using the # symbol in the chat bar.

### More info
Discord has recently added support for these channels in messages: copying the ID and then placing it like this: `<#channelid>`  
When clicked, they make you join the voice/stage channel or view the store channel, and they have their own icon too.

I'd like to see a plugin that adds this to the # menu so manually copying the ID and pasting it in isn't a hassle.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vexed01** [comment]
You can easily mention them by typing `#!` - this brings up an auto-complete menu for voice channels.
