### ISSUE TITLE
Discord Markdown in Notes

### ISSUE THREAD

**Issue by Snapperito** [powercord-community/suggestions#525]
### Description
the plugin would allow you to add notes to people using markdown, like discord's new about me feature,,, but in notes

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by GriefMoDz** [comment]
I'll be closing this request as I've featured this within my new plug-in "Notey" which you can find [here](https://github.com/GriefMoDz/notey). If you have any suggestions that can help me improve this functionality, please let me know as I'd love to hear them.
