### ISSUE TITLE
Disable Reply Ping

### ISSUE THREAD

**Issue by Slowftw** [powercord-community/suggestions#527]
### Description
Deselect reply mentions by default, but you can enable it if needed.

### More info
https://www.reddit.com/r/discordapp/comments/ok4xhi/anyone_else_spend_so_much_time_telling_people_how/

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Already exists: https://github.com/cyyynthia/better-replies
