### ISSUE TITLE
jo!#9211's Scalable Discord plugin, but with all menus rescaled (if possible)

### ISSUE THREAD

**Issue by GoldenFurredFox** [powercord-community/suggestions#528]
### Description
The settings menu doesn't properly scale with this plugin, so you literally cannot close the menu unless you go to your appearance settings and scale down the zoom.

### More info
From what I've seen of CSS coding, I'd imagine it's possible to edit the settings pane as much as any other window. All I'm requesting is that the panels of the settings pages (not the page tabs) get shrunken in width to match the client and leave room for the X button in the corner.
Source: https://github.com/j0lol/Scalable-Discord

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by EmeraldSnorlax** [comment]
@j0lol

oh, and this might be better suited as an issue in their repo

**Comment by cyyynthia** [comment]
This is better suited as an issue on their repository rather than a plugin request here.

**Comment by j0lol** [comment]
hi! it's possible to close the settings window with the escape key! i ended up giving up trying to move it, but I can try again i guess
