### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#53]
### Description
Set reminders for a specific time, and get notified of them when that time comes.

### More info
It'd be nice for it to be able to parse the time in many ways, ex:
`.remindme 1d1h Do this` allow `y, m, w, d, h, m, s`
`.remindme tomorrow at 11 to do this` allow actual strings

`.reminders` View reminders
`.delreminder` Delete a reminder

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by SomeAspy** [comment]
not mine, but we have that. https://github.com/Controlfreak707/remind-me
