### ISSUE TITLE
Hide guild list when in streamer mode

### ISSUE THREAD

**Issue by EmeraldSnorlax** [powercord-community/suggestions#530]
### Description
A way to hide or blur the guild list when in streamer mode

### More info
When entering streamer mode (or maybe a toggle, too), the guild list blurs the icons to hide what guilds you are in

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Syncxv** [comment]
https://github.com/Syncxv/hide-server-on-streamer-mode
if you want changes to it message me on discord 
Aria#8171
