### ISSUE TITLE
Auto No Mention in Replies

### ISSUE THREAD

**Issue by kritishd8** [powercord-community/suggestions#532]
### Description
A simple plugin that will automatically disable mentioning when replying to someone.

### More info
A simple plugin that will automatically disable mentioning when replying to someone.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Already exists: https://github.com/cyyynthia/better-replies
