### ISSUE TITLE
Edit Server Avatars Locally

### ISSUE THREAD

**Issue by 0ethereal** [powercord-community/suggestions#533]
### Description
A plugin that lets you change a Server's avatar locally via right click in the context menu.

### More info
There's already a plugin similar to this, but it only applies to user nicknames, so you can change people's names. I think this is a fitting request for a plugin.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
This would be better suited as a request to [local-nicknames](https://github.com/Oocrop/local-nicknames), with a request to add the ability to change pfp and icons for both users and guilds.
