### ISSUE TITLE
an inbuilt vpn

### ISSUE THREAD

**Issue by kritishd8** [powercord-community/suggestions#536]
### Description
Would love to have a vpn inbuilt to discord.

### More info
VPN can be useful within discord 🤷, Obviously doesnt need alot of locations or anything but just like how browsers have maybe that can happen straight in discord? it can help people who live in countries that get discord updates late, like me.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
There is no such thing as "late updates" in Discord, at least in the technical sense of it. What you probably mean is regional *rollouts*, which can be bypassed by enabling experiments manually.

It is also too low-level for plugins to do. You're better off using a system-wide VPN, or playing with [Electron's http proxy-server command line arguments](https://www.electronjs.org/docs/latest/api/command-line-switches/#--proxy-serveraddressport)
