### ISSUE TITLE
Disable media keys

### ISSUE THREAD

**Issue by slopslug** [powercord-community/suggestions#537]
### Description
A media keys disabler plugin similar to the one that recently got built into BetterDiscord (couldn't find a link to the plugin, would've included sorry)

### More info
Disables discord from using the media keys overlay on windows, (don't know about Linux nor mac)... That's it.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This is not something doable at plugin level. An issue [already exists](https://github.com/powercord-org/powercord/issues/425) on the Powercord repository that would allow disabling these.
