### ISSUE TITLE
Creation Date in Profile

### ISSUE THREAD

**Issue by MadamJazzy** [powercord-community/suggestions#54]
**Describe the plugin**
This plugin would add the date and time (in local time) that the user created their discord account. 

**Expected behavior**
Clicking on a user will show their account creation date and time under their avatar and name#discrim. Above roles in the profile pop out. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by MadamJazzy** [comment]
Example of this plugin coded for Betterdiscord is here https://betterdiscordlibrary.com/plugins/Creation%20Date

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
done, https://github.com/Juby210/user-details
