### ISSUE TITLE
LocalUserEditor

### ISSUE THREAD

**Issue by UrkiMimi** [powercord-community/suggestions#540]
### Description
Allows you to change the user settings on another user locally on your hard drive.

### More info
https://betterdiscord.app/plugin/EditUsers
I basically want this better discord plugin ported but with a few minor changes
You cannot add Discord badges to a user like the Nitro badge or a Discord staff badge.
You also cannot add your own tags like Bot tags.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
This would be better suited as a request to [local-nicknames](https://github.com/Oocrop/local-nicknames), with a request to add the ability to change the requested options.
