### ISSUE TITLE
ppl.moe Plugin

### ISSUE THREAD

**Issue by halsiz** [powercord-community/suggestions#541]
### Description
ppl.moe Plugin for discord profiles

### More info
Think like pronoundb will appear in profile and we will get users' ppl.moe profiles quicker.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
https://github.com/Penguin-Spy/powercord-ppl-moe
