### ISSUE TITLE
Functional Animated PNGs

### ISSUE THREAD

**Issue by hairyfred** [powercord-community/suggestions#544]
### Description
Discord does not currently animate animated pngs in chats
Even though they support stickers that are apngs being animated

### More info
Add functionality for apngs to be animated
Its irritating that stickers work but posting an apng does not (sticker submission channels for example)

----

 - [x ] I checked if this request wasn't already proposed
 - [x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by tacohitbox** [comment]
i am BEGGING for someone to make this

**Comment by pauleks** [comment]
Made it! https://github.com/TheOnlyGhostwolf/stinky-media

**Comment by hairyfred** [comment]
Epic
