### ISSUE TITLE
Copy banner URL

### ISSUE THREAD

**Issue by rollingmoai** [powercord-community/suggestions#546]
### Description
Add a "Copy Banner URL" button to the user context menu

### More info
If there is [Copy Avatar URL](https://github.com/21Joakim/copy-avatar-url), then there should be a copy banner URL plugin.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by LandenStephenss** [comment]
how about instead of making a whole new plugin, why not go add it to the existing one.

**Comment by katlyn** [comment]
As stated, this would be better suited as a request to [copy-avatar-url](https://github.com/21Joakim/copy-avatar-url).
