### ISSUE TITLE
Disable Discord's Auto Update

### ISSUE THREAD

**Issue by ShadowElixir** [powercord-community/suggestions#547]
### Description
A plugin that would make discord stop auto-updating at startup (I didin't mean windows startup, obviously)

### More info
A plugin that would make discord stop auto-updating at startup (there is nothing another then that to say)

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Plugins can't interfere with the startup routine of Discord. It's also very much not recommended to keep your Discord installation out of date. There are ways to do it, but **I severely discourage you from doing so as you may lower the security of the client, and introduce unexpected behavior**. You should also keep in mind this only disables updates to the client which represents a very tiny fraction of the updates done to Discord. The rest of the updates are not easily preventable and also cannot be prevented at a plugin level.

If you really want to disable startup updates, you have a `settings.json` file somewhere in your Discord installation. In this file, set the `SKIP_HOST_UPDATE` and `SKIP_MODULE_UPDATE` properties to `true`.
