### ISSUE TITLE
Vim for Discord

### ISSUE THREAD

**Issue by sinarck** [powercord-community/suggestions#548]
### Description
Vim emulator for Discord, completely useless but funny and maybe, just maybe, useful for the right audience.
### More info
So I have no idea if this is even possible, but I assume someone has the brains to make it work. Not making Discord a text editor, however- more like vim functionality instead of a full-on replacement for it

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
A similar request, #432, outlined similar functionality. However, it was closed in favor of #116 which is a plugin calling for an all around improvement of Discord's keybind system.
