### ISSUE TITLE
Last Message Sent

### ISSUE THREAD

**Issue by MadamJazzy** [powercord-community/suggestions#55]
**Describe the plugin**
This plugin would show the date and time the user last sent a message in the server where the username was clicked. 

**Expected behavior**
Much like the creation date plugin suggested earlier, under the avatar and username in the profile popup would display the date and time of the users last message. Could possibly also be clickable where clicking on "Last message sent on <Date/Time>" would take you to the message itself. Just like clicking on any message link. (eg https://canary.discordapp.com/channels/538759280057122817/539443125727395858/656262518062186496)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by MadamJazzy** [comment]
Example of this plugin coded for BD is here https://betterdiscordlibrary.com/plugins/Last%20Message%20Date

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
done, https://github.com/Juby210/user-details
