### ISSUE TITLE
Some useful features for server owners.

### ISSUE THREAD

**Issue by kritishd8** [powercord-community/suggestions#550]
### Description
3 useful features for server owners and server makers.

### More info
Those features are:
1) Being able to copy the permissions config of one channel and paste it in the other channel (of any servers maybe).

2) Being able to select multiple roles in the roles section of the server and being able to perform a common action on all of them, like maybe deleting all of the selected roles at once and removing a permission from all those roles at once.

3) Being able to remove a permission from a role in every category and channel of the server at once. Like i want to remove the threads permission from the members role in every channel and category of the server, i should be able to do it in few easy steps.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by LandenStephenss** [comment]
I'm not sure how the permissions endpoint works (if it's one request for one permission/role or multiple), but if it's multiple then this might be spammy to the api

**Comment by kritishd8** [comment]
It doesnt have to be instant tho, it can take time and do it slowly itself.

**Comment by LandenStephenss** [comment]
i mean, yeah. but at that point it just sounds inconvenient (depending on the ratelimits for permissions), but i'd have to look

**Comment by kritishd8** [comment]
This feature is just to make things easier for server owners and doesn't need like a time limit. The plugin can do the task in maybe like 15mins or smth that isnt counted as spam in the api. And maybe the plugin displays the estimated time before all of it is done?
