### ISSUE TITLE
Discord Button Create Command

### ISSUE THREAD

**Issue by svn-josh** [powercord-community/suggestions#551]
### Description
make a plugin where you can create a button in discord

### More info
like .createbutton red "text"

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
If, by "button in discord" you mean the interaction buttons that bots can create, this would not only violate our guidelines against selfbotting, but I'm not even sure that the api allows users to create buttons. If I have misinterpreted your request, please explain it a bit more clearly and I will reopen the issue.

**Comment by svn-josh** [comment]
Hello,

Yeah I mean the buttons from discord.
It is possible to create them from any type of discord account. Bot, user
or web hook.
And there comes my idea I know that self bots are against discord tos but
you could code it so that the buttons comes thought a webhook and than is
everything fine

Katlyn Lorimer ***@***.***> schrieb am Sa., 31. Juli 2021,
20:10:

**Comment by bennyscripts** [comment]
its not possible to create them on a user account
