### ISSUE TITLE
Add audio to linux screen shares.

### ISSUE THREAD

**Issue by 11robert11** [powercord-community/suggestions#557]
### Description
Add desktop audio to Linux screen shares.

### More info
Allows people running Linux to share audio with their screen shares, a feature that is absent in discord. It possibly has module you choose to load for different audio back-ends or sources. Maybe it require another plugin the interact with your audio back-end and give this plugin something to work with.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 11robert11** [comment]
BTW this is kinda similar to [MPRIS2 controller (like the Spotify one) + RPC client to share what I am listening to. #138](https://github.com/powercord-community/suggestions/issues/138)

**Comment by NovaMoon** [comment]
here are some current methods that make it possible but are rather tedious 
https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux

**Comment by cyyynthia** [comment]
Discord uses its in-house native module for audio capturing, which you can't inject into (well you theoretically can but good luck with that) making it not easily doable. The method linked above says that it doesn't apply to the Electron client.
