### ISSUE TITLE
Beta features for all

### ISSUE THREAD

**Issue by Armaan-Raisinghani** [powercord-community/suggestions#558]
### Description
A feature to get all beta features 

### More info
Not sure if it's possible, but it's kinda like Powercord Together by notsapinho, https://github.com/notsapinho/powercord-together but for all features, not just the together activities

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Settings > General Settings > Advanced > Enable experiments

There only exists a plugin for this specific feature as additional patchwork is needed compared to all others. Keep in mind, using some beta features (like Discord Activities) can be detected by Discord and may result in potential consequences on your account.
