### ISSUE TITLE
Please can we get a spotify listen along plugin for free spotify account

### ISSUE THREAD

**Issue by ChrisAust1n** [powercord-community/suggestions#559]
### Description
The plugin will allow a spotify free user to listen along with other discord members. Please

----

 - [ ] I checked if this request wasn't already proposed
 - [ ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
Plugins which provide paid features for free are against our guidelines.
