### ISSUE TITLE
Guild Relationships

### ISSUE THREAD

**Issue by MadamJazzy** [powercord-community/suggestions#56]
**Describe the plugin**
This plugin would allow you to see relationships from that guild. For example: Friends in this server, Blocked users in this server, users you share other servers with.

**Expected behavior**
Adds a context menu option when right clicking on a guild, "View Relationships". A pop up is displayed that shows Friends inside that server, Blocked users inside that server, and users that you share other servers with. 

A form of this plugin created for BetterDiscord can be found here. 
https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/ViewGuildRelationships.plugin.js

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by funlennysub** [comment]
I can try

**Comment by funlennysub** [comment]
https://github.com/funlennysub/guild-relationships
