### ISSUE TITLE
Show if user is banned in user profile

### ISSUE THREAD

**Issue by Vexed01** [powercord-community/suggestions#564]
### Description
Show a tag or other easily noticeable thing on the user profile (both pop-out and full thing).

### More info
This would be helpful if you share a different server with them, so cannot immediately tell they are not in the server you clicked their profile on.

Mock up for user popout:
![image](https://user-images.githubusercontent.com/51716387/129099238-acde6084-374f-4752-90f6-aaca79483db3.png)
You can tell I lack design skills :). Maybe a | between the discrim and BANNED or put it somewhere else, I really don't know.

Ideally this would update live, though I understand this would be harder than something which refreshes whenever the profile is re-opened so is not required.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by pythonmcpi** [comment]
Two major issues:
- The plugin would have to check *all* your servers to see if the user is banned in any one of them. This would spam the api.
- You need "Ban Members" permission to view the list of banned members in a server. Without the permission, you cannot tell if a user is banned or if they just aren't in a server.
