### ISSUE TITLE
Loop Video / sounds plugin

### ISSUE THREAD

**Issue by pawelk1337** [powercord-community/suggestions#568]
### Description
It will loop video / sounds

### More info
There is no info

----

 - [ x] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
Uh, where should it loop? How should it loop? What types of videos and sounds should it loop?
