### ISSUE TITLE
Guild and Friend Removal Notifications

### ISSUE THREAD

**Issue by MadamJazzy** [powercord-community/suggestions#57]
### Description
This plugin will show a notification when a friend or guild is no longer available to you. Either because the friend removed you or their account was deleted, the server was deleted, you were kicked, or banned from the server. 

A BD version of this suggested plugin can be found here, https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/GuildAndFriendRemovalAlerts.plugin.js

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
@Bowser65 I assume this is okay?

**Comment by Bowser65** [comment]
Nothing wrong here, that's actually some features I wanted as someone with 70+ servers lol

**Comment by SomeAspy** [comment]
Hellbound has a plugin that does this, I use it myself.
https://github.com/slow/relationships-notifier

**Comment by TheShadowGamer** [comment]
Non hellbound version: https://github.com/Twizzer/relationship-notifier

**Comment by cyyynthia** [comment]
Please refrain from linking software from people who allegedly used it to token-log staff members and all of the plugin users.
