### ISSUE TITLE
Copy Banner Photo

### ISSUE THREAD

**Issue by AiezeL** [powercord-community/suggestions#577]
### Description
Make a Plugin so that I can copy banner photo from accounts

### More info
Make a Plugin so that I can copy banner photo from accounts

----

 - [ ] I checked if this request wasn't already proposed
 - [ ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Duplicate of #546
