### ISSUE TITLE
Auto DM Reply

### ISSUE THREAD

**Issue by doge-uk** [powercord-community/suggestions#579]
### Description
Auto replys to dms when you are away or set it to
### More info
You could add rpc checking to say what the game title is so if you are playing a game.. (e.g minecraft) you could set some text to
```
Sorry, I will respond to your dm later as i am playing {GameName}
```

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This would be selfbotting which is not allowed as per our guidelines.
