### ISSUE TITLE
MessageLogger

### ISSUE THREAD

**Issue by NotRealWolf** [powercord-community/suggestions#581]
### Description
So on BetterDiscord there is a plugin called "Message Logger" and I was like WOW that is a cool plugin so why not ask if someone can make it for Pwercord cause why not and plus it would be really awesome to see if someone could make it more advanced than the BetterDiscord version?.

### More info
Like have it so if someone removes a message it keeps it in chat for you yk yk and also have it so you can change it to where if you wan a group chat to have the logger enabled or not and maybe something better if you can think of it?.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
You did not check if the request was already proposed (#341, #39, #367), and you did not read our plugin guidelines. This breaks guideline number 2 and will not be an accepted suggestion.
