### ISSUE TITLE
Auto scroll down

### ISSUE THREAD

**Issue by rizalvolz** [powercord-community/suggestions#588]
### Description
Hello sir, have u make a plugins like this.
I can push icon/button scroll down or etc. to auto scroll down in chat menu dm/server, for now i just manually scroll.

----

 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
Uh, isn't this already a discord feature?  A button will pop up when you scroll up enough.

**Comment by rizalvolz** [comment]
i think no sir, must be manually with scroll bar or mouse scrool/click button scroll then go down.

im in CreArts theme position

**Comment by cyyynthia** [comment]
You can Shift+PageDown when the "Jump to present" bar isn't present.
