### ISSUE TITLE
Fix Discord going over hidden taskbar

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#6]
### Description
A plugin which fixes the problem on windows where discord is over the windows taskbar(which is in hidden mode)
so i wont open upon going to the bottom with the mouse
\- JustMrRobBoss#1514

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by mrrobboss** [comment]
i found out when it happens:
it happens basically when youre snapping the window instead of using the maximize button

**Comment by Bowser65** [comment]
Is this bug still occurring or we can safely close this as "fixed by Discord"?

**Comment by funlennysub** [comment]
yes, i can reproduce it

**Comment by Bowser65** [comment]
Alright, I've searched a bit and found the Trello card related to this bug (categorized under Electron 6 bugs)

Here's the link for the reference: https://trello.com/c/wDnQ9mw7/4734-taskbar-cannot-be-accessed

**Comment by Bowser65** [comment]
Now that Discord upgraded electron to electron 9, is this still reproducible?

**Comment by mrrobboss** [comment]
Seems to be fixed now. Can't reproduce it the old way so I'll count it as fixed.

**Comment by Ser-Ames** [comment]
this happens to me a lot, seems to be a windows issue where it is layering apps over the taskbar. an easy solution to it is clicking the taskbar whenever an app is over it

**Comment by Xii-Nyth** [comment]
> i found out when it happens: it happens basically when youre snapping the window instead of using the maximize button

yeah thats a fatal flaw with any window in windows, that microsoft somehow cant fix. 
im here however because its happening with the button too
