### ISSUE TITLE
Copy Raw Embed

### ISSUE THREAD

**Issue by nexpid** [powercord-community/suggestions#615]
### Description
A plugin which allows you to copy an embed's raw JSON code.

### More info
Similiar to [Copy Raw Message](https://github.com/mic0ishere/copy-raw-message), but for embeds.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by pythonmcpi** [comment]
There's a BetterDiscord version of this plugin here: https://raw.githubusercontent.com/GR0SST/CopyRawEmbed/main/CopyRawEmbeds.plugin.js
It works when loaded via BdCompat, so for now you can use that.
It would be nice to have a powercord version though.

**Comment by nexpid** [comment]
Thanks! I'll use that.
But I agree, a powercord version would be better. I'll keep this issue opened for now

**Comment by katlyn** [comment]
[Juby210/view-raw](https://github.com/Juby210/view-raw) provides a similar functionality that would facilitate copying a raw embed.
