### ISSUE TITLE
Port: Artemis Lighting

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#618]
### Description
Port the Artemis lighting plugin from BD. https://github.com/AlpacaFur/Artemis.BDDiscord

### More info
When using the BD-Compat it crashes. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
Can you explain what it's supposed to do? Their github is poorly documented :(

**Comment by DracoClaw** [comment]
Yeah sure. It's quite similar to https://github.com/ADoesGit/Aurora-GSI-Powercord. It takes data from discord and sends it to the Artemis RGB app to be used with keyboard lighting. 

And no it can't be a pr to the Aurora one because they send data differently.

**Comment by DracoClaw** [comment]
Someone in the Artemis server has now made a port, it works as it should. Although it's not uploaded to GitHub as of now.
