### ISSUE TITLE
Better tray icon

### ISSUE THREAD

**Issue by GGORG0** [powercord-community/suggestions#621]
### Description
I use linux. And on linux you don't always get the fancy indicator on the taskbar like on Windows. So, let's use the tray icon instead.

### More info
Make the tray icon show the mention count too, like the taskbar badge, or show the dot only for mentions. Now, you just get this annoying, useless thing, which mostly doesn't change. 
![image](https://user-images.githubusercontent.com/51029895/137531590-5fcfc309-004c-46a8-9b03-342da6728c88.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Plugins don't have access to this and can't inject into it.
