### ISSUE TITLE
Linux Audio Screenshare

### ISSUE THREAD

**Issue by NovaMoon** [powercord-community/suggestions#622]
### Description
Enable Audio for Screensharing through linux

### More info
Screensharing with Audio on linux is a pretty big pain. it either requires you to pipe your audio through your mic which results in terrible quality and also a constant active microphone, or doing it through chrome which comes also with limitations as outlined here. https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ChrisJAllan** [comment]
Already at #557, might want to add that link over there

**Comment by NovaMoon** [comment]
i must've selectively skipped over that entry when i looked for existing entries
