### ISSUE TITLE
Server mutual friends

### ISSUE THREAD

**Issue by mwahaha9** [powercord-community/suggestions#624]
### Description
A clear and concise description of what the plugin would do.
Don't get too specific, that's for the next part.

Show friends in a server, basically mutual friends but for servers

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

similar to the mutual friends menu but shows friends of the user's who are in a server the user is also in. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NyxIsBad** [comment]
https://github.com/NurMarvin/guild-profile/
