### ISSUE TITLE
A port of StatusEverywhere plugin for betterdiscord 

### ISSUE THREAD

**Issue by websterwh** [powercord-community/suggestions#625]
### Description
Port the already available plugin from betterdiscord to Powercord

### More info
Here is the link for it [StatusEverywhere ](https://github.com/Strencher/BetterDiscordStuff/tree/development/StatusEverywhere)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by akisblack** [comment]
This is already available as a module on [Better Status Indicators](https://github.com/griefmodz/better-status-indicators).
