### ISSUE TITLE
A port of StaffTag plugin for betterdiscord

### ISSUE THREAD

**Issue by Vertexini** [powercord-community/suggestions#627]
### Description
Port the already available plugin from betterdiscord to Powercord

### More info
Here is the link for it [StaffTag](https://github.com/mwittrien/BetterDiscordAddons/tree/48fd20a04e640adcf58e43f2cda334e3cb8526a1/Plugins/StaffTag)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This already exists: https://github.com/Puyodead1/powercord-ownertag
