### ISSUE TITLE
A port of NoReplyMention plugin for betterdiscord

### ISSUE THREAD

**Issue by Vertexini** [powercord-community/suggestions#628]
### Description
Port the already available plugin from betterdiscord to Powercord

### More info
Here is the link for it [NoReplyMention](https://github.com/BetterDiscordPlugins/userscripts/blob/e8b3bdc3b21ffd13e0004ac10b174edf2d6cef3d/NRM.plugin.js)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This already exists: https://github.com/cyyynthia/better-replies
