### ISSUE TITLE
AutoTranslator

### ISSUE THREAD

**Issue by AlexaRVal** [powercord-community/suggestions#631]
### Description
A translator plugin that hooks into google and iTranslate and can translate what your typing into the specified language. 

### More info
Essentially a port of DevilBros Translation plugin but i would like it to be with commands. like .translate Greek (yep)

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
There already is a plugin.
https://github.com/cyyynthia/message-translate

If you'd like to have a command, open an issue there instead
