### ISSUE TITLE
Search for a YouTube video and paste the link

### ISSUE THREAD

**Issue by FunctionDJ** [powercord-community/suggestions#632]
### Description
Pretty simple plugin. A command to enter a search term, and when sending the message, the YouTube API gets queried and you post the first YouTube result as a normal link into chat.

### More info
This is particularly helpful when sharing music, because not everyone uses the same streaming service like Spotify, but YouTube can be used be everyone, so i often quickly go to YouTube to just search for the song i'm listening to so that i can share it.
Just a simple `.yt search terms` command.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by XeynQ4** [comment]
I will try to do this but it's my first plugin so I'll post update when I finish it or if I give up on it.

**Comment by XeynQ4** [comment]
Done. If there is something wrong, contact me on discord or create an issue (that's the better choice). You can close this  now @cyyynthia.

https://github.com/XeynQ4/powercord-yt-search
