### ISSUE TITLE
Stereo Plugin (Microphone Plugin)

### ISSUE THREAD

**Issue by gk2lit** [powercord-community/suggestions#635]
### Description
This plugin puts stereo on your mic and is supposed to bypass the discord DB limit to prevent your mic from cutting out and sounding muffled if you are too close to it. 

### More info
Stereo Plugins are essentially used to "Loud Mic" or prevent discord from lowering your microphone down if it is too loud.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by rickdtc** [comment]
Not possible, was possible on lightcord because of outdated client, if possible, it still would be against pc guidelines.

**Comment by ghost** [comment]
> Not possible, was possible on lightcord because of outdated client, if possible, it still would be against pc guidelines.

Question, how would this be against PC guidelines?

**Comment by katlyn** [comment]
Creating this plugin to bypass Discord's db limit would be abuse and loud micing is a feature that would really only serve to annoy users, both of which violate guideline 1.

**Comment by ghost** [comment]
oh, fair
