### ISSUE TITLE
Channel Profiles

### ISSUE THREAD

**Issue by AlexaRVal** [powercord-community/suggestions#636]
### Description
Different channel profiles similar to server profiles

### More info
just imagine, a world where you can have individual settings for individual channels for your user. where you can set in one channel your nickname as for example death and the picture is a scythe but the next channel is canary with a bird. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
There's no way for a plugin to enable this kind of functionality with the current APIs that Discord has. Even implementing without touching Discord's API would require a seperate backend and every other user in the guild having the same plugin. This would be better suited as a feature request to Discord itself as the scope is so large.

**Comment by AlexaRVal** [comment]
all good. thank you :>
