### ISSUE TITLE
Revamped Powercord Together (PowerNight)

### ISSUE THREAD

**Issue by MisterZedd** [powercord-community/suggestions#638]
### Description
Looking for a plugin to imitate some of the features Powercord Together had. Mainly the YouTube part, but the games would be a bonus.

### More info
I am not smart so I do not have much technical knowledge to put here, just above description. I think the name “PowerNight” is pretty cool tho lol, combining Power from powercord and night to represent game night or movie night for friends utilizing the plugin.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Powercord Together had no game, nor any real feature, and was simply unlocking upcoming activities feature of Discord. Not to mention a standalone plugin like this would require tons of work (building the games themselves, building the game servers, a place to host the game servers, ...), which isn't realistically achievable by a plugin.

Just wait for Discord's release.
