### ISSUE TITLE
Reddit markdown

### ISSUE THREAD

**Issue by j0hnmeow** [powercord-community/suggestions#64]
### Description
It should highlight `r/subreddit` and `u/user` things like Reddit does. Also maybe autocomplete thing when you type them.

### More info
The plugin should find matches for `/?[ur]/\w{3,20}` regex and highlight them by:

1. Adding icon of corresponding sub/user before the matching string
2. Highlighting them like mentions (without `@` symbol)
3. Make them open the sub/user page in browser/iframe on click

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Rodentman87** [comment]
I think I'll take a crack at this one, seems simple enough, and useful.

**Comment by Rodentman87** [comment]
I've got a version 1 going right now that renders the links here: https://github.com/Rodentman87/reddit-parser

**Comment by Kanin** [comment]
@j0hnmeow does this do everything you wanted it to?

**Comment by j0hnmeow** [comment]
> @j0hnmeow does this do everything you wanted it to?

> 1. Adding icon of corresponding sub/user before the matching string
> 
> 1. Highlighting them like mentions (without `@` symbol)

These two are missing

**Comment by Kanin** [comment]
> > @j0hnmeow does this do everything you wanted it to?
> 
> > 1. Adding icon of corresponding sub/user before the matching string
> > 2. Highlighting them like mentions (without `@` symbol)
> 
> @Kanin These two are missing

@j0hnmeow do you want all of them highlighted like mentions? If so @Rodentman87 if you would like to add these to your plugin, would you please make the features of this toggleable? :) If you do not wish to add these to your plugin this issue is still up for grabs!

**Comment by Rodentman87** [comment]
Yeah, I'll throw those two in there with toggles for them.

**Comment by Rodentman87** [comment]
Those two have both been added with settings to toggle them. 👍

**Comment by j0hnmeow** [comment]
I don't see the difference between links and mentions variant. Also what's wrong with NSFW subs and users?

**Comment by NotExactlyMeButMeh** [comment]
Their icons may contain graphic or NSFW content that the user may not wish to see.

**Comment by j0hnmeow** [comment]
Add another toggle for that?

**Comment by Rodentman87** [comment]
The toggle has been added, it's off by default.

**Comment by Rodentman87** [comment]
I think everything is covered with my plugin now, with toggles for all of it. Let me know if I missed anything with it.
