### ISSUE TITLE
Rich Presence Maker similar to BD version

### ISSUE THREAD

**Issue by CyberGhost047** [powercord-community/suggestions#644]
### Description
Be able to create rich presence just like the autostartrichpresence plugin for BD. No longer works with bdcompat because it causes loop of crahses.

### More info
N/A

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by E-boi** [comment]
already made: https://github.com/E-boi/custom-rpc

**Comment by CyberGhost047** [comment]
Oh my bad, I was searching for rich presence not the abbreviated form
