### ISSUE TITLE
Find users that you share a lot of servers with (common servers)

### ISSUE THREAD

**Issue by FunctionDJ** [powercord-community/suggestions#649]
### Description
A plugin that shows a list of users that are in a lot of servers in that you're also in, so you might find some new friends with lots of shared interests :)

### More info
In vanilla Discord you can see which servers you share with a user on their profile. If querying this data is not too API-heavy, this could be used to generate a list of people that you shared more than X servers with. If this plugin were to be made, a whitelist / blacklist for servers to count into this list would probably be a good idea as a feature down the line.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by pythonmcpi** [comment]
If the users are cached by the client, touching the api should be unnecessary. I might try making a prototype, but I've never done proper UIs so the best I can do is a command that returns clickable user mentions.
