### ISSUE TITLE
Pop Out Window

### ISSUE THREAD

**Issue by skiletro** [powercord-community/suggestions#65]
**Describe the plugin**
The ability to "pop out" a channel or direct message and display it in a separate, smaller window.

**Expected behavior**
The user would Right Click on a channel or direct message and would be given the option to pop out the chat, upon clicking, it would open in a smaller, separate window.

----

The proposed use case would be those would like to keep an eye on a channel w/o having to keep the entire Discord window open, eg to avoid distraction.

![mockup](https://user-images.githubusercontent.com/19377854/71532400-0ab0b580-28eb-11ea-98ec-bb41f41f7679.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by theGordHoard** [comment]
This feature already exists with Bowser's multitask plugin
https://github.com/powercord-community/multitask

**Comment by CodingKanin** [comment]
> 
> 
> This feature already exists with Bowser's multitask plugin
> [powercord-community/multitask](https://github.com/powercord-community/multitask)
