### ISSUE TITLE
A plugin to set a separate default browser just for Discord.

### ISSUE THREAD

**Issue by RiskierSubset** [powercord-community/suggestions#658]
### Description
A plugin that can set a default browser that is different from the system default specifically for Discord.

### More info
As the title and description suggest, I think a plugin that lets you set a specific browser to open links in Discord that is not the system default can be really useful. I know I'm not the only one that uses different browsers for different reasons. Something that will make it even better is the ability to set a default browser for left clicks and a browser list for the right click menu when clicking on a link.  Sorry if this is not possible to achieve with plugins.

Thank you for your time!

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Most of the handling of opening links is done by Electron itself and just forwards it to your system default agent ([docs](https://www.electronjs.org/docs/latest/api/shell/)). Plugins can't inject into these methods unfortunately.
