### ISSUE TITLE
Custom autocomplete 

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#66]
### Description
[p]customautocomplete \<bot> \<prefix> \<command> \<arguments> \<description>
**Aliases:** ca
Would be much easier to have in settings

[p]customautocompletehelp \<query>
**Aliases:** cahelp
Query is either the prefix
 ![image](https://cdn.discordapp.com/attachments/553325417088679938/744374648094851082/auF7AalqLE.png)
 or the prefix and command
 ![image](https://cdn.discordapp.com/attachments/553325417088679938/744374657335033896/ZdLiOMbm1a.png)
 or the bot
 ![image](https://cdn.discordapp.com/attachments/553325417088679938/744374837979643987/a4KxX61c9N.png)
 that would look something like these examples but less shitty. 

### More info
Doesn't actually create a powercord command. Rather autocompletes for actual bot commands.
Would be nice to have some way of custom auto updating bot templates, so the community could make them for specific bots and other people could import them. Ideally Having the bot argument would let you add multiple commands, using the same prefix, but for different bots. Therefore different argument help would be passed. Those examples are ROUGH and it would be much nicer to have them displayed per bot per prefix/command or something better. In auto complete it should show the bot name just before the description as that's what's necessary in that view. I know there's more that I was thinking of earlier but it's not coming to mind now. I'll update this request if it does. 

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by NurMarvin** [comment]
This idea looks like something I'd totally want to do but since I've to do other things as well I'll leave it grabbable for others but as soon as I've completed everything else I'll do this if it's still up for grabs at that point.
So please leave the the idea "up for grabs" so other developers can still claim this if they want to do it before I have time for it ;)
