### ISSUE TITLE
hide invite to server button 

### ISSUE THREAD

**Issue by halsiz** [powercord-community/suggestions#663]
### Description
https://inci.pls-finger.me/5iedHS19v I dont want this button

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by colin273** [comment]
Already exists: https://github.com/SebbyLaw/remove-invite-from-user-context-menu

It's just a bit of CSS, so you could even use a CSS snippet in Quick CSS rather than using a plugin.

**Comment by halsiz** [comment]
i searched but i cant find anyway thank you
