### ISSUE TITLE
Chat commands for Discord's built-in user moderation options.

### ISSUE THREAD

**Issue by Raffael7777** [powercord-community/suggestions#668]
### Description
Chat commands for Discord's timeout/untimeout, kick, and ban/unban, with customizable default settings, for faster "keyboard-only" moderation.

### More info
Chat commands for:
- timeout
- untimeout
- kick
- ban
- unban

Accept either a user mention or a user ID as a valid user argument following the powercord prefix and the command.

Any text following the user argument is set as the reason if the option can accept a reason.

Have a settings menu where default timeout durations and message history deletion durations (for ban) can be set which are applied when the chat command is used (**identical to the duration options present in Discord's client**; custom durations would likely be considered self-botting since they are not possible for a normal client to do).
> this means you don't have to deal with parsing durations and making sure they match a valid Discord preset duration (which you could totally do if you want to, but not necessary)

Obviously these chat commands would not work on servers where the client user does not have the appropriate permissions to perform the selected action.

Not asking for features like temp-ban, soft-ban, or mass-ban, those are self-botting. Only 1-to-1 chat command alternatives for Discord's built-in moderation tools that currently can only be accessed by right-clicking a user and selecting the option with a mouse.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Muatex** [comment]
This feature has already been built into Discord via slash commands.
