### ISSUE TITLE
Password locked server folders

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#67]
### Description
Click on password locked folder and it asks for password. If the password isn't right rick roll them :^) /s

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by LandenStephenss** [comment]
I am going to try to attempt this, but i am not claiming it as of right now

**Comment by TheShadowGamer** [comment]
> I am going to try to attempt this, but i am not claiming it as of right now

Have you gotten anywhere with this? If not I’m gonna attempt it.

**Comment by TheShadowGamer** [comment]
I think I’ll claim this.

**Comment by TheShadowGamer** [comment]
Completed. Also added a feature to lock all of discord, and that one has a Rick roll setting 🙂
Link: https://github.com/TheShadowGamer/Password-Folders
