### ISSUE TITLE
Option to mass unblock

### ISSUE THREAD

**Issue by cyrus01337** [powercord-community/suggestions#676]
### Description
A way to unblock all users that were blocked.

### More info
Can be a button or some sort of command, time-based customisation to control who should be unblocked is a want but not a need - so long as mass unblocking is possible, that's fine. Undo button optional but feel that would be too much IMO.

----

 - [x] I checked if this request wasn't already proposed
 - [x} I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by LandenStephenss** [comment]
This falls under selfbotting (cynthia says)

**Comment by cyrus01337** [comment]
No worries, apologies for the suggestion.
