### ISSUE TITLE
Blur the Dicord Window When It's Unfocused

### ISSUE THREAD

**Issue by Jamalam360** [powercord-community/suggestions#679]
### Description
Blurs the Discord window when it isn't focused (i.e. it isn't being clicked on etc.)

### More info
Focused:
![focused](https://user-images.githubusercontent.com/56727311/148091680-cc532161-6912-44d6-bfe0-5543f3abf64a.png)

Unfocused:
![unfocused](https://user-images.githubusercontent.com/56727311/148091728-e90875a7-c871-4c9a-bab4-47bb80209c95.png)

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This is doable with simple CSS

```css
html:not(.app-focused) { filter: blur(5px) }
```

**Comment by Jamalam360** [comment]
That's perfect, thanks! I didn't realise you could apply a filter to all elements like that
