### ISSUE TITLE
Copy DM Channel ID

### ISSUE THREAD

**Issue by Bowser65** [powercord-community/suggestions#69]
**Describe the plugin**
While DM channels do have IDs allocated to them, Discord doesn't gives an easy way to copy just the DM channel ID, which makes sense since it's useless for a normal Discord use, but can be useful for plugin developers to experiment.

**Expected behavior**
Would add, when developer mode is enabled, a "Copy Channel ID" item below the "Copy ID" item when right clicking on a DM channel. (Copy ID copies the recipient ID)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
_**/resolved**_

This suggestion is no longer up for grabs and should be marked as 'Completed'. You can find a direct link to the plug-in repository below. Thank you.

**Direct link**: [GriefMoDz/copy-dm-channel-id](https://github.com/griefmodz/copy-dm-channel-id) :tada:

**Comment by aetheryx** [comment]
coughs. hold shift while copying a message in dms
