### ISSUE TITLE
Quick CSS button in top bar

### ISSUE THREAD

**Issue by kritishd8** [powercord-community/suggestions#694]
### Description
Just a quick little button to directly open the quick css menu from the top channel bar (the bar that has search button, threads, notifs, inbox and etc.).

### More info
So, basically a quick css button that sits on the top bar of the channel (the inbox, search, threads buttons area) which lets you open the quick css pop up window directly without having to go to settings > themes > quick css > open pop up window.

Its simple but very handy for theme devs like me 👍😁!

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by 12944qwerty** [comment]
Sounds like something to be added in this plugin https://github.com/12944qwerty/css-toggler

**Comment by kritishd8** [comment]
Do it then please 😁

**Comment by 12944qwerty** [comment]
https://github.com/12944qwerty/css-toggler/commit/7acd8941ef468351f447fbf0cbec09afd9f24edc done

**Comment by kritishd8** [comment]
Was way quicker than I expected lol, thanks!
