### ISSUE TITLE
Remove the Favorite button if gif is under 50px

### ISSUE THREAD

**Issue by Spritzerland** [powercord-community/suggestions#698]
### Description
Just remove the favorite button when the gif is under 50px, since it covers some of the gif

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Syncxv** [comment]
if something doesnt work ping me in the plugin dev channel or message me on discord Aria#8171
https://github.com/Syncxv/hide-gif-label
