### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#7]
**Describe the plugin**
Add a button/command to the client that marks all of the user's guilds as read.

**Expected behavior**
You click a button/run a command and.. bam. All of your servers are marked as read.
[Something here might be helpful.. idk](https://github.com/powercord-org/powercord/blob/f0b8bd708a5d1ce8ef86d9ca9df9ccc1724f8e7a/src/Powercord/plugins/pc-guilds/index.js)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by intrnl** [comment]
[intrnl/powercord-read-all](https://github.com/intrnl/powercord-read-all)
Adds mark all guilds as read to context menu
