### ISSUE TITLE
Stereo Microphone

### ISSUE THREAD

**Issue by Khodyn** [powercord-community/suggestions#70]
### Description
The Discord client downmixes your microphone's audio to mono before sending it. This is not a server-side restriction, as custom clients such as [Ripcord](https://cancel.fm/ripcord/) allow you to send audio in stereo.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
As Gord said:
> a plugin like that should probably come with a pretty hefty warning as that's detectable on the server side and it's not normal for user accounts to send stereo audio

**Comment by Khodyn** [comment]
Anyone? I'd love to see this.

**Comment by theGordHoard** [comment]
This has been implemented with https://github.com/AAGaming00/stereo.

**Comment by Methosss** [comment]
how to install this? i pasted it to plugins folder and didn't work

**Comment by BenSegal855** [comment]
Plugins are not installed by manually copying and pasting into your plugins folder. Please see the guide in the pins of #plugin-support in our [Discord server](https://discord.gg/gs4ZMbBfCh).

**Comment by Methosss** [comment]
actually plugin is seems to be loaded, i'll check discord

**Comment by warsogasp** [comment]
hmmm, interesting
