### ISSUE TITLE
Shortkey to disable all plugins and themes for fast screenshot/screen record

### ISSUE THREAD

**Issue by Bricklou** [powercord-community/suggestions#701]
### Description
Be able to have a shortcut that will quickly toggle plugins and themes states.

### More info
The main goal is to prevent problem when making screenshots and screen record of discord for others servers. This way other will no see that we are using a modded client.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
[Panikk](https://github.com/LandenStephenss/Panikk) already exists.

**Comment by Bricklou** [comment]
I wasn't thinking of a plugin that works this way but this will do the trick.
