### ISSUE TITLE
Easily mention voice channels

### ISSUE THREAD

**Issue by Spritzerland** [powercord-community/suggestions#709]
### Description
Mention a voice channel in chat

### More info
Make a plugin where you can easily mention voice channels the same way text channels do. Find the id of the voice channel, then put it in a <#channel-id> 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NurMarvin** [comment]
Type `#!` in chat.

**Comment by Vendicated** [comment]
stock feature, type #!
