### ISSUE TITLE
Retain and show deleted messages

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#723]
### Description
Retain and display deleted messages from text channels
### More info
Idk if this is possible for all deleted messages, but maybe just ones that have been sent while viewing the channel?

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
![image](https://user-images.githubusercontent.com/34194692/166121977-a22603db-d92d-40f9-9126-cb0f6e843fa3.png)
Have you though?
