### ISSUE TITLE
A Working Dad Joke Plugin

### ISSUE THREAD

**Issue by AlecXtra** [powercord-community/suggestions#729]
### Description
Since the previous plugin wasn't working for some reason, I would love to see a working one if it's possible.

### More info
It's basically like the 'motivaion' plugin but instead it will send Dad Jokes.
More specifically it will be something like {prefix}joke

----

 - [x] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by FC5570** [comment]
https://github.com/FC5570/powercord-random-dadjoke
