### ISSUE TITLE
Custom Css/Scss

### ISSUE THREAD

**Issue by UPPERCASEuser** [powercord-community/suggestions#73]
<h1 align=center><b>Describe the plugin</b></h1>
Add a custom css menu to add css/scss code for testing

<h1 align=center><b>Expected behavior</b></h1>
Adds a menu called "Custom Css/Scss" that contains

* A css/scss editor
* A button to update the css/scss
* (probally) Auto-update
* Auto-save (or a button to save)

Its like Custom Css from BD

----

 - [x] I checked if this request wasn't already proposed

 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
That's something already planned for Powercord itself, even though there aren't any opened issues about it there. I'll mention in powercord-org/powercord#81

**Comment by UPPERCASEuser** [comment]
Oh, thanks. Have a nice day
