### ISSUE TITLE
Display Current Sessions

### ISSUE THREAD

**Issue by Gyrox2699** [powercord-community/suggestions#733]
### Description
A plugin to display currently logged in sessions for your discord account

### More info
This could be displayed in the "My Account" tab of the discord settings and give information about the sessions that are logged in.
for example, if they are mobile or PC, the ID of the session

all similar to the plugin for betterdiscord that does the same thing. 

i have tried to run the betterdiscord plugin for this using the powercord plugin to do so, but it seems to always cause a crash when i click on the account tab in setings

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
This plugin has already been created as Oocrop's [show-sessions](https://github.com/Oocrop/show-sessions) plugin.
