### ISSUE TITLE
Auto BD plugin loader

### ISSUE THREAD

**Issue by kittykush** [powercord-community/suggestions#74]
Self explanatory. 

I think it would be easier for users like me who misses BD aspects whilst using PC.

**Comment by ghostlydilemma** [comment]
if you are searching for a BD compatibility layer for Powercord, there already is one
https://github.com/juby210-PL/bdCompat
I think it still works

**Comment by CodingKanin** [comment]
As Emma said it already exists, you also failed to use the suggestion format which makes sure you check fort things like this. Please use it in the future :)
