### ISSUE TITLE
Nitro Spam remover.

### ISSUE THREAD

**Issue by MagmaSlime123** [powercord-community/suggestions#744]
### Description
I bet this'll just get insta-closed, but I really don't get why Discord loves spamming ads about Nitro everywhere. I know it exists, but seriously, you don't need to put it in the server list too...
![image](https://user-images.githubusercontent.com/51277766/177008874-26ed045a-c1d8-4ecf-92a9-d0aeeaaaaf90.png)

### More info
N/A

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by asportnoy** [comment]
You can do this with a CSS snippet that sets `display: none;` on the class selectors for that element. No plugin needed.

**Comment by MagmaSlime123** [comment]
Oh? No clue how to make themes, hence why I asked here.
Sorry for putting this in the wrong area.

**Comment by asportnoy** [comment]
You don't need a whole theme, just a quick CSS snippet. If you need help doing that, I recommend asking in the support server.

**Comment by MagmaSlime123** [comment]
Alright, sorry.
