### ISSUE TITLE
Prevent accidentally moving channels

### ISSUE THREAD

**Issue by asportnoy** [powercord-community/suggestions#747]
### Description
On some servers I'm admin in, I sometimes accidentally rearrange channels when I'm just trying to scroll down the list or switch to another channel. It would be nice to have a plugin that prevents dragging the channels unless I press a certain button/checkbox/switch.

### More info
Maybe add a checkbox under the server context menu? Would fit in well with the native design.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Captain8771** [comment]
until someone makes this you could use some duct tape

 ![image](https://cdn.discordapp.com/attachments/816969327504392243/995350873494523904/unknown.png)

**Comment by 12944qwerty** [comment]
https://github.com/12944qwerty/no-admin-abuse
