### ISSUE TITLE
automatically capitalize the first letter of every sentence

### ISSUE THREAD

**Issue by Rainerss** [powercord-community/suggestions#75]
**Describe the plugin**
automatically capitalize the first letter of every sentence

**Expected behavior**
^^^

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
I updated your request to follow the suggestion format, please use it from now on.

**Comment by Swishilicous** [comment]
I technically made a plugin that does this (+ other things) but I can make a plugin that only does the thing mentioned here if that would be preferred.

**Comment by CodingKanin** [comment]
> I technically made a plugin that does this (+ other things) but I can make a plugin that only does the thing mentioned here if that would be preferred.

@Swishilicous are the other things toggleable?

**Comment by Swishilicous** [comment]
I'm currently working on that but I've been having trouble figuring out how the Settings.jsx file and all that stuff work with the actual plugin :/

**Comment by CodingKanin** [comment]
> @CodingKanin I'm currently working on that but I've been having trouble figuring out how the Settings.jsx file and all that stuff work with the actual plugin :/

I believe in you!

**Comment by Swishilicous** [comment]
I added the functionality to disable and enable specific settings.

**Comment by CodingKanin** [comment]
You can now get this feature from [here!](https://github.com/Swishilicous/grammar-nazi)
