### ISSUE TITLE
Custom mute duration

### ISSUE THREAD

**Issue by Juby210** [powercord-community/suggestions#76]
**Describe the plugin**
Context menu item for mute channel/guild for eg. 3 hours. There may also be context menu item that shows the modal with a selection until when the channel/guild is to be muted.

**Expected behavior**
^^^

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Custom unmute duration could be nice as well

**Comment by Juby210** [comment]
done,
https://github.com/Juby210/custom-mute
