### ISSUE TITLE
Custom User Tags

### ISSUE THREAD

**Issue by gdude2002** [powercord-community/suggestions#77]
### Description
I noticed that `creatable` [posted a CSS snippet on the Discord server last night](https://user-images.githubusercontent.com/204153/73530944-64882c00-4411-11ea-9cae-4e061e6b7f94.png), and it reminded me of something a friend of mine asked me about some time ago.

Essentially, some users have issues remembering who is who when they're in large groups of people they know by real name, and (I'm sure) in other situations as well. A plugin that allows you to add a custom tag to individual users would be extremely useful for those people, and would probably be helpful as an accessibility feature.

### More info
Pretty simply:

1. User may right-click on a user (or perhaps go to their profile) to get an option to set up a custom tag for them
2. User can set the text of the custom tag (colour would be nice as well)
3. ![image](https://user-images.githubusercontent.com/204153/73531351-2b9c8700-4412-11ea-8a0c-b749d2cb3946.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
As said in #120 it would also be nice to be able to customize the already built-in tags!

**Comment by hmBxnny** [comment]
I think there already is a plugin which you can use for something like that.

If I'm not wrong, it's called `Custom User Tags`
You can set custom text, color and choose the user you want by their User ID. It's A plugin to customize at the ** User Settings** menu.

**Comment by Bowser65** [comment]
https://github.com/HooferDevelops/Custom-User-Tags
