### ISSUE TITLE
Enhanced Discord compatibility layer

### ISSUE THREAD

**Issue by ohlookitsderpy** [powercord-community/suggestions#78]
**Describe the plugin**
[bdcompat](https://github.com/Juby210/bdCompat) but it's edcompat. Useful for users who want to switch to the great Powercord:tm:

**Expected behavior**
The ED codebase looks to be less bloated than BD, so this *should* be fairly easy to achieve.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Cr3atable** [comment]
the massive lack of ED plugins (besides the default ones) makes this seem not very worthwhile in my opinion

**Comment by Juby210** [comment]
~~look at this: https://github.com/Juby210/EDPluginsLoader~~
![image](https://user-images.githubusercontent.com/31005896/73549725-6b2f9700-4443-11ea-9b07-327f048acf46.png)

**Comment by ohlookitsderpy** [comment]
Closing since EDPluginsLoader works on Powercord.

@Juby210, could you possibly add a note into bdcompat (or even add built-in support) saying that it works with ED plugins too using the plugin loader please?

**Comment by Juby210** [comment]
sure, I'll add later

**Comment by ohlookitsderpy** [comment]
thanks
