### ISSUE TITLE
Hide nitro emojis

### ISSUE THREAD

**Issue by Atakku** [powercord-community/suggestions#79]
**Describe the plugin**
Plugin would look for divs with class `emojiItem-* disabled-*` and remove them on click on emoji menu

**Expected behavior**
Hide unusable emojis (For nitro free users who want to use global emojis)
----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Juby210** [comment]
duplicate #10 
https://github.com/NurMarvin/discord-tweaks
