### ISSUE TITLE
Guild icons in emoji list

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#8]
**Describe the plugin**
Apparently on iOS there are guild icons in the emoji list, something cool on iOS :o

**Expected behavior**
Seems like you can select which guild you want to pull emojis from in the emoji picker itself, neat.

![image](https://user-images.githubusercontent.com/29491781/67614880-4cf63300-f792-11e9-99c2-b73ef1d705c1.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This has been implemented by Discord themselves in their new emoji picker
