### ISSUE TITLE
Open Links in an internal discord window

### ISSUE THREAD

**Issue by abUwUser** [powercord-community/suggestions#80]
### Description
When you click on a link it opens a window with the page displaying. Like [OpenLinksInDiscord](https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/OpenLinksInDiscord.plugin.js) made by Metalloriff, a BD plugin dev.

(and the part of opening with `ctrl` pressed or any key wont be in the plugin)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
Removing the ctrl part seems anything but a good idea, but anyway. Updated the link to be the actual link to the plugin

**Comment by SomeAspy** [comment]
this should do it. https://github.com/ploogins/powercord-openlinks
