### ISSUE TITLE
Automatic Mute Duration Chooser

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#82]
**Describe the plugin**
I always forget the 2nd menu after clicking mute and automatically click away. It would be nice to set an automatic set amount of time for a channel to be muted when you click on mute.

**Expected behavior**
Adds a settings page where you can specify the automatic applied amount of time when clicked on mute.

A little plus if anyone can do it:
  Shift + Click should open the usual time chooser menu.

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Juby210** [comment]
claimed

**Comment by Juby210** [comment]
done,

https://github.com/Juby210/default-mute-duration-chooser
