### ISSUE TITLE
Hover over links

### ISSUE THREAD

**Issue by Ser-Ames** [powercord-community/suggestions#84]
**Describe the plugin**
Hovering over a link will preview the meta data or image that the link points to

**Expected behavior**
Hovering over a link will create a pop up above or below the link that shows the data that the link points to. This could be a user setting, a channel setting, or both. The links and images are not loaded when the link is sent, only when hovered.

This plugin could also work with images and files too, where it places the file name into a box similar to the one that appears when uploading a file that has the same functionality as a link when hovered.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This request is still pending review, and I believe the main reason for it is that people who initially reviewed didn't understand the request. Could you clarify the feature you want?

As I understand it it'd basically be the same thing as embeds Discord already generates..?

**Comment by Ser-Ames** [comment]
to be honest i cant really remember what i was requesting, so im going to close it
