### ISSUE TITLE
Blob Emoji Font / Custom Emoji Font

### ISSUE THREAD

**Issue by Ominitay** [powercord-community/suggestions#88]
### Description
This plugin would either:
A) Replace the default Discord emojis with blob emojis ([this repo has a continued version of them](https://github.com/C1710/blobmoji)).
B) Replace the default Discord emojis with any emojis in the form of ~~a .tff file~~ _a set of images_.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by RenegadeAmigo** [comment]
It turns out that emojis in discord aren't from a font, but rather are images. A plugin exactly like what I am requesting for Powercord was made for EnhacedDiscord ([here](https://github.com/joe27g/EnhancedDiscord-Plugins/blob/master/emoji_packs.js)), so it should be doable.
