### ISSUE TITLE
Scrollable chat emoji list

### ISSUE THREAD

**Issue by CodingKanin** [powercord-community/suggestions#9]
**Describe the plugin**
Essentially this list is scrollable ![Image](https://kanin.cannot.date/2019/10/26/h7VxkwhLJ8.png)

**Expected behavior**
Read above

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
**_/resolved_**

This suggestion is no longer up for grabs and should be marked as 'Completed'. You can find a direct link to the plug-in repository below. Thank you.

**Direct link**: [GriefMoDz/scrollable-autocomplete](https://github.com/griefmodz/scrollable-autocomplete) :tada:
