### ISSUE TITLE
Remove friend request notifications

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#90]
### Description
Have options to remove both the badge on the taskbar and the badge on the home button for friend requests.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
Request is up for grabs again

**Comment by CodingKanin** [comment]
https://github.com/hellbound1337/begone-app-badge
