### ISSUE TITLE
Better Invis Mode

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#91]
**Describe the plugin**
Automatic hide typing status in invisible mode. Privacy and better lurking!

**Expected behavior**
Basically, when you are in "Invisible" mode/status, it should also hide your typing status for enhanced lurking. 
(i always accidentaly activate the chat bar and sends a typign status when lurking)

----

 - [x] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Drylotrans** [comment]
I did it, [Drylotrans/better-invisible](https://github.com/Drylotrans/better-invisible)

**Comment by Bowser65** [comment]
I am fairly certain of from where you grabbed the typing injection, however this is not the recommended way of doing it. In theory you're supposed to use both inject and uninject methods available in `powercord/injector` package

**Comment by Drylotrans** [comment]
Okay, I edited it ([v1.0.1](https://github.com/Drylotrans/better-invisible/commit/987733eea5189098c9415d83d602247014e8f93f)) and I used the `powercord/injector` package in that version
