### ISSUE TITLE
Fake Connections

### ISSUE THREAD

**Issue by zzzmario** [powercord-community/suggestions#92]
**Describe the plugin**
 Create fake connections in the connections tab
 
 **Expected behavior**
 https://github.com/SnazzahDI/FakeConnections
 
 * [x]  I checked if this request wasn't already proposed
 * [x]  I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by ohlookitsderpy** [comment]
Claimed (for now)

**Comment by ohlookitsderpy** [comment]
Apologies, I'm currently too busy to work on this. Feel free to open it up again.

**Comment by Bowser65** [comment]
uh, any specific reason for closing this issue?

**Comment by zzzmario** [comment]
fake connections are patched
