### ISSUE TITLE
Undertale Text Box Generator Button

### ISSUE THREAD

**Issue by Mr-Foxtrot** [powercord-community/suggestions#94]
### Description
This plugin would be a simple and faster way to generate Undertale text boxes from [Demirramon's Hideout](https://www.demirramon.com/en/generators/undertale_text_box_generator) and send them directly without a link, all for fun of course.

This plugin would add a button similar to the emoji button to the text area that upon clicking it opens a popup menu to customize a Undertale/Deltarune box before sending it __directly__.

### More info
![image](https://user-images.githubusercontent.com/45246118/80535163-5ee9a600-896e-11ea-9797-4b5a0121da20.png)
![image](https://user-images.githubusercontent.com/45246118/80537799-9d815f80-8972-11ea-8e4d-8eedef39aff7.png)
![image](https://user-images.githubusercontent.com/45246118/80541955-26e86000-897a-11ea-9ea9-da7cae190211.png)
Entries shown above with arrows are dropdown menus allowing you to pick and choose from what is available instead of typing the names. This menu should have a live preview below the options to see how it's coming together.
(Original layout borrowed from Kyza's SendSafeEmbeds BD plugin, this being a conceptual image of course)

The settings menu should allow you to set default settings for quick Box generation and place image URL's as custom character entries.

Generating boxes via the plugin can be done all by modifying a URL, as [all the configurable data is in the URL](https://demirramon.com/en/help/undertale_text_box_generator_dev) of the image as modifying the various options in the URL will change how the image is shown.
(this image should be sent directly as an upload rather than a link if possible.)

This idea might be ridiculous or a waste of time but, it's just a neat Idea I have had in the back of my mind for a while and thought I might as well put it out there for anyone who wants to try their hand at creating such a plugin.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Controlfreak707** [comment]
[Here ya go.](https://github.com/Controlfreak707/undertale-dialog-generator)
It's not completely done yet though, sorry.

**Comment by Controlfreak707** [comment]
Um... anyone going to close this and add the **completed** label...?
