### ISSUE TITLE
Better Toolstips.

### ISSUE THREAD

**Issue by LandenStephenss** [powercord-community/suggestions#95]
### Description
A plugin that will add a tooltip to the custom status emojis, since discord does not have a tooltip for those emojis. Currently whenever you try to hover over the custom status emoji it does nothing, with this you should be able to see a tooltip with the emoji name.

### More info
This could be bundled with a plugin that adds better tooltips to places.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by theGordHoard** [comment]
Discord now provides tooltips on custom status emoji.
![image](https://user-images.githubusercontent.com/17418611/102739564-af04e680-430a-11eb-8eda-3aa96397f3e1.png)
As the second part of this suggest has not had any additional information added to it, we'll close this issue for now (and update the issue title to better reflect the main suggestion).
