### ISSUE TITLE
Hover Color Codes

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#97]
### Description
On hover over any color code (#rrggbb / #rrggbbaa / rgb(r,g,b) / rgba(r,g,b,a)) shows a pop up with a square, being the color of the code.

Hovering shows up a pop up styled similar to all the other/ the emote hover plugin alike style. On rgba colors, the background should be white and black behind the actual color. This would be a nice addition and lets you preview color codes without having to google them or putting them in your quick css.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by UPPERCASEuser** [comment]
it should be only shown when using devtools and with the inspect element enabled?

**Comment by mrrobboss** [comment]
> it should be only shown when using devtools and with the inspect element enabled?

No, just all the time but with a delay.

**Comment by TrueXPixels** [comment]
That sounds useful, I'll give it a shot.

**Comment by TrueXPixels** [comment]
Here you go: https://github.com/TrueXPixels/powercord-message-tooltips

This is my first working with React component injection in Powercord, so please let me know if there are any issues. Thank you!

![](https://i.plexidev.org/1Gdzuok.gif)
