### ISSUE TITLE
Persistent Hidden Channel History

### ISSUE THREAD

**Issue by Hexcede** [powercord-community/suggestions#99]
**Describe the plugin**
Normally, Discord allows you to view content recently sent in a channel with its history hidden. Their messages are stored their until either A. You have reloaded the client or B. You have not loaded the channel recently (perhaps related to cache).

For me it would be extremely useful to be able to both A. Always receive messages in these channels even if I'm not directly looking at said channel and B. Keep their content until the client has been restarted.

**Expected behavior**
Channels with "hidden history" store content even while the channel or its guild is not currently being viewed, and this content will always be kept until the client is reloaded rather than being discarded after a while.

**Extra behaviour (probably unlikely)**
I'd like to look into whether or not keeping messages permanently is acceptable, however, I suspect that Discord ToS would not allow for this, and it sort of falls under the same category as storing deleted messages in my opinion, so I find it really unlikely that this would be allowed. If someone wants to look into that (I'm not asking you to) and potentially implement something like this (assuming it's allowed under ToS and guidelines!) that'd be awesome. If you do that, it'd be nice to have a message from Clyde (alternatives) between sessions to know when content may have been missed.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by ghostlydilemma** [comment]
Interesting submission but I am relatively certain that it'd break [Guideline Rule 3](https://github.com/powercord-community/guidelines#3-no-circumvention-of-discord-permissions) as message history is a permission given to one. Storing stuff temporarily would still result in storing messages you wouldn't be able to see with a vanilla client due to the permissions given to you.
I might be misunderstanding the submission so it's up for discussion

**Comment by Hexcede** [comment]
> Interesting submission but I am relatively certain that it'd break [Guideline Rule 3](https://github.com/powercord-community/guidelines#3-no-circumvention-of-discord-permissions) as message history is a permission given to one. Storing stuff temporarily would still result in storing messages you wouldn't be able to see with a vanilla client due to the permissions given to you.
> I might be misunderstanding the submission so it's up for discussion
This is definitely a good point and I agree that it is along the same lines... I don't believe that it should be considered to be against ToS though. You can really already achieve this exact behaviour in vanilla Discord by having a Discord tab open in chrome or something on a channel with its history disabled, I'm sort of asking for a slightly more convenient version of this.

I didn't really share my intentions for this, and I can see how it might be used maliciously, but users using this maliciously can still have the same results without a plugin. My intentions are basically just to be able to respond to content in bug reports in a game's Discord server (kinda to discourage invalid reports) as I know a lot about the game's inner workings as well as the engine it runs on (Roblox haha). Their content was hidden a while back by one of the devs to stop people from posting spam/jokes (e.g. posting "I can't win when I hack" as a bug lol).

Discord actively sends messages from these channels to your client and will display and store those messages as long as you're viewing the channel. Even if you were to switch channels/servers, having any messages stored in the channel generally means that new messages are also stored until Discord decides to clear their content (which usually happens if you don't view the channel for a while and always happens when you restart your client).

**Comment by ghostlydilemma** [comment]
I can see the intention behind it, but it's still very borderline regarding the third rule. It's probably a much safer way to ask the admins/mods on that server to give you read permission on that channel to be able to respond to the people in question. I see where you are coming from and I am very certain that you wouldn't use it for any malicious purposes, yet it's still pretty eh.
It's something that gets around a permission and is not possible *without inconvenience* in Vanilla

**Comment by Hexcede** [comment]
> I can see the intention behind it, but it's still very borderline regarding the third rule. It's probably a much safer way to ask the admins/mods on that server to give you read permission on that channel to be able to respond to the people in question. I see where you are coming from and I am very certain that you wouldn't use it for any malicious purposes, yet it's still pretty eh.
> It's something that gets around a permission and is not possible _without inconvenience_ in Vanilla

I have to agree with you, and I guess I didn't really think about it this way. I'll close this
